{
  "name": "Sales",
  "compatibilityLevel": 1200,
  "model": {
    "culture": "nl-BE",
    "dataSources": [
      {
        "name": "sibgrpudmsqlsrvd0001",
        "connectionString": "Provider=SQLOLEDB.1;Persist Security Info=true;User ID=SibelcoAdmin;Initial Catalog=sibgrpudmdbd0002;Data Source=sibgrpudmsqlsrvd0001.database.windows.net",
        "impersonationMode": "impersonateServiceAccount",
        "annotations": [
          {
            "name": "ConnectionEditUISource",
            "value": "SqlServer"
          }
        ]
      }
    ],
    "tables": [
      {
        "name": "Accounting Currency",
        "columns": [
          {
            "name": "DIM_Currency_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_Currency_SKEY"
          },
          {
            "name": "Currency Code",
            "dataType": "string",
            "sourceColumn": "CurrencyCode"
          },
          {
            "name": "Currency Description",
            "dataType": "string",
            "sourceColumn": "CurrencyDescription"
          },
          {
            "name": "ISO Code",
            "dataType": "string",
            "sourceColumn": "ISOCode"
          },
          {
            "name": "Last Updated",
            "dataType": "dateTime",
            "sourceColumn": "LastUpdated"
          },
          {
            "name": "DIM_DataForest_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_DataForest_SKEY"
          },
          {
            "name": "ISO Description",
            "dataType": "string",
            "sourceColumn": "ISODescription"
          }
        ],
        "partitions": [
          {
            "name": "vwDimCurrency",
            "source": {
              "query": "SELECT [dbo].[vDimCurrency].[DIM_Currency_SKEY],[dbo].[vDimCurrency].[CurrencyCode],[dbo].[vDimCurrency].[CurrencyDescription],[dbo].[vDimCurrency].[ISOCode],[dbo].[vDimCurrency].[ISODescription],[dbo].[vDimCurrency].[LastUpdated],[dbo].[vDimCurrency].[DIM_DataForest_SKEY] FROM [dbo].[vDimCurrency] where DIM_DataForest_SKEY like '20%'",
              "dataSource": "sibgrpudmsqlsrvd0001"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT [dbo].[vDimCurrency].[DIM_Currency_SKEY],[dbo].[vDimCurrency].[CurrencyCode],[dbo].[vDimCurrency].[CurrencyDescription],[dbo].[vDimCurrency].[ISOCode],[dbo].[vDimCurrency].[ISODescription],[dbo].[vDimCurrency].[LastUpdated],[dbo].[vDimCurrency].[DIM_DataForest_SKEY] FROM [dbo].[vDimCurrency] where DIM_DataForest_SKEY like '20%'</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "vDimCurrency"
          },
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": "SELECT [dbo].[vDimCurrency].[DIM_Currency_SKEY],[dbo].[vDimCurrency].[CurrencyCode],[dbo].[vDimCurrency].[CurrencyDescription],[dbo].[vDimCurrency].[ISOCode],[dbo].[vDimCurrency].[ISODescription],[dbo].[vDimCurrency].[LastUpdated],[dbo].[vDimCurrency].[DIM_DataForest_SKEY] FROM [dbo].[vDimCurrency] where DIM_DataForest_SKEY like '20%'"
          },
          {
            "name": "QueryEditorSerialization",
            "value": "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT [dbo].[vDimCurrency].[DIM_Currency_SKEY],[dbo].[vDimCurrency].[CurrencyCode],[dbo].[vDimCurrency].[CurrencyDescription],[dbo].[vDimCurrency].[ISOCode],[dbo].[vDimCurrency].[ISODescription],[dbo].[vDimCurrency].[LastUpdated],[dbo].[vDimCurrency].[DIM_DataForest_SKEY] FROM [dbo].[vDimCurrency] where DIM_DataForest_SKEY like '20%'</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
          }
        ]
      },
      {
        "name": "Customer",
        "columns": [
          {
            "name": "DIM_Customer_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_Customer_SKEY"
          },
          {
            "name": "Customer Number",
            "dataType": "string",
            "sourceColumn": "CustomerNumber"
          },
          {
            "name": "Customer Name",
            "dataType": "string",
            "sourceColumn": "CustomerName"
          },
          {
            "name": "Customer Short Name",
            "dataType": "string",
            "sourceColumn": "CustomerShortName"
          },
          {
            "name": "Fiscal Code",
            "dataType": "string",
            "sourceColumn": "FiscalCode"
          },
          {
            "name": "Customer Group Code",
            "dataType": "string",
            "sourceColumn": "CustomerGroupCode"
          },
          {
            "name": "Customer Group Description",
            "dataType": "string",
            "sourceColumn": "CustomerGroupDescription"
          },
          {
            "name": "Category Code",
            "dataType": "string",
            "sourceColumn": "CategoryCode"
          },
          {
            "name": "Sales Representative Code",
            "dataType": "string",
            "sourceColumn": "SalesRepresentativeCode"
          },
          {
            "name": "Sales Representative Name",
            "dataType": "string",
            "sourceColumn": "SalesRepresentativeName"
          },
          {
            "name": "State Code",
            "dataType": "string",
            "sourceColumn": "StateCode"
          },
          {
            "name": "Zip Code",
            "dataType": "string",
            "sourceColumn": "ZipCode"
          },
          {
            "name": "City",
            "dataType": "string",
            "sourceColumn": "City"
          },
          {
            "name": "Region Name",
            "dataType": "string",
            "sourceColumn": "RegionName"
          },
          {
            "name": "Segment Description",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "SegmentDescription"
          },
          {
            "name": "Country Description",
            "dataType": "string",
            "sourceColumn": "CountryDescription"
          },
          {
            "name": "Legal Entity Code",
            "dataType": "string",
            "sourceColumn": "LegalEntityCode"
          },
          {
            "name": "Country Code",
            "dataType": "string",
            "sourceColumn": "CountryCode"
          },
          {
            "name": "Currency Code",
            "dataType": "string",
            "sourceColumn": "CurrencyCode"
          },
          {
            "name": "Terms Of Payment Code",
            "dataType": "string",
            "sourceColumn": "TermsOfPaymentCode"
          },
          {
            "name": "Method Of Payment Code",
            "dataType": "string",
            "sourceColumn": "MethodOfPaymentCode"
          },
          {
            "name": "Customer Stat Group Code",
            "dataType": "string",
            "sourceColumn": "CustomerStatGroupCode"
          },
          {
            "name": "Customer Stat Group Description",
            "dataType": "string",
            "sourceColumn": "CustomerStatGroupDescription"
          },
          {
            "name": "Bill To Address",
            "dataType": "string",
            "sourceColumn": "BillToAddress"
          },
          {
            "name": "Credit Limit",
            "dataType": "double",
            "sourceColumn": "CreditLimit"
          },
          {
            "name": "Credit Parent",
            "dataType": "string",
            "sourceColumn": "CreditParent"
          },
          {
            "name": "Shale Play Code",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "ShalePlayCode"
          },
          {
            "name": "SIC Code",
            "dataType": "string",
            "sourceColumn": "SICCode"
          },
          {
            "name": "Created Date",
            "dataType": "dateTime",
            "sourceColumn": "CreatedDate"
          },
          {
            "name": "Last Updated",
            "dataType": "dateTime",
            "sourceColumn": "LastUpdated"
          },
          {
            "name": "DIM_ShalePlay_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_ShalePlay_SKEY"
          },
          {
            "name": "DIM_DataForest_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_DataForest_SKEY"
          },
          {
            "name": "DIM_CustomerHierarchy_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_CustomerHierarchy_SKEY"
          },
          {
            "name": "Payer Number",
            "dataType": "string",
            "sourceColumn": "Payer"
          },
          {
            "name": "Payer Name",
            "dataType": "string",
            "sourceColumn": "PayerName"
          },
          {
            "name": "Customer Loyalty",
            "dataType": "string",
            "sourceColumn": "CustomerLoyalty"
          }
        ],
        "partitions": [
          {
            "name": "vwDimCustomer",
            "source": {
              "query": "SELECT [dbo].[vDimCustomer].[DIM_Customer_SKEY],[dbo].[vDimCustomer].[CustomerNumber],[dbo].[vDimCustomer].[CustomerName],[dbo].[vDimCustomer].[CustomerShortName],[dbo].[vDimCustomer].[FiscalCode],[dbo].[vDimCustomer].[CustomerGroupCode],[dbo].[vDimCustomer].[CustomerGroupDescription],[dbo].[vDimCustomer].[SegmentDescription],[dbo].[vDimCustomer].[CategoryCode],[dbo].[vDimCustomer].[SalesRepresentativeCode],[dbo].[vDimCustomer].[SalesRepresentativeName],[dbo].[vDimCustomer].[CountryDescription],[dbo].[vDimCustomer].[StateCode],[dbo].[vDimCustomer].[ZipCode],[dbo].[vDimCustomer].[City],[dbo].[vDimCustomer].[RegionName],[dbo].[vDimCustomer].[LegalEntityCode],[dbo].[vDimCustomer].[CountryCode],[dbo].[vDimCustomer].[CurrencyCode],[dbo].[vDimCustomer].[TermsOfPaymentCode],[dbo].[vDimCustomer].[MethodOfPaymentCode],[dbo].[vDimCustomer].[CustomerStatGroupCode],[dbo].[vDimCustomer].[CustomerStatGroupDescription],[dbo].[vDimCustomer].[Payer],[dbo].[vDimCustomer].[PayerName],[dbo].[vDimCustomer].[BillToAddress],[dbo].[vDimCustomer].[CreditLimit],[dbo].[vDimCustomer].[CreditParent],[dbo].[vDimCustomer].[ShalePlayCode],[dbo].[vDimCustomer].[SICCode],[dbo].[vDimCustomer].[CreatedDate],[dbo].[vDimCustomer].[LastUpdated],[dbo].[vDimCustomer].[DIM_ShalePlay_SKEY],[dbo].[vDimCustomer].[CustomerLoyalty],[dbo].[vDimCustomer].[DIM_DataForest_SKEY],[dbo].[vDimCustomer].[DIM_CustomerHierarchy_SKEY] FROM [dbo].[vDimCustomer] where DIM_DataForest_SKEY like '20%'",
              "dataSource": "sibgrpudmsqlsrvd0001"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT [dbo].[vDimCustomer].[DIM_Customer_SKEY],[dbo].[vDimCustomer].[CustomerNumber],[dbo].[vDimCustomer].[CustomerName],[dbo].[vDimCustomer].[CustomerShortName],[dbo].[vDimCustomer].[FiscalCode],[dbo].[vDimCustomer].[CustomerGroupCode],[dbo].[vDimCustomer].[CustomerGroupDescription],[dbo].[vDimCustomer].[SegmentDescription],[dbo].[vDimCustomer].[CategoryCode],[dbo].[vDimCustomer].[SalesRepresentativeCode],[dbo].[vDimCustomer].[SalesRepresentativeName],[dbo].[vDimCustomer].[CountryDescription],[dbo].[vDimCustomer].[StateCode],[dbo].[vDimCustomer].[ZipCode],[dbo].[vDimCustomer].[City],[dbo].[vDimCustomer].[RegionName],[dbo].[vDimCustomer].[LegalEntityCode],[dbo].[vDimCustomer].[CountryCode],[dbo].[vDimCustomer].[CurrencyCode],[dbo].[vDimCustomer].[TermsOfPaymentCode],[dbo].[vDimCustomer].[MethodOfPaymentCode],[dbo].[vDimCustomer].[CustomerStatGroupCode],[dbo].[vDimCustomer].[CustomerStatGroupDescription],[dbo].[vDimCustomer].[Payer],[dbo].[vDimCustomer].[PayerName],[dbo].[vDimCustomer].[BillToAddress],[dbo].[vDimCustomer].[CreditLimit],[dbo].[vDimCustomer].[CreditParent],[dbo].[vDimCustomer].[ShalePlayCode],[dbo].[vDimCustomer].[SICCode],[dbo].[vDimCustomer].[CreatedDate],[dbo].[vDimCustomer].[LastUpdated],[dbo].[vDimCustomer].[DIM_ShalePlay_SKEY],[dbo].[vDimCustomer].[CustomerLoyalty],[dbo].[vDimCustomer].[DIM_DataForest_SKEY],[dbo].[vDimCustomer].[DIM_CustomerHierarchy_SKEY] FROM [dbo].[vDimCustomer] where DIM_DataForest_SKEY like '20%'</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "vDimCustomer"
          },
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": "SELECT [dbo].[vDimCustomer].[DIM_Customer_SKEY],[dbo].[vDimCustomer].[CustomerNumber],[dbo].[vDimCustomer].[CustomerName],[dbo].[vDimCustomer].[CustomerShortName],[dbo].[vDimCustomer].[FiscalCode],[dbo].[vDimCustomer].[CustomerGroupCode],[dbo].[vDimCustomer].[CustomerGroupDescription],[dbo].[vDimCustomer].[SegmentDescription],[dbo].[vDimCustomer].[CategoryCode],[dbo].[vDimCustomer].[SalesRepresentativeCode],[dbo].[vDimCustomer].[SalesRepresentativeName],[dbo].[vDimCustomer].[CountryDescription],[dbo].[vDimCustomer].[StateCode],[dbo].[vDimCustomer].[ZipCode],[dbo].[vDimCustomer].[City],[dbo].[vDimCustomer].[RegionName],[dbo].[vDimCustomer].[LegalEntityCode],[dbo].[vDimCustomer].[CountryCode],[dbo].[vDimCustomer].[CurrencyCode],[dbo].[vDimCustomer].[TermsOfPaymentCode],[dbo].[vDimCustomer].[MethodOfPaymentCode],[dbo].[vDimCustomer].[CustomerStatGroupCode],[dbo].[vDimCustomer].[CustomerStatGroupDescription],[dbo].[vDimCustomer].[Payer],[dbo].[vDimCustomer].[PayerName],[dbo].[vDimCustomer].[BillToAddress],[dbo].[vDimCustomer].[CreditLimit],[dbo].[vDimCustomer].[CreditParent],[dbo].[vDimCustomer].[ShalePlayCode],[dbo].[vDimCustomer].[SICCode],[dbo].[vDimCustomer].[CreatedDate],[dbo].[vDimCustomer].[LastUpdated],[dbo].[vDimCustomer].[DIM_ShalePlay_SKEY],[dbo].[vDimCustomer].[CustomerLoyalty],[dbo].[vDimCustomer].[DIM_DataForest_SKEY],[dbo].[vDimCustomer].[DIM_CustomerHierarchy_SKEY] FROM [dbo].[vDimCustomer] where DIM_DataForest_SKEY like '20%'"
          },
          {
            "name": "QueryEditorSerialization",
            "value": "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT [dbo].[vDimCustomer].[DIM_Customer_SKEY],[dbo].[vDimCustomer].[CustomerNumber],[dbo].[vDimCustomer].[CustomerName],[dbo].[vDimCustomer].[CustomerShortName],[dbo].[vDimCustomer].[FiscalCode],[dbo].[vDimCustomer].[CustomerGroupCode],[dbo].[vDimCustomer].[CustomerGroupDescription],[dbo].[vDimCustomer].[SegmentDescription],[dbo].[vDimCustomer].[CategoryCode],[dbo].[vDimCustomer].[SalesRepresentativeCode],[dbo].[vDimCustomer].[SalesRepresentativeName],[dbo].[vDimCustomer].[CountryDescription],[dbo].[vDimCustomer].[StateCode],[dbo].[vDimCustomer].[ZipCode],[dbo].[vDimCustomer].[City],[dbo].[vDimCustomer].[RegionName],[dbo].[vDimCustomer].[LegalEntityCode],[dbo].[vDimCustomer].[CountryCode],[dbo].[vDimCustomer].[CurrencyCode],[dbo].[vDimCustomer].[TermsOfPaymentCode],[dbo].[vDimCustomer].[MethodOfPaymentCode],[dbo].[vDimCustomer].[CustomerStatGroupCode],[dbo].[vDimCustomer].[CustomerStatGroupDescription],[dbo].[vDimCustomer].[Payer],[dbo].[vDimCustomer].[PayerName],[dbo].[vDimCustomer].[BillToAddress],[dbo].[vDimCustomer].[CreditLimit],[dbo].[vDimCustomer].[CreditParent],[dbo].[vDimCustomer].[ShalePlayCode],[dbo].[vDimCustomer].[SICCode],[dbo].[vDimCustomer].[CreatedDate],[dbo].[vDimCustomer].[LastUpdated],[dbo].[vDimCustomer].[DIM_ShalePlay_SKEY],[dbo].[vDimCustomer].[CustomerLoyalty],[dbo].[vDimCustomer].[DIM_DataForest_SKEY],[dbo].[vDimCustomer].[DIM_CustomerHierarchy_SKEY] FROM [dbo].[vDimCustomer] where DIM_DataForest_SKEY like '20%'</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
          }
        ]
      },
      {
        "name": "Date",
        "dataCategory": "Time",
        "columns": [
          {
            "name": "DIM_Date_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_Date_SKEY"
          },
          {
            "name": "Year",
            "dataType": "int64",
            "sourceColumn": "Year"
          },
          {
            "name": "Year Month",
            "dataType": "int64",
            "sourceColumn": "YearMonth"
          },
          {
            "name": "Month",
            "dataType": "int64",
            "sourceColumn": "Month"
          },
          {
            "name": "Month Short Name",
            "dataType": "string",
            "sourceColumn": "MonthShortName",
            "sortByColumn": "Month"
          },
          {
            "name": "Month Name",
            "dataType": "string",
            "sourceColumn": "MonthName",
            "sortByColumn": "Month"
          },
          {
            "name": "Year Month Day",
            "dataType": "int64",
            "sourceColumn": "YearMonthDay"
          },
          {
            "name": "Day Month Year",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DayMonthYear"
          },
          {
            "name": "Date",
            "dataType": "dateTime",
            "isKey": true,
            "sourceColumn": "Date"
          },
          {
            "name": "MonthDays",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "MonthDays"
          }
        ],
        "partitions": [
          {
            "name": "vwDimDate",
            "source": {
              "query": "SELECT [iso].[vDimDate].[DIM_Date_SKEY],[iso].[vDimDate].[Date],[iso].[vDimDate].[Year],[iso].[vDimDate].[YearMonth],[iso].[vDimDate].[Month],[iso].[vDimDate].[MonthShortName],[iso].[vDimDate].[MonthName],[iso].[vDimDate].[YearMonthDay],[iso].[vDimDate].[DayMonthYear],[iso].[vDimDate].[MonthDays] FROM [iso].[vDimDate]",
              "dataSource": "sibgrpudmsqlsrvd0001"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "&lt;?xml version=\"1.0\" encoding=\"UTF-16\"?&gt;&lt;Gemini xmlns=\"TableWidgetSerialization\"&gt;&lt;AnnotationContent&gt;&lt;![CDATA[&lt;?xml version=\"1.0\"?&gt;",
                  "&lt;TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\"&gt;",
                  "  &lt;ColumnSuggestedType /&gt;",
                  "  &lt;ColumnFormat /&gt;",
                  "  &lt;ColumnAccuracy /&gt;",
                  "  &lt;ColumnCurrencySymbol /&gt;",
                  "  &lt;ColumnPositivePattern /&gt;",
                  "  &lt;ColumnNegativePattern /&gt;",
                  "  &lt;ColumnWidths&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;DIM_Date_SKEY&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;108&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Date&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;113&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Year&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;52&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;YearQuarter&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;90&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Quarter&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;68&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;QuarterShortName&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;121&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;QuarterName&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;95&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;YearMonth&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;82&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Month&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;60&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;MonthShortName&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;113&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;MonthName&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;87&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;YearMonthDay&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;101&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;DayInMonth&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;89&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;DayInYear&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;81&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;DayInWeek&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;86&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;DayInWeekName&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;113&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;DayMonthYear&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;101&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;DayMonthYearName&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;128&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;YearWeek&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;79&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Week&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;57&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;WeekName&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;84&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;IsoDateKey&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;105&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;MonthShortNameYear&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;170&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;MonthNameYear&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;136&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;MonthDays&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;105&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "  &lt;/ColumnWidths&gt;",
                  "  &lt;ColumnDisplayIndex&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;DIM_Date_SKEY&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;0&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Date&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;1&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Year&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;2&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;YearQuarter&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;3&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Quarter&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;4&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;QuarterShortName&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;5&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;QuarterName&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;6&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;YearMonth&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;7&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Month&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;8&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;MonthShortName&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;9&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;MonthName&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;10&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;YearMonthDay&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;11&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;DayInMonth&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;12&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;DayInYear&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;13&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;DayInWeek&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;14&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;DayInWeekName&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;15&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;DayMonthYear&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;16&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;DayMonthYearName&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;17&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;YearWeek&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;18&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Week&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;19&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;WeekName&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;20&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;IsoDateKey&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;21&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;MonthShortNameYear&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;22&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;MonthNameYear&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;23&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;MonthDays&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;24&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "  &lt;/ColumnDisplayIndex&gt;",
                  "  &lt;ColumnFrozen /&gt;",
                  "  &lt;ColumnChecked&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;WeekName&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;false&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Week&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;false&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;YearWeek&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;false&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;DayMonthYearName&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;false&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;DayInWeekName&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;false&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;DayInWeek&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;false&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;DayInYear&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;false&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;DayInMonth&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;false&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;QuarterName&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;false&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;QuarterShortName&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;false&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Quarter&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;false&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;YearQuarter&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;false&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;Date&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;true&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;IsoDateKey&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;false&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;MonthShortNameYear&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;false&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;MonthNameYear&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;false&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;MonthDays&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;true&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "  &lt;/ColumnChecked&gt;",
                  "  &lt;ColumnFilter /&gt;",
                  "  &lt;SelectionFilter /&gt;",
                  "  &lt;FilterParameters /&gt;",
                  "  &lt;IsSortDescending&gt;false&lt;/IsSortDescending&gt;",
                  "&lt;/TableWidgetGridSerialization&gt;]]&gt;&lt;/AnnotationContent&gt;&lt;/Gemini&gt;"
                ]
              }
            ]
          }
        ],
        "hierarchies": [
          {
            "name": "By Year - Month",
            "levels": [
              {
                "name": "Year",
                "ordinal": 0,
                "column": "Year"
              },
              {
                "name": "Month",
                "ordinal": 1,
                "column": "Month Short Name"
              },
              {
                "name": "Date",
                "ordinal": 2,
                "column": "Date"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "iso"
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "vDimDate"
          },
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [iso].[vDimDate].[DIM_Date_SKEY],[iso].[vDimDate].[Date],[iso].[vDimDate].[Year],[iso].[vDimDate].[YearMonth],[iso].[vDimDate].[Month],[iso].[vDimDate].[MonthShortName],[iso].[vDimDate].[MonthName],[iso].[vDimDate].[YearMonthDay],[iso].[vDimDate].[DayMonthYear],[iso].[vDimDate].[MonthDays] FROM [iso].[vDimDate] "
          }
        ]
      },
      {
        "name": "Legal Entity",
        "columns": [
          {
            "name": "DIM_LegalEntity_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_LegalEntity_SKEY"
          },
          {
            "name": "Legal Entity Code",
            "dataType": "string",
            "sourceColumn": "LegalEntityCode"
          },
          {
            "name": "Legal Entity Name",
            "dataType": "string",
            "sourceColumn": "LegalEntityName"
          },
          {
            "name": "Fiscal Code",
            "dataType": "string",
            "sourceColumn": "FiscalCode"
          },
          {
            "name": "Country Code",
            "dataType": "string",
            "sourceColumn": "CountryCode"
          },
          {
            "name": "State Code",
            "dataType": "string",
            "sourceColumn": "StateCode"
          },
          {
            "name": "Zip Code",
            "dataType": "string",
            "sourceColumn": "ZipCode"
          },
          {
            "name": "City",
            "dataType": "string",
            "sourceColumn": "City"
          },
          {
            "name": "Accounting Currency Code",
            "dataType": "string",
            "sourceColumn": "AccountingCurrencyCode"
          },
          {
            "name": "Regional Currency Code",
            "dataType": "string",
            "sourceColumn": "RegionalCurrencyCode"
          },
          {
            "name": "Country Description",
            "dataType": "string",
            "sourceColumn": "CountryDescription"
          },
          {
            "name": "Address",
            "dataType": "string",
            "sourceColumn": "Address"
          },
          {
            "name": "Address 2",
            "dataType": "string",
            "sourceColumn": "Address2"
          },
          {
            "name": "Last Updated",
            "dataType": "dateTime",
            "sourceColumn": "LastUpdated"
          },
          {
            "name": "DIM_DataForest_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_DataForest_SKEY"
          }
        ],
        "partitions": [
          {
            "name": "vwDimLegalEntity",
            "source": {
              "query": "SELECT [dbo].[vDimLegalEntity].[DIM_LegalEntity_SKEY],[dbo].[vDimLegalEntity].[LegalEntityCode],[dbo].[vDimLegalEntity].[LegalEntityName],[dbo].[vDimLegalEntity].[FiscalCode],[dbo].[vDimLegalEntity].[AccountingCurrencyCode],[dbo].[vDimLegalEntity].[RegionalCurrencyCode],[dbo].[vDimLegalEntity].[CountryCode],[dbo].[vDimLegalEntity].[CountryDescription],[dbo].[vDimLegalEntity].[StateCode],[dbo].[vDimLegalEntity].[ZipCode],[dbo].[vDimLegalEntity].[City],[dbo].[vDimLegalEntity].[Address],[dbo].[vDimLegalEntity].[Address2],[dbo].[vDimLegalEntity].[LastUpdated],[dbo].[vDimLegalEntity].[DIM_DataForest_SKEY] FROM [dbo].[vDimLegalEntity] where DIM_DataForest_SKEY like '20%'",
              "dataSource": "sibgrpudmsqlsrvd0001"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT [dbo].[vDimLegalEntity].[DIM_LegalEntity_SKEY],[dbo].[vDimLegalEntity].[LegalEntityCode],[dbo].[vDimLegalEntity].[LegalEntityName],[dbo].[vDimLegalEntity].[FiscalCode],[dbo].[vDimLegalEntity].[AccountingCurrencyCode],[dbo].[vDimLegalEntity].[RegionalCurrencyCode],[dbo].[vDimLegalEntity].[CountryCode],[dbo].[vDimLegalEntity].[CountryDescription],[dbo].[vDimLegalEntity].[StateCode],[dbo].[vDimLegalEntity].[ZipCode],[dbo].[vDimLegalEntity].[City],[dbo].[vDimLegalEntity].[Address],[dbo].[vDimLegalEntity].[Address2],[dbo].[vDimLegalEntity].[LastUpdated],[dbo].[vDimLegalEntity].[DIM_DataForest_SKEY] FROM [dbo].[vDimLegalEntity] where DIM_DataForest_SKEY like '20%'</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "vDimLegalEntity"
          },
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": "SELECT [dbo].[vDimLegalEntity].[DIM_LegalEntity_SKEY],[dbo].[vDimLegalEntity].[LegalEntityCode],[dbo].[vDimLegalEntity].[LegalEntityName],[dbo].[vDimLegalEntity].[FiscalCode],[dbo].[vDimLegalEntity].[AccountingCurrencyCode],[dbo].[vDimLegalEntity].[RegionalCurrencyCode],[dbo].[vDimLegalEntity].[CountryCode],[dbo].[vDimLegalEntity].[CountryDescription],[dbo].[vDimLegalEntity].[StateCode],[dbo].[vDimLegalEntity].[ZipCode],[dbo].[vDimLegalEntity].[City],[dbo].[vDimLegalEntity].[Address],[dbo].[vDimLegalEntity].[Address2],[dbo].[vDimLegalEntity].[LastUpdated],[dbo].[vDimLegalEntity].[DIM_DataForest_SKEY] FROM [dbo].[vDimLegalEntity] where DIM_DataForest_SKEY like '20%'"
          },
          {
            "name": "QueryEditorSerialization",
            "value": "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT [dbo].[vDimLegalEntity].[DIM_LegalEntity_SKEY],[dbo].[vDimLegalEntity].[LegalEntityCode],[dbo].[vDimLegalEntity].[LegalEntityName],[dbo].[vDimLegalEntity].[FiscalCode],[dbo].[vDimLegalEntity].[AccountingCurrencyCode],[dbo].[vDimLegalEntity].[RegionalCurrencyCode],[dbo].[vDimLegalEntity].[CountryCode],[dbo].[vDimLegalEntity].[CountryDescription],[dbo].[vDimLegalEntity].[StateCode],[dbo].[vDimLegalEntity].[ZipCode],[dbo].[vDimLegalEntity].[City],[dbo].[vDimLegalEntity].[Address],[dbo].[vDimLegalEntity].[Address2],[dbo].[vDimLegalEntity].[LastUpdated],[dbo].[vDimLegalEntity].[DIM_DataForest_SKEY] FROM [dbo].[vDimLegalEntity] where DIM_DataForest_SKEY like '20%'</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
          }
        ]
      },
      {
        "name": "Plant",
        "columns": [
          {
            "name": "DIM_Plant_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_Plant_SKEY"
          },
          {
            "name": "Plant Code",
            "dataType": "string",
            "sourceColumn": "PlantCode"
          },
          {
            "name": "Plant Name",
            "dataType": "string",
            "sourceColumn": "PlantName"
          },
          {
            "name": "Plant Type",
            "dataType": "string",
            "sourceColumn": "PlantType"
          },
          {
            "name": "Fiscal Code",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "FiscalCode"
          },
          {
            "name": "Country Code",
            "dataType": "string",
            "sourceColumn": "CountryCode"
          },
          {
            "name": "State Code",
            "dataType": "string",
            "sourceColumn": "StateCode"
          },
          {
            "name": "Zip Code",
            "dataType": "string",
            "sourceColumn": "ZipCode"
          },
          {
            "name": "City",
            "dataType": "string",
            "sourceColumn": "City"
          },
          {
            "name": "Address",
            "dataType": "string",
            "sourceColumn": "Address"
          },
          {
            "name": "Legal Entity Code",
            "dataType": "string",
            "sourceColumn": "LegalEntityCode"
          },
          {
            "name": "ShalePlay Code",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "ShalePlayCode"
          },
          {
            "name": "Last Updated",
            "dataType": "dateTime",
            "sourceColumn": "LastUpdated"
          },
          {
            "name": "DIM_ShalePlay_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_ShalePlay_SKEY"
          },
          {
            "name": "DIM_DataForest_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_DataForest_SKEY"
          },
          {
            "name": "Latitude",
            "dataType": "string",
            "sourceColumn": "Latitude",
            "dataCategory": "Latitude"
          },
          {
            "name": "Longitude",
            "dataType": "string",
            "sourceColumn": "Longitude",
            "dataCategory": "Longitude"
          },
          {
            "name": "GIS",
            "dataType": "string",
            "sourceColumn": "GIS"
          }
        ],
        "partitions": [
          {
            "name": "vwDimPlant",
            "source": {
              "query": "SELECT [dbo].[vDimPlant].[DIM_Plant_SKEY],[dbo].[vDimPlant].[LegalEntityCode],[dbo].[vDimPlant].[PlantCode],[dbo].[vDimPlant].[PlantName],[dbo].[vDimPlant].[PlantType],[dbo].[vDimPlant].[FiscalCode],[dbo].[vDimPlant].[CountryCode],[dbo].[vDimPlant].[StateCode],[dbo].[vDimPlant].[ZipCode],[dbo].[vDimPlant].[City],[dbo].[vDimPlant].[Address],[dbo].[vDimPlant].[Latitude],[dbo].[vDimPlant].[Longitude],[dbo].[vDimPlant].[ShalePlayCode],[dbo].[vDimPlant].[DIM_ShalePlay_SKEY],[dbo].[vDimPlant].[LastUpdated],[dbo].[vDimPlant].[DIM_DataForest_SKEY],[dbo].[vDimPlant].[GIS] FROM [dbo].[vDimPlant] where DIM_DataForest_SKEY like '20%'",
              "dataSource": "sibgrpudmsqlsrvd0001"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT [dbo].[vDimPlant].[DIM_Plant_SKEY],[dbo].[vDimPlant].[LegalEntityCode],[dbo].[vDimPlant].[PlantCode],[dbo].[vDimPlant].[PlantName],[dbo].[vDimPlant].[PlantType],[dbo].[vDimPlant].[FiscalCode],[dbo].[vDimPlant].[CountryCode],[dbo].[vDimPlant].[StateCode],[dbo].[vDimPlant].[ZipCode],[dbo].[vDimPlant].[City],[dbo].[vDimPlant].[Address],[dbo].[vDimPlant].[Latitude],[dbo].[vDimPlant].[Longitude],[dbo].[vDimPlant].[ShalePlayCode],[dbo].[vDimPlant].[DIM_ShalePlay_SKEY],[dbo].[vDimPlant].[LastUpdated],[dbo].[vDimPlant].[DIM_DataForest_SKEY],[dbo].[vDimPlant].[GIS] FROM [dbo].[vDimPlant] where DIM_DataForest_SKEY like '20%'</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "vDimPlant"
          },
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": "SELECT [dbo].[vDimPlant].[DIM_Plant_SKEY],[dbo].[vDimPlant].[LegalEntityCode],[dbo].[vDimPlant].[PlantCode],[dbo].[vDimPlant].[PlantName],[dbo].[vDimPlant].[PlantType],[dbo].[vDimPlant].[FiscalCode],[dbo].[vDimPlant].[CountryCode],[dbo].[vDimPlant].[StateCode],[dbo].[vDimPlant].[ZipCode],[dbo].[vDimPlant].[City],[dbo].[vDimPlant].[Address],[dbo].[vDimPlant].[Latitude],[dbo].[vDimPlant].[Longitude],[dbo].[vDimPlant].[ShalePlayCode],[dbo].[vDimPlant].[DIM_ShalePlay_SKEY],[dbo].[vDimPlant].[LastUpdated],[dbo].[vDimPlant].[DIM_DataForest_SKEY],[dbo].[vDimPlant].[GIS] FROM [dbo].[vDimPlant] where DIM_DataForest_SKEY like '20%'"
          },
          {
            "name": "QueryEditorSerialization",
            "value": "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT [dbo].[vDimPlant].[DIM_Plant_SKEY],[dbo].[vDimPlant].[LegalEntityCode],[dbo].[vDimPlant].[PlantCode],[dbo].[vDimPlant].[PlantName],[dbo].[vDimPlant].[PlantType],[dbo].[vDimPlant].[FiscalCode],[dbo].[vDimPlant].[CountryCode],[dbo].[vDimPlant].[StateCode],[dbo].[vDimPlant].[ZipCode],[dbo].[vDimPlant].[City],[dbo].[vDimPlant].[Address],[dbo].[vDimPlant].[Latitude],[dbo].[vDimPlant].[Longitude],[dbo].[vDimPlant].[ShalePlayCode],[dbo].[vDimPlant].[DIM_ShalePlay_SKEY],[dbo].[vDimPlant].[LastUpdated],[dbo].[vDimPlant].[DIM_DataForest_SKEY],[dbo].[vDimPlant].[GIS] FROM [dbo].[vDimPlant] where DIM_DataForest_SKEY like '20%'</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
          }
        ]
      },
      {
        "name": "Product",
        "columns": [
          {
            "name": "DIM_Product_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_Product_SKEY"
          },
          {
            "name": "Product Id",
            "dataType": "string",
            "sourceColumn": "ProductId"
          },
          {
            "name": "Product Number",
            "dataType": "string",
            "sourceColumn": "ProductNumber"
          },
          {
            "name": "Product Description",
            "dataType": "string",
            "sourceColumn": "ProductDescription"
          },
          {
            "name": "Product Description English",
            "dataType": "string",
            "sourceColumn": "ProductDescriptionEnglish"
          },
          {
            "name": "Product Type",
            "dataType": "string",
            "sourceColumn": "ProductType"
          },
          {
            "name": "Store Warehouse Code",
            "dataType": "string",
            "sourceColumn": "StoreWarehouseCode"
          },
          {
            "name": "Store Warehouse Description",
            "dataType": "string",
            "sourceColumn": "StoreWarehouseDescription"
          },
          {
            "name": "Unit Id",
            "dataType": "string",
            "sourceColumn": "UnitId"
          },
          {
            "name": "Weight Factor",
            "dataType": "double",
            "sourceColumn": "WeightFactor"
          },
          {
            "name": "Material Family Code",
            "dataType": "string",
            "sourceColumn": "MaterialFamilyCode"
          },
          {
            "name": "Material Family Description",
            "dataType": "string",
            "sourceColumn": "MaterialFamilyDescription"
          },
          {
            "name": "Commercial Family Code",
            "dataType": "string",
            "sourceColumn": "CommercialFamilyCode"
          },
          {
            "name": "Commercial Family Description",
            "dataType": "string",
            "sourceColumn": "CommercialFamilyDescription"
          },
          {
            "name": "Cluster Group Code",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "ClusterGroupCode"
          },
          {
            "name": "Cluster Group Family Code",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "ClusterGroupFamilyCode"
          },
          {
            "name": "Cluster Group SubFamily Code",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "ClusterGroupSubFamilyCode"
          },
          {
            "name": "Status",
            "dataType": "string",
            "sourceColumn": "Status"
          },
          {
            "name": "Cluster Group Family Description",
            "dataType": "string",
            "sourceColumn": "ClusterGroupFamilyDescription"
          },
          {
            "name": "Cluster Group SubFamily Description",
            "dataType": "string",
            "sourceColumn": "ClusterGroupSubFamilyDescription"
          },
          {
            "name": "Product Inventory Type",
            "dataType": "string",
            "sourceColumn": "ProductInventoryType"
          },
          {
            "name": "Legal Entity Code",
            "dataType": "string",
            "sourceColumn": "LegalEntityCode"
          },
          {
            "name": "Product Name",
            "dataType": "string",
            "sourceColumn": "ProductName"
          },
          {
            "name": "Sales Group Code",
            "dataType": "string",
            "sourceColumn": "SalesGroupCode"
          },
          {
            "name": "Product Price Group Code",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "ProductPriceGroupCode"
          },
          {
            "name": "Plant Code",
            "dataType": "string",
            "sourceColumn": "PlantCode"
          },
          {
            "name": "Brand",
            "dataType": "string",
            "sourceColumn": "Brand"
          },
          {
            "name": "Mineral",
            "dataType": "string",
            "sourceColumn": "Mineral"
          },
          {
            "name": "Price Unit Id",
            "dataType": "string",
            "sourceColumn": "PriceUnitId"
          },
          {
            "name": "Inventory Unit Id",
            "dataType": "string",
            "sourceColumn": "InventoryUnitId"
          },
          {
            "name": "Sales Unit Id",
            "dataType": "string",
            "sourceColumn": "SalesUnitId"
          },
          {
            "name": "Customs Stat Number",
            "dataType": "string",
            "sourceColumn": "CustomsStatNumber"
          },
          {
            "name": "Catalog Type DB",
            "dataType": "string",
            "sourceColumn": "CatalogTypeDB"
          },
          {
            "name": "Sales Price Group Code",
            "dataType": "string",
            "sourceColumn": "SalesPriceGroupCode"
          },
          {
            "name": "Sales Price Group Description",
            "dataType": "string",
            "sourceColumn": "SalesPriceGroupDescription"
          },
          {
            "name": "SPC Code",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "SPCCode"
          },
          {
            "name": "Valid From Date",
            "dataType": "dateTime",
            "sourceColumn": "ValidFromDate"
          },
          {
            "name": "Valid To Date",
            "dataType": "dateTime",
            "sourceColumn": "ValidToDate"
          },
          {
            "name": "Last Updated",
            "dataType": "dateTime",
            "sourceColumn": "LastUpdated"
          },
          {
            "name": "DIM_DataForest_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_DataForest_SKEY"
          },
          {
            "name": "New Product Code",
            "dataType": "string",
            "sourceColumn": "NewProductCode"
          },
          {
            "name": "Product Short Description",
            "dataType": "string",
            "sourceColumn": "ProductShortDescription"
          },
          {
            "name": "Product Package Description",
            "dataType": "string",
            "sourceColumn": "ProductPackageDescription"
          }
        ],
        "partitions": [
          {
            "name": "vwDimProduct",
            "source": {
              "query": "SELECT [dbo].[vDimProduct].[DIM_Product_SKEY],[dbo].[vDimProduct].[ProductId],[dbo].[vDimProduct].[ProductNumber],[dbo].[vDimProduct].[ProductDescription],[dbo].[vDimProduct].[ProductDescriptionEnglish],[dbo].[vDimProduct].[ProductShortDescription],[dbo].[vDimProduct].[ProductPackageDescription],[dbo].[vDimProduct].[ProductType],[dbo].[vDimProduct].[ProductInventoryType],[dbo].[vDimProduct].[StoreWarehouseCode],[dbo].[vDimProduct].[StoreWarehouseDescription],[dbo].[vDimProduct].[UnitId],[dbo].[vDimProduct].[WeightFactor],[dbo].[vDimProduct].[MaterialFamilyCode],[dbo].[vDimProduct].[MaterialFamilyDescription],[dbo].[vDimProduct].[CommercialFamilyCode],[dbo].[vDimProduct].[CommercialFamilyDescription],[dbo].[vDimProduct].[ClusterGroupCode],[dbo].[vDimProduct].[ClusterGroupSubFamilyCode],[dbo].[vDimProduct].[ClusterGroupFamilyCode],[dbo].[vDimProduct].[ClusterGroupFamilyDescription],[dbo].[vDimProduct].[ClusterGroupSubFamilyDescription],[dbo].[vDimProduct].[LegalEntityCode],[dbo].[vDimProduct].[ProductName],[dbo].[vDimProduct].[SalesGroupCode],[dbo].[vDimProduct].[ProductPriceGroupCode],[dbo].[vDimProduct].[PlantCode],[dbo].[vDimProduct].[Brand],[dbo].[vDimProduct].[Mineral],[dbo].[vDimProduct].[PriceUnitId],[dbo].[vDimProduct].[InventoryUnitId],[dbo].[vDimProduct].[SalesUnitId],[dbo].[vDimProduct].[CustomsStatNumber],[dbo].[vDimProduct].[CatalogTypeDB],[dbo].[vDimProduct].[SalesPriceGroupCode],[dbo].[vDimProduct].[SalesPriceGroupDescription],[dbo].[vDimProduct].[Status],[dbo].[vDimProduct].[SPCCode],[dbo].[vDimProduct].[ValidFromDate],[dbo].[vDimProduct].[ValidToDate],[dbo].[vDimProduct].[LastUpdated],[dbo].[vDimProduct].[NewProductCode],[dbo].[vDimProduct].[DIM_DataForest_SKEY] FROM [dbo].[vDimProduct] where DIM_DataForest_SKEY like '20%'",
              "dataSource": "sibgrpudmsqlsrvd0001"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT [dbo].[vDimProduct].[DIM_Product_SKEY],[dbo].[vDimProduct].[ProductId],[dbo].[vDimProduct].[ProductNumber],[dbo].[vDimProduct].[ProductDescription],[dbo].[vDimProduct].[ProductDescriptionEnglish],[dbo].[vDimProduct].[ProductShortDescription],[dbo].[vDimProduct].[ProductPackageDescription],[dbo].[vDimProduct].[ProductType],[dbo].[vDimProduct].[ProductInventoryType],[dbo].[vDimProduct].[StoreWarehouseCode],[dbo].[vDimProduct].[StoreWarehouseDescription],[dbo].[vDimProduct].[UnitId],[dbo].[vDimProduct].[WeightFactor],[dbo].[vDimProduct].[MaterialFamilyCode],[dbo].[vDimProduct].[MaterialFamilyDescription],[dbo].[vDimProduct].[CommercialFamilyCode],[dbo].[vDimProduct].[CommercialFamilyDescription],[dbo].[vDimProduct].[ClusterGroupCode],[dbo].[vDimProduct].[ClusterGroupSubFamilyCode],[dbo].[vDimProduct].[ClusterGroupFamilyCode],[dbo].[vDimProduct].[ClusterGroupFamilyDescription],[dbo].[vDimProduct].[ClusterGroupSubFamilyDescription],[dbo].[vDimProduct].[LegalEntityCode],[dbo].[vDimProduct].[ProductName],[dbo].[vDimProduct].[SalesGroupCode],[dbo].[vDimProduct].[ProductPriceGroupCode],[dbo].[vDimProduct].[PlantCode],[dbo].[vDimProduct].[Brand],[dbo].[vDimProduct].[Mineral],[dbo].[vDimProduct].[PriceUnitId],[dbo].[vDimProduct].[InventoryUnitId],[dbo].[vDimProduct].[SalesUnitId],[dbo].[vDimProduct].[CustomsStatNumber],[dbo].[vDimProduct].[CatalogTypeDB],[dbo].[vDimProduct].[SalesPriceGroupCode],[dbo].[vDimProduct].[SalesPriceGroupDescription],[dbo].[vDimProduct].[Status],[dbo].[vDimProduct].[SPCCode],[dbo].[vDimProduct].[ValidFromDate],[dbo].[vDimProduct].[ValidToDate],[dbo].[vDimProduct].[LastUpdated],[dbo].[vDimProduct].[NewProductCode],[dbo].[vDimProduct].[DIM_DataForest_SKEY] FROM [dbo].[vDimProduct] where DIM_DataForest_SKEY like '20%'</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "vDimProduct"
          },
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": "SELECT [dbo].[vDimProduct].[DIM_Product_SKEY],[dbo].[vDimProduct].[ProductId],[dbo].[vDimProduct].[ProductNumber],[dbo].[vDimProduct].[ProductDescription],[dbo].[vDimProduct].[ProductDescriptionEnglish],[dbo].[vDimProduct].[ProductShortDescription],[dbo].[vDimProduct].[ProductPackageDescription],[dbo].[vDimProduct].[ProductType],[dbo].[vDimProduct].[ProductInventoryType],[dbo].[vDimProduct].[StoreWarehouseCode],[dbo].[vDimProduct].[StoreWarehouseDescription],[dbo].[vDimProduct].[UnitId],[dbo].[vDimProduct].[WeightFactor],[dbo].[vDimProduct].[MaterialFamilyCode],[dbo].[vDimProduct].[MaterialFamilyDescription],[dbo].[vDimProduct].[CommercialFamilyCode],[dbo].[vDimProduct].[CommercialFamilyDescription],[dbo].[vDimProduct].[ClusterGroupCode],[dbo].[vDimProduct].[ClusterGroupSubFamilyCode],[dbo].[vDimProduct].[ClusterGroupFamilyCode],[dbo].[vDimProduct].[ClusterGroupFamilyDescription],[dbo].[vDimProduct].[ClusterGroupSubFamilyDescription],[dbo].[vDimProduct].[LegalEntityCode],[dbo].[vDimProduct].[ProductName],[dbo].[vDimProduct].[SalesGroupCode],[dbo].[vDimProduct].[ProductPriceGroupCode],[dbo].[vDimProduct].[PlantCode],[dbo].[vDimProduct].[Brand],[dbo].[vDimProduct].[Mineral],[dbo].[vDimProduct].[PriceUnitId],[dbo].[vDimProduct].[InventoryUnitId],[dbo].[vDimProduct].[SalesUnitId],[dbo].[vDimProduct].[CustomsStatNumber],[dbo].[vDimProduct].[CatalogTypeDB],[dbo].[vDimProduct].[SalesPriceGroupCode],[dbo].[vDimProduct].[SalesPriceGroupDescription],[dbo].[vDimProduct].[Status],[dbo].[vDimProduct].[SPCCode],[dbo].[vDimProduct].[ValidFromDate],[dbo].[vDimProduct].[ValidToDate],[dbo].[vDimProduct].[LastUpdated],[dbo].[vDimProduct].[NewProductCode],[dbo].[vDimProduct].[DIM_DataForest_SKEY] FROM [dbo].[vDimProduct] where DIM_DataForest_SKEY like '20%'"
          },
          {
            "name": "QueryEditorSerialization",
            "value": "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT [dbo].[vDimProduct].[DIM_Product_SKEY],[dbo].[vDimProduct].[ProductId],[dbo].[vDimProduct].[ProductNumber],[dbo].[vDimProduct].[ProductDescription],[dbo].[vDimProduct].[ProductDescriptionEnglish],[dbo].[vDimProduct].[ProductShortDescription],[dbo].[vDimProduct].[ProductPackageDescription],[dbo].[vDimProduct].[ProductType],[dbo].[vDimProduct].[ProductInventoryType],[dbo].[vDimProduct].[StoreWarehouseCode],[dbo].[vDimProduct].[StoreWarehouseDescription],[dbo].[vDimProduct].[UnitId],[dbo].[vDimProduct].[WeightFactor],[dbo].[vDimProduct].[MaterialFamilyCode],[dbo].[vDimProduct].[MaterialFamilyDescription],[dbo].[vDimProduct].[CommercialFamilyCode],[dbo].[vDimProduct].[CommercialFamilyDescription],[dbo].[vDimProduct].[ClusterGroupCode],[dbo].[vDimProduct].[ClusterGroupSubFamilyCode],[dbo].[vDimProduct].[ClusterGroupFamilyCode],[dbo].[vDimProduct].[ClusterGroupFamilyDescription],[dbo].[vDimProduct].[ClusterGroupSubFamilyDescription],[dbo].[vDimProduct].[LegalEntityCode],[dbo].[vDimProduct].[ProductName],[dbo].[vDimProduct].[SalesGroupCode],[dbo].[vDimProduct].[ProductPriceGroupCode],[dbo].[vDimProduct].[PlantCode],[dbo].[vDimProduct].[Brand],[dbo].[vDimProduct].[Mineral],[dbo].[vDimProduct].[PriceUnitId],[dbo].[vDimProduct].[InventoryUnitId],[dbo].[vDimProduct].[SalesUnitId],[dbo].[vDimProduct].[CustomsStatNumber],[dbo].[vDimProduct].[CatalogTypeDB],[dbo].[vDimProduct].[SalesPriceGroupCode],[dbo].[vDimProduct].[SalesPriceGroupDescription],[dbo].[vDimProduct].[Status],[dbo].[vDimProduct].[SPCCode],[dbo].[vDimProduct].[ValidFromDate],[dbo].[vDimProduct].[ValidToDate],[dbo].[vDimProduct].[LastUpdated],[dbo].[vDimProduct].[NewProductCode],[dbo].[vDimProduct].[DIM_DataForest_SKEY] FROM [dbo].[vDimProduct] where DIM_DataForest_SKEY like '20%'</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
          }
        ]
      },
      {
        "name": "Sales Invoices",
        "columns": [
          {
            "name": "DIM_LegalEntity_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_LegalEntity_SKEY"
          },
          {
            "name": "DIM_Plant_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_Plant_SKEY"
          },
          {
            "name": "DIM_Date_Invoice_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_Date_Invoice_SKEY"
          },
          {
            "name": "DIM_Currency_Transaction_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_Currency_Transaction_SKEY"
          },
          {
            "name": "DIM_Currency_Accounting_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_Currency_Accounting_SKEY"
          },
          {
            "name": "DIM_Currency_Regional_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_Currency_Regional_SKEY"
          },
          {
            "name": "DIM_Customer_Invoice_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_Customer_Invoice_SKEY"
          },
          {
            "name": "DIM_TermsOfDelivery_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_TermsOfDelivery_SKEY"
          },
          {
            "name": "DIM_Unit_Sales_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_Unit_Sales_SKEY"
          },
          {
            "name": "DIM_Product_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_Product_SKEY"
          },
          {
            "name": "Serie",
            "dataType": "string",
            "sourceColumn": "InvoiceNumberSequence",
            "displayFolder": "Sales Invoice Meta"
          },
          {
            "name": "Invoice Number",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "InvoiceNumber",
            "displayFolder": "Sales Invoice Meta"
          },
          {
            "name": "InvoiceDate",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "InvoiceDate",
            "formatString": "General Date"
          },
          {
            "name": "Invoice Nature",
            "dataType": "string",
            "sourceColumn": "InvoiceNature",
            "displayFolder": "Sales Invoice Meta"
          },
          {
            "name": "Invoice Nature Description",
            "dataType": "string",
            "sourceColumn": "InvoiceNatureDescription",
            "displayFolder": "Sales Invoice Meta"
          },
          {
            "name": "Invoice Fiscal Code",
            "dataType": "string",
            "sourceColumn": "InvoiceFiscalCode",
            "displayFolder": "Sales Invoice Meta"
          },
          {
            "name": "Invoice Fiscal Description",
            "dataType": "string",
            "sourceColumn": "InvoiceFiscalDescription",
            "displayFolder": "Sales Invoice Meta"
          },
          {
            "name": "SalesPrice",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "SalesPrice"
          },
          {
            "name": "SalesPriceUnit",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "SalesPriceUnit"
          },
          {
            "name": "QtySalesUnit",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "QtySalesUnit"
          },
          {
            "name": "GrossWeight",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "GrossWeight"
          },
          {
            "name": "NetWeight",
            "dataType": "decimal",
            "isHidden": true,
            "sourceColumn": "NetWeight",
            "formatString": "\"\" #,0.00;#,0.00 -\"\";\"\" #,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"2067\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"2\" NegativePattern=\"12\" /></Format>"
              }
            ]
          },
          {
            "name": "FreightAmountCurrTrans",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "FreightAmountCurrTrans"
          },
          {
            "name": "FreightAmountCurrAcc",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "FreightAmountCurrAcc"
          },
          {
            "name": "FreightAmountCurrReg",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "FreightAmountCurrReg"
          },
          {
            "name": "VATTaxAmountCurrTrans",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "VATTaxAmountCurrTrans"
          },
          {
            "name": "VATTaxAmountCurrAcc",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "VATTaxAmountCurrAcc"
          },
          {
            "name": "VATTaxAmountCurrReg",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "VATTaxAmountCurrReg"
          },
          {
            "name": "FederalTaxAmountCurrTrans",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "FederalTaxAmountCurrTrans"
          },
          {
            "name": "FederalTaxAmountCurrAcc",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "FederalTaxAmountCurrAcc"
          },
          {
            "name": "FederalTaxAmountCurrReg",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "FederalTaxAmountCurrReg"
          },
          {
            "name": "StateTaxAmountCurrTrans",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "StateTaxAmountCurrTrans"
          },
          {
            "name": "StateTaxAmountCurrAcc",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "StateTaxAmountCurrAcc"
          },
          {
            "name": "StateTaxAmountCurrReg",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "StateTaxAmountCurrReg"
          },
          {
            "name": "CityTaxAmountCurrTrans",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "CityTaxAmountCurrTrans"
          },
          {
            "name": "CityTaxAmountCurrAcc",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "CityTaxAmountCurrAcc"
          },
          {
            "name": "CityTaxAmountCurrReg",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "CityTaxAmountCurrReg"
          },
          {
            "name": "TaxAmountCurrTrans",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "TaxAmountCurrTrans"
          },
          {
            "name": "TaxAmountCurrAcc",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "TaxAmountCurrAcc"
          },
          {
            "name": "TaxAmountCurrReg",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "TaxAmountCurrReg"
          },
          {
            "name": "InvoiceAmountCurrTrans",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "InvoiceAmountCurrTrans"
          },
          {
            "name": "InvoiceAmountCurrAcc",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "InvoiceAmountCurrAcc"
          },
          {
            "name": "InvoiceAmountCurrReg",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "InvoiceAmountCurrReg"
          },
          {
            "name": "InvoiceHasCreditNote",
            "dataType": "boolean",
            "isHidden": true,
            "sourceColumn": "InvoiceHasCreditNote"
          },
          {
            "name": "QtyTon",
            "dataType": "decimal",
            "isHidden": true,
            "sourceColumn": "QtyTon",
            "formatString": "\"\" #,0.00;#,0.00 -\"\";\"\" #,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"2067\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"2\" NegativePattern=\"12\" /></Format>"
              }
            ]
          },
          {
            "name": "NetSalesAmountCurrTrans",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "NetSalesAmountCurrTrans"
          },
          {
            "name": "NetSalesAmountCurrAcc",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "NetSalesAmountCurrAcc"
          },
          {
            "name": "NetSalesAmountCurrReg",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "NetSalesAmountCurrReg"
          },
          {
            "name": "RevenueAmountCurrTrans",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "RevenueAmountCurrTrans"
          },
          {
            "name": "RevenueAmountCurrAcc",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "RevenueAmountCurrAcc"
          },
          {
            "name": "RevenueAmountCurrReg",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "RevenueAmountCurrReg"
          },
          {
            "name": "DIM_GroupSIC_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_GroupSIC_SKEY"
          },
          {
            "name": "DIM_GroupSPC_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_GroupSPC_SKEY"
          },
          {
            "name": "CURR_DIM_GroupSIC_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CURR_DIM_GroupSIC_SKEY"
          },
          {
            "name": "CURR_DIM_GroupSPC_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CURR_DIM_GroupSPC_SKEY"
          },
          {
            "name": "Invoice Line Id",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "InvoiceLineId",
            "displayFolder": "Sales Invoice Meta"
          },
          {
            "name": "Freight Type",
            "dataType": "string",
            "sourceColumn": "FreightType",
            "displayFolder": "Sales Invoice Meta"
          },
          {
            "name": "Invoice Reference",
            "dataType": "string",
            "sourceColumn": "InvoiceReference",
            "displayFolder": "Sales Invoice Meta"
          },
          {
            "name": "Customer Reference",
            "dataType": "string",
            "sourceColumn": "CustomerReference",
            "displayFolder": "Sales Invoice Meta"
          },
          {
            "name": "Ship Via",
            "dataType": "string",
            "sourceColumn": "ShipVia",
            "displayFolder": "Sales Invoice Meta"
          },
          {
            "name": "Invoice Status",
            "dataType": "string",
            "sourceColumn": "InvoiceStatus",
            "displayFolder": "Sales Invoice Meta"
          },
          {
            "name": "Due Date",
            "dataType": "dateTime",
            "sourceColumn": "DueDate",
            "displayFolder": "Sales Invoice Meta"
          },
          {
            "name": "Terms Of Payment Code",
            "dataType": "string",
            "sourceColumn": "TermsOfPaymentCode",
            "displayFolder": "Sales Invoice Meta"
          },
          {
            "name": "Method Of Payment Code",
            "dataType": "string",
            "sourceColumn": "MethodOfPaymentCode",
            "displayFolder": "Sales Invoice Meta"
          },
          {
            "name": "Last Updated",
            "dataType": "dateTime",
            "sourceColumn": "LastUpdated",
            "displayFolder": "Sales Invoice Meta"
          },
          {
            "name": "DIM_DataForest_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_DataForest_SKEY"
          },
          {
            "name": "DIM_TgkLegalEntity_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_TgkLegalEntity_SKEY"
          },
          {
            "name": "Sales Unit",
            "dataType": "string",
            "sourceColumn": "SalesUnitId",
            "displayFolder": "Sales Invoice Meta"
          },
          {
            "name": "NonFreightAmountCurrTrans",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "NonFreightAmountCurrTrans"
          },
          {
            "name": "NonFreightAmountCurrAcc",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "NonFreightAmountCurrAcc"
          },
          {
            "name": "NonFreightAmountCurrReg",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "NonFreightAmountCurrReg"
          },
          {
            "name": "Charge Flag",
            "dataType": "string",
            "sourceColumn": "ChargeFlag",
            "displayFolder": "Sales Invoice Meta"
          },
          {
            "name": "Charge Group",
            "dataType": "string",
            "sourceColumn": "ChargeGroup",
            "displayFolder": "Sales Invoice Meta"
          },
          {
            "name": "DIM_SalesOrderLine_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_SalesOrderLine_SKEY"
          },
          {
            "name": "DIM_Customerdeliveryaddress_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_Customerdeliveryaddress_SKEY"
          },
          {
            "name": "NetInvoiceAmountCurrTrans",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "NetInvoiceAmountCurrTrans"
          },
          {
            "name": "NetInvoiceAmountCurrAcc",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "NetInvoiceAmountCurrAcc"
          },
          {
            "name": "NetInvoiceAmountCurrReg",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "NetInvoiceAmountCurrReg"
          },
          {
            "name": "Sales Order Line Id",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "SalesOrderLineId",
            "displayFolder": "Sales Invoice Meta"
          },
          {
            "name": "Exchange Rate Accounting Currency",
            "dataType": "double",
            "sourceColumn": "ExchangeRateCurrAcc",
            "formatString": "0.0000",
            "displayFolder": "Sales Invoice Meta"
          },
          {
            "name": "Exchange Rate Regional Currency",
            "dataType": "double",
            "sourceColumn": "ExchangeRateCurrReg",
            "formatString": "0.0000",
            "displayFolder": "Sales Invoice Meta"
          },
          {
            "name": "DIM_SalesInvoiceLine_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_SalesInvoiceLine_SKEY"
          },
          {
            "name": "NetWeightShortTons",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "NetWeightShortTons"
          },
          {
            "name": "FreightAmountCurrRegSys",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "FreightAmountCurrRegSys"
          },
          {
            "name": "InvoiceAmountCurrRegSys",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "InvoiceAmountCurrRegSys"
          },
          {
            "name": "NetInvoiceAmountCurrRegSys",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "NetInvoiceAmountCurrRegSys"
          },
          {
            "name": "StateTaxAmountCurrRegSys",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "StateTaxAmountCurrRegSys"
          },
          {
            "name": "TaxAmountCurrRegSys",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "TaxAmountCurrRegSys"
          },
          {
            "name": "VATTaxAmountCurrRegSys",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "VATTaxAmountCurrRegSys"
          }
        ],
        "partitions": [
          {
            "name": "vwFactSalesInvoices",
            "source": {
              "query": "SELECT [dbo].[vFactSalesInvoices].[DIM_DataForest_SKEY],[dbo].[vFactSalesInvoices].[DIM_SalesOrderLine_SKEY],[dbo].[vFactSalesInvoices].[DIM_SalesInvoiceLine_SKEY],[dbo].[vFactSalesInvoices].[DIM_LegalEntity_SKEY],[dbo].[vFactSalesInvoices].[DIM_TgkLegalEntity_SKEY],[dbo].[vFactSalesInvoices].[DIM_Plant_SKEY],[dbo].[vFactSalesInvoices].[DIM_Date_Invoice_SKEY],[dbo].[vFactSalesInvoices].[DIM_Currency_Transaction_SKEY],[dbo].[vFactSalesInvoices].[DIM_Currency_Accounting_SKEY],[dbo].[vFactSalesInvoices].[DIM_Currency_Regional_SKEY],[dbo].[vFactSalesInvoices].[DIM_Customer_Invoice_SKEY],[dbo].[vFactSalesInvoices].[DIM_TermsOfDelivery_SKEY],[dbo].[vFactSalesInvoices].[DIM_Unit_Sales_SKEY],[dbo].[vFactSalesInvoices].[DIM_Product_SKEY],[dbo].[vFactSalesInvoices].[DIM_GroupSIC_SKEY],[dbo].[vFactSalesInvoices].[CURR_DIM_GroupSIC_SKEY],[dbo].[vFactSalesInvoices].[DIM_GroupSPC_SKEY],[dbo].[vFactSalesInvoices].[CURR_DIM_GroupSPC_SKEY],[dbo].[vFactSalesInvoices].[InvoiceNumberSequence],[dbo].[vFactSalesInvoices].[InvoiceNumber],[dbo].[vFactSalesInvoices].[InvoiceDate],[dbo].[vFactSalesInvoices].[SalesUnitId],[dbo].[vFactSalesInvoices].[InvoiceHasCreditNote],[dbo].[vFactSalesInvoices].[InvoiceNature],[dbo].[vFactSalesInvoices].[InvoiceNatureDescription],[dbo].[vFactSalesInvoices].[InvoiceFiscalCode],[dbo].[vFactSalesInvoices].[InvoiceFiscalDescription],[dbo].[vFactSalesInvoices].[SalesPrice],[dbo].[vFactSalesInvoices].[SalesPriceUnit],[dbo].[vFactSalesInvoices].[QtySalesUnit],[dbo].[vFactSalesInvoices].[QtyTon],[dbo].[vFactSalesInvoices].[GrossWeight],[dbo].[vFactSalesInvoices].[NetWeight],[dbo].[vFactSalesInvoices].[NetWeightShortTons],[dbo].[vFactSalesInvoices].[InvoiceLineId],[dbo].[vFactSalesInvoices].[FreightType],[dbo].[vFactSalesInvoices].[InvoiceReference],[dbo].[vFactSalesInvoices].[CustomerReference],[dbo].[vFactSalesInvoices].[ShipVia],[dbo].[vFactSalesInvoices].[InvoiceStatus],[dbo].[vFactSalesInvoices].[DueDate],[dbo].[vFactSalesInvoices].[TermsOfPaymentCode],[dbo].[vFactSalesInvoices].[MethodOfPaymentCode],[dbo].[vFactSalesInvoices].[LastUpdated],[dbo].[vFactSalesInvoices].[ChargeFlag],[dbo].[vFactSalesInvoices].[ChargeGroup],[dbo].[vFactSalesInvoices].[DIM_Customerdeliveryaddress_SKEY],[dbo].[vFactSalesInvoices].[SalesOrderLineId],[dbo].[vFactSalesInvoices].[ExchangeRateCurrAcc],[dbo].[vFactSalesInvoices].[ExchangeRateCurrReg],[dbo].[vFactSalesInvoices].[NetInvoiceAmountCurrTrans],[dbo].[vFactSalesInvoices].[NetInvoiceAmountCurrAcc],[dbo].[vFactSalesInvoices].[NetInvoiceAmountCurrReg],[dbo].[vFactSalesInvoices].[RevenueAmountCurrTrans],[dbo].[vFactSalesInvoices].[RevenueAmountCurrAcc],[dbo].[vFactSalesInvoices].[RevenueAmountCurrReg],[dbo].[vFactSalesInvoices].[FreightAmountCurrTrans],[dbo].[vFactSalesInvoices].[FreightAmountCurrAcc],[dbo].[vFactSalesInvoices].[FreightAmountCurrReg],[dbo].[vFactSalesInvoices].[NonFreightAmountCurrTrans],[dbo].[vFactSalesInvoices].[NonFreightAmountCurrAcc],[dbo].[vFactSalesInvoices].[NonFreightAmountCurrReg],[dbo].[vFactSalesInvoices].[VATTaxAmountCurrTrans],[dbo].[vFactSalesInvoices].[VATTaxAmountCurrAcc],[dbo].[vFactSalesInvoices].[VATTaxAmountCurrReg],[dbo].[vFactSalesInvoices].[FederalTaxAmountCurrTrans],[dbo].[vFactSalesInvoices].[FederalTaxAmountCurrAcc],[dbo].[vFactSalesInvoices].[FederalTaxAmountCurrReg],[dbo].[vFactSalesInvoices].[StateTaxAmountCurrTrans],[dbo].[vFactSalesInvoices].[StateTaxAmountCurrAcc],[dbo].[vFactSalesInvoices].[StateTaxAmountCurrReg],[dbo].[vFactSalesInvoices].[CityTaxAmountCurrTrans],[dbo].[vFactSalesInvoices].[CityTaxAmountCurrAcc],[dbo].[vFactSalesInvoices].[CityTaxAmountCurrReg],[dbo].[vFactSalesInvoices].[TaxAmountCurrTrans],[dbo].[vFactSalesInvoices].[TaxAmountCurrAcc],[dbo].[vFactSalesInvoices].[TaxAmountCurrReg],[dbo].[vFactSalesInvoices].[InvoiceAmountCurrTrans],[dbo].[vFactSalesInvoices].[InvoiceAmountCurrAcc],[dbo].[vFactSalesInvoices].[InvoiceAmountCurrReg],[dbo].[vFactSalesInvoices].[NetSalesAmountCurrTrans],[dbo].[vFactSalesInvoices].[NetSalesAmountCurrAcc],[dbo].[vFactSalesInvoices].[NetSalesAmountCurrReg],[dbo].[vFactSalesInvoices].[FreightAmountCurrRegSys],[dbo].[vFactSalesInvoices].[InvoiceAmountCurrRegSys],[dbo].[vFactSalesInvoices].[NetInvoiceAmountCurrRegSys],[dbo].[vFactSalesInvoices].[StateTaxAmountCurrRegSys],[dbo].[vFactSalesInvoices].[TaxAmountCurrRegSys],[dbo].[vFactSalesInvoices].[VATTaxAmountCurrRegSys] FROM [dbo].[vFactSalesInvoices] where DIM_DataForest_SKEY like '20%'",
              "dataSource": "sibgrpudmsqlsrvd0001"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT [dbo].[vFactSalesInvoices].[DIM_DataForest_SKEY],[dbo].[vFactSalesInvoices].[DIM_SalesOrderLine_SKEY],[dbo].[vFactSalesInvoices].[DIM_SalesInvoiceLine_SKEY],[dbo].[vFactSalesInvoices].[DIM_LegalEntity_SKEY],[dbo].[vFactSalesInvoices].[DIM_TgkLegalEntity_SKEY],[dbo].[vFactSalesInvoices].[DIM_Plant_SKEY],[dbo].[vFactSalesInvoices].[DIM_Date_Invoice_SKEY],[dbo].[vFactSalesInvoices].[DIM_Currency_Transaction_SKEY],[dbo].[vFactSalesInvoices].[DIM_Currency_Accounting_SKEY],[dbo].[vFactSalesInvoices].[DIM_Currency_Regional_SKEY],[dbo].[vFactSalesInvoices].[DIM_Customer_Invoice_SKEY],[dbo].[vFactSalesInvoices].[DIM_TermsOfDelivery_SKEY],[dbo].[vFactSalesInvoices].[DIM_Unit_Sales_SKEY],[dbo].[vFactSalesInvoices].[DIM_Product_SKEY],[dbo].[vFactSalesInvoices].[DIM_GroupSIC_SKEY],[dbo].[vFactSalesInvoices].[CURR_DIM_GroupSIC_SKEY],[dbo].[vFactSalesInvoices].[DIM_GroupSPC_SKEY],[dbo].[vFactSalesInvoices].[CURR_DIM_GroupSPC_SKEY],[dbo].[vFactSalesInvoices].[InvoiceNumberSequence],[dbo].[vFactSalesInvoices].[InvoiceNumber],[dbo].[vFactSalesInvoices].[InvoiceDate],[dbo].[vFactSalesInvoices].[SalesUnitId],[dbo].[vFactSalesInvoices].[InvoiceHasCreditNote],[dbo].[vFactSalesInvoices].[InvoiceNature],[dbo].[vFactSalesInvoices].[InvoiceNatureDescription],[dbo].[vFactSalesInvoices].[InvoiceFiscalCode],[dbo].[vFactSalesInvoices].[InvoiceFiscalDescription],[dbo].[vFactSalesInvoices].[SalesPrice],[dbo].[vFactSalesInvoices].[SalesPriceUnit],[dbo].[vFactSalesInvoices].[QtySalesUnit],[dbo].[vFactSalesInvoices].[QtyTon],[dbo].[vFactSalesInvoices].[GrossWeight],[dbo].[vFactSalesInvoices].[NetWeight],[dbo].[vFactSalesInvoices].[NetWeightShortTons],[dbo].[vFactSalesInvoices].[InvoiceLineId],[dbo].[vFactSalesInvoices].[FreightType],[dbo].[vFactSalesInvoices].[InvoiceReference],[dbo].[vFactSalesInvoices].[CustomerReference],[dbo].[vFactSalesInvoices].[ShipVia],[dbo].[vFactSalesInvoices].[InvoiceStatus],[dbo].[vFactSalesInvoices].[DueDate],[dbo].[vFactSalesInvoices].[TermsOfPaymentCode],[dbo].[vFactSalesInvoices].[MethodOfPaymentCode],[dbo].[vFactSalesInvoices].[LastUpdated],[dbo].[vFactSalesInvoices].[ChargeFlag],[dbo].[vFactSalesInvoices].[ChargeGroup],[dbo].[vFactSalesInvoices].[DIM_Customerdeliveryaddress_SKEY],[dbo].[vFactSalesInvoices].[SalesOrderLineId],[dbo].[vFactSalesInvoices].[ExchangeRateCurrAcc],[dbo].[vFactSalesInvoices].[ExchangeRateCurrReg],[dbo].[vFactSalesInvoices].[NetInvoiceAmountCurrTrans],[dbo].[vFactSalesInvoices].[NetInvoiceAmountCurrAcc],[dbo].[vFactSalesInvoices].[NetInvoiceAmountCurrReg],[dbo].[vFactSalesInvoices].[RevenueAmountCurrTrans],[dbo].[vFactSalesInvoices].[RevenueAmountCurrAcc],[dbo].[vFactSalesInvoices].[RevenueAmountCurrReg],[dbo].[vFactSalesInvoices].[FreightAmountCurrTrans],[dbo].[vFactSalesInvoices].[FreightAmountCurrAcc],[dbo].[vFactSalesInvoices].[FreightAmountCurrReg],[dbo].[vFactSalesInvoices].[NonFreightAmountCurrTrans],[dbo].[vFactSalesInvoices].[NonFreightAmountCurrAcc],[dbo].[vFactSalesInvoices].[NonFreightAmountCurrReg],[dbo].[vFactSalesInvoices].[VATTaxAmountCurrTrans],[dbo].[vFactSalesInvoices].[VATTaxAmountCurrAcc],[dbo].[vFactSalesInvoices].[VATTaxAmountCurrReg],[dbo].[vFactSalesInvoices].[FederalTaxAmountCurrTrans],[dbo].[vFactSalesInvoices].[FederalTaxAmountCurrAcc],[dbo].[vFactSalesInvoices].[FederalTaxAmountCurrReg],[dbo].[vFactSalesInvoices].[StateTaxAmountCurrTrans],[dbo].[vFactSalesInvoices].[StateTaxAmountCurrAcc],[dbo].[vFactSalesInvoices].[StateTaxAmountCurrReg],[dbo].[vFactSalesInvoices].[CityTaxAmountCurrTrans],[dbo].[vFactSalesInvoices].[CityTaxAmountCurrAcc],[dbo].[vFactSalesInvoices].[CityTaxAmountCurrReg],[dbo].[vFactSalesInvoices].[TaxAmountCurrTrans],[dbo].[vFactSalesInvoices].[TaxAmountCurrAcc],[dbo].[vFactSalesInvoices].[TaxAmountCurrReg],[dbo].[vFactSalesInvoices].[InvoiceAmountCurrTrans],[dbo].[vFactSalesInvoices].[InvoiceAmountCurrAcc],[dbo].[vFactSalesInvoices].[InvoiceAmountCurrReg],[dbo].[vFactSalesInvoices].[NetSalesAmountCurrTrans],[dbo].[vFactSalesInvoices].[NetSalesAmountCurrAcc],[dbo].[vFactSalesInvoices].[NetSalesAmountCurrReg],[dbo].[vFactSalesInvoices].[FreightAmountCurrRegSys],[dbo].[vFactSalesInvoices].[InvoiceAmountCurrRegSys],[dbo].[vFactSalesInvoices].[NetInvoiceAmountCurrRegSys],[dbo].[vFactSalesInvoices].[StateTaxAmountCurrRegSys],[dbo].[vFactSalesInvoices].[TaxAmountCurrRegSys],[dbo].[vFactSalesInvoices].[VATTaxAmountCurrRegSys] FROM [dbo].[vFactSalesInvoices] where DIM_DataForest_SKEY like '20%'</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
              }
            ]
          }
        ],
        "measures": [
          {
            "name": "Qty Invoiced Sales Unit",
            "expression": "SUM([QtySalesUnit])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Invoice Qty"
          },
          {
            "name": "Gross Weight",
            "expression": "SUM([GrossWeight])",
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Sales Invoice Weight"
          },
          {
            "name": "Net Weight",
            "expression": "SUM([NetWeight])",
            "formatString": "\"\" #,0.00;#,0.00 -\"\";\"\" #,0.00",
            "displayFolder": "Sales Invoice Weight",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"2067\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"2\" NegativePattern=\"12\" /></Format>"
              }
            ]
          },
          {
            "name": "Freight Amount Curr Acc",
            "expression": "SUM([FreightAmountCurrAcc])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Invoice Amount Accounting Currency"
          },
          {
            "name": "Freight Amount Curr Reg",
            "expression": "SUM([FreightAmountCurrReg])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Invoice Amount Regional Currency"
          },
          {
            "name": "VAT Tax Amount Curr Acc",
            "expression": "SUM([VATTaxAmountCurrAcc])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Invoice Amount Accounting Currency"
          },
          {
            "name": "VAT Tax Amount Curr Reg",
            "expression": "SUM([VATTaxAmountCurrReg])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Invoice Amount Regional Currency"
          },
          {
            "name": "Federal Tax Amount Curr Acc",
            "expression": "SUM([FederalTaxAmountCurrAcc])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Invoice Amount Accounting Currency"
          },
          {
            "name": "Federal Tax Amount Curr Reg",
            "expression": "SUM([FederalTaxAmountCurrReg])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Invoice Amount Regional Currency"
          },
          {
            "name": "Invoice Amount Curr Acc",
            "expression": "SUM([InvoiceAmountCurrAcc])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Invoice Amount Accounting Currency"
          },
          {
            "name": "Invoice Amount Curr Reg",
            "expression": "SUM([InvoiceAmountCurrReg])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Invoice Amount Regional Currency"
          },
          {
            "name": "Tax Amount Curr Acc",
            "expression": "SUM([TaxAmountCurrAcc])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Invoice Amount Accounting Currency"
          },
          {
            "name": "Tax Amount Curr Reg",
            "expression": "SUM([TaxAmountCurrReg])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Invoice Amount Regional Currency"
          },
          {
            "name": "City Tax Amount Curr Acc",
            "expression": "SUM([CityTaxAmountCurrAcc])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Invoice Amount Accounting Currency"
          },
          {
            "name": "City Tax Amount Curr Reg",
            "expression": "SUM([CityTaxAmountCurrReg])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Invoice Amount Regional Currency"
          },
          {
            "name": "State Tax Amount Curr Acc",
            "expression": "SUM([StateTaxAmountCurrAcc])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Invoice Amount Accounting Currency"
          },
          {
            "name": "State Tax Amount Curr Reg",
            "expression": "SUM([StateTaxAmountCurrReg])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Invoice Amount Regional Currency"
          },
          {
            "name": "Qty Invoiced Ton",
            "expression": "SUM([QtyTon])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Invoice Qty"
          },
          {
            "name": "Net Sales Amount Curr Acc",
            "expression": "SUM([NetSalesAmountCurrAcc])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Invoice Amount Accounting Currency"
          },
          {
            "name": "Net Sales Amount Curr Reg",
            "expression": "SUM([NetSalesAmountCurrReg])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Invoice Amount Regional Currency"
          },
          {
            "name": "Net Sales Per Ton Curr Acc",
            "expression": "DIVIDE(SUM('Sales Invoices'[NetSalesAmountCurrAcc]),SUM('Sales Invoices'[QtyTon]))",
            "formatString": "#,0.00",
            "displayFolder": "Sales Invoice KPI"
          },
          {
            "name": "Net Sales Per Ton Curr Reg",
            "expression": "DIVIDE(SUM('Sales Invoices'[NetSalesAmountCurrReg]),SUM('Sales Invoices'[QtyTon]))",
            "formatString": "#,0.00",
            "displayFolder": "Sales Invoice KPI"
          },
          {
            "name": "Revenue Amount Curr Acc",
            "expression": "SUM([RevenueAmountCurrAcc])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Invoice Amount Accounting Currency"
          },
          {
            "name": "Revenue Amount Curr Reg",
            "expression": "SUM([RevenueAmountCurrReg])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Invoice Amount Regional Currency"
          },
          {
            "name": "Revenue Amount Curr Trans",
            "expression": "SUM([RevenueAmountCurrTrans])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Invoice Amount Transaction Currency"
          },
          {
            "name": "Net Sales Amount Curr Trans",
            "expression": "SUM([NetSalesAmountCurrTrans])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Invoice Amount Transaction Currency"
          },
          {
            "name": "Freight Amount Curr Trans",
            "expression": "SUM([FreightAmountCurrTrans])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Invoice Amount Transaction Currency"
          },
          {
            "name": "VAT Tax Amount Curr Trans",
            "expression": "SUM([VATTaxAmountCurrTrans])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Invoice Amount Transaction Currency"
          },
          {
            "name": "Federal Tax Amount Curr Trans",
            "expression": "SUM([FederalTaxAmountCurrTrans])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Invoice Amount Transaction Currency"
          },
          {
            "name": "State Tax Amount Curr Trans",
            "expression": "SUM([StateTaxAmountCurrTrans])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Invoice Amount Transaction Currency"
          },
          {
            "name": "City Tax Amount Curr Trans",
            "expression": "SUM([CityTaxAmountCurrTrans])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Invoice Amount Transaction Currency"
          },
          {
            "name": "Tax Amount Curr Trans",
            "expression": "SUM([TaxAmountCurrTrans])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Invoice Amount Transaction Currency"
          },
          {
            "name": "Invoice Amount Curr Trans",
            "expression": "SUM([InvoiceAmountCurrTrans])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Invoice Amount Transaction Currency"
          },
          {
            "name": "Qty Delta",
            "expression": "SUM([QtyTon]) - SUM('Sales Budgets'[QtySalesUnit])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Invoice Qty Actuals vs Budget"
          },
          {
            "name": "Qty Delta %",
            "expression": "DIVIDE([Qty Delta],SUM('Sales Budgets'[QtySalesUnit]))",
            "formatString": "0.0%;-0.0%;0.0%",
            "displayFolder": "Sales Invoice Qty Actuals vs Budget"
          },
          {
            "name": "Net Sales Amount Delta Curr Reg",
            "expression": "SUM([NetSalesAmountCurrReg]) - SUM('Sales Budgets'[NetSalesAmountCurrReg])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Invoice Amount Actuals vs Budget"
          },
          {
            "name": "Net Sales Amount Delta Curr Reg %",
            "expression": "DIVIDE([Net Sales Amount Delta Curr Reg],SUM('Sales Budgets'[NetSalesAmountCurrReg]))",
            "formatString": "0.0%;-0.0%;0.0%",
            "displayFolder": "Sales Invoice Amount Actuals vs Budget"
          },
          {
            "name": "Revenue Amount Delta Curr Reg",
            "expression": "SUM([RevenueAmountCurrReg]) - SUM('Sales Budgets'[RevenueAmountCurrReg])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Invoice Amount Actuals vs Budget"
          },
          {
            "name": "Revenue Amount Delta Curr Reg %",
            "expression": "DIVIDE([Revenue Amount Delta Curr Reg],SUM('Sales Budgets'[RevenueAmountCurrReg]))",
            "formatString": "0.0%;-0.0%;0.0%",
            "displayFolder": "Sales Invoice Amount Actuals vs Budget"
          },
          {
            "name": "Net Sales Amount Delta Curr Acc",
            "expression": "SUM([NetSalesAmountCurrAcc]) - SUM('Sales Budgets'[NetSalesAmountCurrAcc])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Invoice Amount Actuals vs Budget"
          },
          {
            "name": "Net Sales Amount Delta Curr Acc %",
            "expression": "DIVIDE([Net Sales Amount Delta Curr Acc],SUM('Sales Budgets'[NetSalesAmountCurrAcc]))",
            "formatString": "0.0%;-0.0%;0.0%",
            "displayFolder": "Sales Invoice Amount Actuals vs Budget"
          },
          {
            "name": "Revenue Amount Delta Curr Acc",
            "expression": "SUM([RevenueAmountCurrAcc]) - SUM('Sales Budgets'[RevenueAmountCurrAcc])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Invoice Amount Actuals vs Budget"
          },
          {
            "name": "Revenue Amount Delta Curr Acc %",
            "expression": "DIVIDE([Revenue Amount Delta Curr Acc],SUM('Sales Budgets'[RevenueAmountCurrAcc]))",
            "formatString": "0.0%;-0.0%;0.0%",
            "displayFolder": "Sales Invoice Amount Actuals vs Budget"
          },
          {
            "name": "Revenue Per Ton Curr Acc",
            "expression": "DIVIDE(SUM('Sales Invoices'[RevenueAmountCurrAcc]),SUM('Sales Invoices'[QtyTon]))",
            "formatString": "\"\" #,0.00;#,0.00 -\"\";\"\" #,0.00",
            "displayFolder": "Sales Invoice KPI",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"2067\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"2\" NegativePattern=\"12\" /></Format>"
              }
            ]
          },
          {
            "name": "Revenue Per Ton Curr Reg",
            "expression": "DIVIDE(SUM('Sales Invoices'[RevenueAmountCurrReg]),SUM('Sales Invoices'[QtyTon]))",
            "formatString": "\"\" #,0.00;#,0.00 -\"\";\"\" #,0.00",
            "displayFolder": "Sales Invoice KPI",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"2067\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"2\" NegativePattern=\"12\" /></Format>"
              }
            ]
          },
          {
            "name": "PY Qty Invoiced Ton",
            "expression": "CALCULATE([Qty Invoiced Ton],SAMEPERIODLASTYEAR('Date'[Date]))",
            "formatString": "#,0.00",
            "isHidden": true
          },
          {
            "name": "PY Revenue Amount Curr Acc",
            "expression": "CALCULATE([Revenue Amount Curr Acc],SAMEPERIODLASTYEAR('Date'[Date]))",
            "formatString": "#,0.00",
            "isHidden": true
          },
          {
            "name": "PY Revenue Amount Curr Reg",
            "expression": "CALCULATE([Revenue Amount Curr Reg],SAMEPERIODLASTYEAR('Date'[Date]))",
            "formatString": "#,0.00",
            "isHidden": true
          },
          {
            "name": "Growth Volume Ton",
            "expression": "[Qty Invoiced Ton]-[PY Qty Invoiced Ton]",
            "formatString": "#,0.00",
            "displayFolder": "Sales Invoice Trends"
          },
          {
            "name": "Growth Revenue Amount Curr Acc",
            "expression": "[Revenue Amount Curr Acc]-[PY Revenue Amount Curr Acc]",
            "formatString": "#,0.00",
            "displayFolder": "Sales Invoice Trends"
          },
          {
            "name": "Growth Revenue Amount Curr Reg",
            "expression": "[Revenue Amount Curr Reg]-[PY Revenue Amount Curr Reg]",
            "formatString": "#,0.00",
            "displayFolder": "Sales Invoice Trends"
          },
          {
            "name": "Percent Growth Volume Ton",
            "expression": "DIVIDE([Growth Volume Ton],[PY Qty Invoiced Ton])",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Sales Invoice Trends"
          },
          {
            "name": "Percent Growth Revenue Amount Curr Acc",
            "expression": "DIVIDE([Growth Revenue Amount Curr Acc],[PY Revenue Amount Curr Acc])",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Sales Invoice Trends"
          },
          {
            "name": "Percent Growth Revenue Amount Curr Reg",
            "expression": "DIVIDE([Growth Revenue Amount Curr Reg],[PY Revenue Amount Curr Reg])",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Sales Invoice Trends"
          },
          {
            "name": "Customer Revenue Type",
            "expression": "calculate(IF(ISFILTERED ('Date'[Year]), if(and([PY Rolling 12M Revenue Amount Curr Acc]<=0,[Rolling 12M Revenue Amount Curr Acc]>0),\"New Business\",\tif(and([PY Rolling 12M Revenue Amount Curr Acc]>0,[Rolling 12M Revenue Amount Curr Acc]<=0),\"Lost Business\",\tif([Rolling 12M Revenue Amount Curr Acc]>[PY Rolling 12M Revenue Amount Curr Acc],\"Recurring Business - Revenue Increase\",\tif([Rolling 12M Revenue Amount Curr Acc]<[PY Rolling 12M Revenue Amount Curr Acc],\"Recurring Business - Revenue Decrease\"\t))))))",
            "displayFolder": "Sales Invoice KPI"
          },
          {
            "name": "PY Revenue Per Ton Curr Reg",
            "expression": "CALCULATE([Revenue Per Ton Curr Reg],SAMEPERIODLASTYEAR('Date'[Date]))",
            "isHidden": true
          },
          {
            "name": "Customer Revenue Growth Variance",
            "expression": "calculate(IF(ISFILTERED ('Date'[Year]), if(and([Rolling 12M Revenue Per Ton Curr Acc]<[PY Rolling 12M Revenue Per Ton Curr Acc],[Rolling 12M Qty Invoiced Ton]<[PY Rolling 12M Qty Invoiced Ton]),\"Lower Volume - Lower Price\",if(and([Rolling 12M Revenue Per Ton Curr Acc]>[PY Rolling 12M Revenue Per Ton Curr Acc],[Rolling 12M Qty Invoiced Ton]<[PY Rolling 12M Qty Invoiced Ton]),\"Lower Volume - Higher Price\",if(and([Rolling 12M Revenue Per Ton Curr Acc]<[PY Rolling 12M Revenue Per Ton Curr Acc],[Rolling 12M Qty Invoiced Ton]>[PY Rolling 12M Qty Invoiced Ton]),\"Higher Volume - Lower Price\",if(and([Rolling 12M Revenue Per Ton Curr Acc]>[PY Rolling 12M Revenue Per Ton Curr Acc],[Rolling 12M Qty Invoiced Ton]>[PY Rolling 12M Qty Invoiced Ton]),\"Higher Volume - Higher Price\"))))))",
            "displayFolder": "Sales Invoice KPI"
          },
          {
            "name": "Rolling 12M Revenue Amount Curr Acc",
            "expression": "CALCULATE (  'Sales Invoices'[Revenue Amount Curr Acc] ,    DATESBETWEEN (        'Date'[Date],        NEXTDAY ( SAMEPERIODLASTYEAR (LASTDATE ( 'Date'[Date] ) ) ),        LASTDATE ( 'Date'[Date] )    ))",
            "isHidden": true
          },
          {
            "name": "PY Rolling 12M Revenue Amount Curr Acc",
            "expression": "CALCULATE (  'Sales Invoices'[PY Revenue Amount Curr Acc] ,    DATESBETWEEN (        'Date'[Date],        NEXTDAY ( SAMEPERIODLASTYEAR (LASTDATE ( 'Date'[Date] ) ) ),        LASTDATE ( 'Date'[Date] )    ))",
            "isHidden": true
          },
          {
            "name": "PY Rolling 12M Qty Invoiced Ton",
            "expression": "CALCULATE (  [PY Qty Invoiced Ton],    DATESBETWEEN (        'Date'[Date],        NEXTDAY ( SAMEPERIODLASTYEAR (LASTDATE ( 'Date'[Date] ) ) ),        LASTDATE ( 'Date'[Date] )    ))",
            "formatString": "0.00",
            "isHidden": true
          },
          {
            "name": "Rolling 12M Qty Invoiced Ton",
            "expression": "CALCULATE ( [Qty Invoiced Ton] ,    DATESBETWEEN (        'Date'[Date],        NEXTDAY ( SAMEPERIODLASTYEAR (LASTDATE ( 'Date'[Date] ) ) ),        LASTDATE ( 'Date'[Date] )    ))",
            "formatString": "0.00",
            "isHidden": true
          },
          {
            "name": "Rolling 12M Revenue Per Ton Curr Acc",
            "expression": "DIVIDE(calculate('Sales Invoices'[Rolling 12M Revenue Amount Curr Acc]),calculate([Rolling 12M Qty Invoiced Ton]))",
            "formatString": "0.00",
            "isHidden": true
          },
          {
            "name": "PY Rolling 12M Revenue Per Ton Curr Acc",
            "expression": "DIVIDE(calculate('Sales Invoices'[PY Rolling 12M Revenue Amount Curr Acc]),calculate([PY Rolling 12M Qty Invoiced Ton]))",
            "formatString": "0.00",
            "isHidden": true
          },
          {
            "name": "Rolling 12M Revenue Amount Curr Trans",
            "expression": "CALCULATE (  'Sales Invoices'[Revenue Amount Curr Trans] ,    DATESBETWEEN (        'Date'[Date],        NEXTDAY ( SAMEPERIODLASTYEAR (LASTDATE ( 'Date'[Date] ) ) ),        LASTDATE ( 'Date'[Date] )    ))",
            "isHidden": true
          },
          {
            "name": "Rolling 12M Revenue Amount Curr Reg",
            "expression": "CALCULATE (  'Sales Invoices'[Revenue Amount Curr Reg] ,    DATESBETWEEN (        'Date'[Date],        NEXTDAY ( SAMEPERIODLASTYEAR (LASTDATE ( 'Date'[Date] ) ) ),        LASTDATE ( 'Date'[Date] )    ))",
            "isHidden": true
          },
          {
            "name": "Transportation Cost per Ton Curr Acc",
            "expression": "DIVIDE([Freight Amount Curr Acc],[Qty Invoiced Ton])",
            "formatString": "0.00",
            "displayFolder": "Sales Invoice KPI"
          },
          {
            "name": "NPI Curr Acc",
            "expression": "DIVIDE(calculate(sum('Sales Invoices'[RevenueAmountCurrAcc]),'Product'[New Product Code]=\"Yes\"),sum('Sales Invoices'[RevenueAmountCurrAcc]))",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Sales Invoice KPI"
          },
          {
            "name": "OutstandingInvoices",
            "expression": "calculate([Revenue Amount Curr Acc],'Sales Invoices'[Invoice Status]<>\"PaidPosted\" && 'Sales Invoices'[Invoice Status]<>\"Paid\")",
            "isHidden": true
          },
          {
            "name": "DSO Curr Acc",
            "expression": "DIVIDE([OutstandingInvoices],[Revenue Amount Curr Acc])*[DaysInPeriod]",
            "formatString": "0.00",
            "displayFolder": "Sales Invoice KPI"
          },
          {
            "name": "DaysInPeriod",
            "expression": "COUNTX(FILTER('Date','Date'[Date]<=TODAY()),'Date'[Date])",
            "formatString": "0",
            "isHidden": true
          },
          {
            "name": "OutstandingInvoicesCurrTrans",
            "expression": "calculate([Revenue Amount Curr Trans],'Sales Invoices'[Invoice Status]<>\"PaidPosted\" && 'Sales Invoices'[Invoice Status]<>\"Paid\")",
            "isHidden": true
          },
          {
            "name": "OutstandingInvoicesCurrReg",
            "expression": "calculate([Revenue Amount Curr Reg],'Sales Invoices'[Invoice Status]<>\"PaidPosted\" && 'Sales Invoices'[Invoice Status]<>\"Paid\")",
            "isHidden": true
          },
          {
            "name": "DSO Curr Trans",
            "expression": "DIVIDE([OutstandingInvoicesCurrTrans],[Revenue Amount Curr Trans])*[DaysInPeriod]",
            "isHidden": true
          },
          {
            "name": "DSO Curr Reg",
            "expression": "DIVIDE([OutstandingInvoicesCurrReg],[Revenue Amount Curr Reg])*[DaysInPeriod]",
            "formatString": "0.00",
            "displayFolder": "Sales Invoice KPI"
          },
          {
            "name": "Transportation Cost per Ton Curr Trans",
            "expression": "DIVIDE([Freight Amount Curr Trans],[Qty Invoiced Ton])",
            "isHidden": true
          },
          {
            "name": "Transportation Cost per Ton Curr Reg",
            "expression": "DIVIDE([Freight Amount Curr Reg],[Qty Invoiced Ton])",
            "formatString": "0.00",
            "displayFolder": "Sales Invoice KPI"
          },
          {
            "name": "Revenue Per Ton Curr Trans",
            "expression": "DIVIDE(SUM('Sales Invoices'[RevenueAmountCurrTrans]),SUM('Sales Invoices'[QtyTon]))",
            "isHidden": true
          },
          {
            "name": "NPI Curr Reg",
            "expression": "DIVIDE(calculate(sum('Sales Invoices'[RevenueAmountCurrReg]),'Product'[New Product Code]=\"Yes\"),sum('Sales Invoices'[RevenueAmountCurrReg]))",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Sales Invoice KPI"
          },
          {
            "name": "Non Freight Amount Curr Reg",
            "expression": "SUM([NonFreightAmountCurrReg])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Invoice Amount Regional Currency"
          },
          {
            "name": "Non Freight Amount Curr Acc",
            "expression": "SUM([NonFreightAmountCurrAcc])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Invoice Amount Accounting Currency"
          },
          {
            "name": "Non Freight Amount Curr Trans",
            "expression": "SUM([NonFreightAmountCurrTrans])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Invoice Amount Transaction Currency"
          },
          {
            "name": "Net Invoice Amount Curr Trans",
            "expression": "SUM([NetInvoiceAmountCurrTrans])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Invoice Amount Transaction Currency"
          },
          {
            "name": "Net Invoice Amount Curr Acc",
            "expression": "SUM([NetInvoiceAmountCurrAcc])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Invoice Amount Accounting Currency"
          },
          {
            "name": "Net Invoice Amount Curr Reg",
            "expression": "SUM([NetInvoiceAmountCurrReg])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Invoice Amount Regional Currency"
          },
          {
            "name": "Short Tons",
            "expression": "SUM([NetWeightShortTons])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Invoice Weight"
          },
          {
            "name": "Previous Month - Qty Invoiced Sales Unit",
            "expression": "CALCULATE([Qty Invoiced Sales Unit],PREVIOUSMONTH('Date'[Date]))",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Previous Month"
          },
          {
            "name": "Previous Month - Net Weight",
            "expression": "CALCULATE([Net Weight],PREVIOUSMONTH('Date'[Date]))",
            "formatString": "\"\" #,0.00;#,0.00 -\"\";\"\" #,0.00",
            "displayFolder": "Time Intelligence - Previous Month",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"2067\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"2\" NegativePattern=\"12\" /></Format>"
              }
            ]
          },
          {
            "name": "Previous Month - Qty Invoiced Ton",
            "expression": "CALCULATE([Qty Invoiced Ton],PREVIOUSMONTH('Date'[Date]))",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Previous Month"
          },
          {
            "name": "Previous Month - Net Sales Amount Curr Acc",
            "expression": "CALCULATE([Net Sales Amount Curr Acc],PREVIOUSMONTH('Date'[Date]))",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Previous Month"
          },
          {
            "name": "Previous Month - Net Sales Amount Curr Reg",
            "expression": "CALCULATE([Net Sales Amount Curr Reg],PREVIOUSMONTH('Date'[Date]))",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Previous Month"
          },
          {
            "name": "Previous Month - Net Sales Per Ton Curr Acc",
            "expression": "CALCULATE([Net Sales Amount Curr Acc],PREVIOUSMONTH('Date'[Date]))",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Previous Month"
          },
          {
            "name": "Previous Month - Net Sales Per Ton Curr Reg",
            "expression": "CALCULATE([Net Sales Per Ton Curr Reg],PREVIOUSMONTH('Date'[Date]))",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Previous Month"
          },
          {
            "name": "Previous Month - Revenue Amount Curr Acc",
            "expression": "CALCULATE([Revenue Amount Curr Acc],PREVIOUSMONTH('Date'[Date]))",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Previous Month"
          },
          {
            "name": "Previous Month - Revenue Amount Curr Reg",
            "expression": "CALCULATE([Revenue Amount Curr Reg],PREVIOUSMONTH('Date'[Date]))",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Previous Month"
          },
          {
            "name": "Previous Month - Revenue Amount Curr Trans",
            "expression": "CALCULATE([Revenue Amount Curr Trans],PREVIOUSMONTH('Date'[Date]))",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Previous Month"
          },
          {
            "name": "Previous Month - Net Sales Amount Curr Trans",
            "expression": "CALCULATE([Net Sales Amount Curr Trans],PREVIOUSMONTH('Date'[Date]))",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Previous Month"
          },
          {
            "name": "Previous Month - Revenue Per Ton Curr Reg",
            "expression": "CALCULATE([Revenue Per Ton Curr Reg],PREVIOUSMONTH('Date'[Date]))",
            "formatString": "\"\" #,0.00;#,0.00 -\"\";\"\" #,0.00",
            "isHidden": true,
            "displayFolder": "Time Intelligence - Previous Month",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"2067\" DisplayName=\"\" Symbol=\"\" PositivePattern=\"2\" NegativePattern=\"12\" /></Format>"
              }
            ]
          },
          {
            "name": "Previous Month - Short Tons",
            "expression": "CALCULATE([Short Tons],PREVIOUSMONTH('Date'[Date]))",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Previous Month"
          },
          {
            "name": "Qty Invoiced Sales Unit - Growth Month",
            "expression": "[Qty Invoiced Sales Unit]-[Previous Month - Qty Invoiced Sales Unit]",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Previous Month"
          },
          {
            "name": "Net Weight - Growth Month",
            "expression": "[Net Weight]-[Previous Month - Net Weight]",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Previous Month"
          },
          {
            "name": "Qty Invoiced Ton - Growth Month",
            "expression": "[Qty Invoiced Ton]-[Previous Month - Qty Invoiced Ton]",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Previous Month"
          },
          {
            "name": "Net Sales Amount Curr Acc - Growth Month",
            "expression": "[Net Sales Amount Curr Acc]-[Previous Month - Net Sales Amount Curr Acc]",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Previous Month"
          },
          {
            "name": "Net Sales Amount Curr Reg - Growth Month",
            "expression": "[Net Sales Amount Curr Reg]-[Previous Month - Net Sales Amount Curr Reg]",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Previous Month"
          },
          {
            "name": "Net Sales Amount Curr Trans - Growth Month",
            "expression": "[Net Sales Amount Curr Trans]-[Previous Month - Net Sales Amount Curr Trans]",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Previous Month"
          },
          {
            "name": "Revenue Amount Curr Trans - Growth Month",
            "expression": "[Revenue Amount Curr Trans]-[Previous Month - Revenue Amount Curr Trans]",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Previous Month"
          },
          {
            "name": "Revenue Amount Curr Acc - Growth Month",
            "expression": "[Revenue Amount Curr Acc]-[Previous Month - Revenue Amount Curr Acc]",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Previous Month"
          },
          {
            "name": "Revenue Amount Curr Reg - Growth Month",
            "expression": "[Revenue Amount Curr Reg]-[Previous Month - Revenue Amount Curr Reg]",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Previous Month"
          },
          {
            "name": "Short Tons - Growth Month",
            "expression": "[Short Tons]-[Previous Month - Short Tons]",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Previous Month"
          },
          {
            "name": "Qty Invoiced Sales Unit - Growth Month %",
            "expression": "IF(ISBLANK([Previous Month - Qty Invoiced Sales Unit])=TRUE,BLANK(),DIVIDE([Qty Invoiced Sales Unit],[Previous Month - Qty Invoiced Sales Unit])-1)",
            "formatString": "0.0%;-0.0%;0.0%",
            "displayFolder": "Time Intelligence - Previous Month"
          },
          {
            "name": "Net Weight - Growth Month %",
            "expression": "IF(ISBLANK([Previous Month - Net Weight])=TRUE,BLANK(),DIVIDE([Net Weight],[Previous Month - Net Weight])-1)",
            "formatString": "0.0%;-0.0%;0.0%",
            "displayFolder": "Time Intelligence - Previous Month"
          },
          {
            "name": "Qty Invoiced Ton - Growth Month %",
            "expression": "IF(ISBLANK([Previous Month - Qty Invoiced Ton])=TRUE,BLANK(),DIVIDE([Qty Invoiced Ton],[Previous Month - Qty Invoiced Ton])-1)",
            "formatString": "0.0%;-0.0%;0.0%",
            "displayFolder": "Time Intelligence - Previous Month"
          },
          {
            "name": "Net Sales Amount Curr Acc - Growth Month %",
            "expression": "IF(ISBLANK([Previous Month - Net Sales Amount Curr Acc])=TRUE,BLANK(),DIVIDE([Net Sales Amount Curr Acc],[Previous Month - Net Sales Amount Curr Acc])-1)",
            "formatString": "0.0%;-0.0%;0.0%",
            "displayFolder": "Time Intelligence - Previous Month"
          },
          {
            "name": "Net Sales Amount Curr Reg - Growth Month %",
            "expression": "IF(ISBLANK([Previous Month - Net Sales Amount Curr Reg])=TRUE,BLANK(),DIVIDE([Net Sales Amount Curr Reg],[Previous Month - Net Sales Amount Curr Reg])-1)",
            "formatString": "0.0%;-0.0%;0.0%",
            "displayFolder": "Time Intelligence - Previous Month"
          },
          {
            "name": "Revenue Amount Curr Acc - Growth Month %",
            "expression": "IF(ISBLANK([Previous Month - Revenue Amount Curr Acc])=TRUE,BLANK(),DIVIDE([Revenue Amount Curr Acc],[Previous Month - Revenue Amount Curr Acc])-1)",
            "formatString": "0.0%;-0.0%;0.0%",
            "displayFolder": "Time Intelligence - Previous Month"
          },
          {
            "name": "Revenue Amount Curr Reg - Growth Month %",
            "expression": "IF(ISBLANK([Previous Month - Revenue Amount Curr Reg])=TRUE,BLANK(),DIVIDE([Revenue Amount Curr Reg],[Previous Month - Revenue Amount Curr Reg])-1)",
            "formatString": "0.0%;-0.0%;0.0%",
            "displayFolder": "Time Intelligence - Previous Month"
          },
          {
            "name": "Revenue Amount Curr Trans - Growth Month %",
            "expression": "IF(ISBLANK([Previous Month - Revenue Amount Curr Trans])=TRUE,BLANK(),DIVIDE([Revenue Amount Curr Trans],[Previous Month - Revenue Amount Curr Trans]))",
            "formatString": "0.0%;-0.0%;0.0%",
            "displayFolder": "Time Intelligence - Previous Month"
          },
          {
            "name": "Net Sales Amount Curr Trans - Growth Month %",
            "expression": "IF(ISBLANK([Previous Month - Net Sales Amount Curr Trans])=TRUE,BLANK(),DIVIDE([Net Sales Amount Curr Trans],[Previous Month - Net Sales Amount Curr Trans])-1)",
            "formatString": "0.0%;-0.0%;0.0%",
            "displayFolder": "Time Intelligence - Previous Month"
          },
          {
            "name": "Short Tons - Growth Month %",
            "expression": "IF(ISBLANK([Previous Month - Short Tons])=TRUE,BLANK(),DIVIDE([Short Tons],[Previous Month - Short Tons])-1)",
            "formatString": "0.0%;-0.0%;0.0%",
            "displayFolder": "Time Intelligence - Previous Month"
          },
          {
            "name": "Short Tons Ex Alabama",
            "expression": "SUMX(FILTER('Sales Invoices','Sales Invoices'[Charge Group]<>\"ALABAMA SEVERANCE TAX\"),[NetWeightShortTons])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Invoice Regional Measures"
          },
          {
            "name": "Metric Tons Ex Alabama",
            "expression": "SUMX(FILTER('Sales Invoices','Sales Invoices'[Charge Group]<>\"ALABAMA SEVERANCE TAX\"),[NetWeight])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Invoice Regional Measures"
          },
          {
            "name": "Revenue Per Ton Ex Alabama Curr Reg",
            "expression": "DIVIDE(SUM('Sales Invoices'[RevenueAmountCurrReg]),[Short Tons Ex Alabama])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Invoice Regional Measures"
          },
          {
            "name": "Revenue Per Ton Ex Alabama Curr Acc",
            "expression": "DIVIDE(SUM('Sales Invoices'[RevenueAmountCurrAcc]),[Short Tons Ex Alabama])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Invoice Regional Measures"
          },
          {
            "name": "Revenue Per Ton Ex Alabama Curr Trans",
            "expression": "DIVIDE(SUM('Sales Invoices'[RevenueAmountCurrTrans]),[Short Tons Ex Alabama])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Invoice Regional Measures"
          },
          {
            "name": "Previous Month - Short Tons Ex Alabama",
            "expression": "CALCULATE([Short Tons Ex Alabama],PREVIOUSMONTH('Date'[Date]))",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Previous Month"
          },
          {
            "name": "Short Tons Ex Alabama - Growth Month",
            "expression": "[Short Tons Ex Alabama]-[Previous Month - Short Tons Ex Alabama]",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Previous Month"
          },
          {
            "name": "Short Tons Ex Alabama - Growth Month %",
            "expression": "IF(ISBLANK([Previous Month - Short Tons Ex Alabama])=TRUE,BLANK(),DIVIDE([Short Tons Ex Alabama],[Previous Month - Short Tons Ex Alabama])-1)",
            "formatString": "0.0%;-0.0%;0.0%",
            "displayFolder": "Time Intelligence - Previous Month"
          },
          {
            "name": "Year To Date - Qty Invoiced Sales Unit",
            "expression": "TOTALYTD([Qty Invoiced Sales Unit],'Date'[Date])  ",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Year To Date - Net Weight",
            "expression": "TOTALYTD([Net Weight],'Date'[Date])  ",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Year To Date - Qty Invoiced Ton",
            "expression": "TOTALYTD([Qty Invoiced Ton],'Date'[Date])  ",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Year To Date - Net Sales Amount Curr Acc",
            "expression": "TOTALYTD([Net Sales Amount Curr Acc],'Date'[Date])  ",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Year To Date - Net Sales Amount Curr Reg",
            "expression": "TOTALYTD([Net Sales Amount Curr Reg],'Date'[Date])  ",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Year To Date - Revenue Amount Curr Acc",
            "expression": "TOTALYTD([Revenue Amount Curr Acc],'Date'[Date])  ",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Year To Date - Revenue Amount Curr Reg",
            "expression": "TOTALYTD([Revenue Amount Curr Reg],'Date'[Date])  ",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Year To Date - Revenue Amount Curr Trans",
            "expression": "TOTALYTD([Revenue Amount Curr Trans],'Date'[Date])  ",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Year To Date - Net Sales Amount Curr Trans",
            "expression": "TOTALYTD([Net Sales Amount Curr Trans],'Date'[Date])  ",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Year To Date - Net Sales Per Ton Curr Reg",
            "expression": "TOTALYTD([Net Sales Per Ton Curr Reg],'Date'[Date])  ",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Year To Date - Net Sales Per Ton Curr Acc",
            "expression": "TOTALYTD([Net Sales Per Ton Curr Acc],'Date'[Date])  ",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Year To Date - Revenue Per Ton Ex Alabama Curr Acc",
            "expression": "TOTALYTD([Revenue Per Ton Ex Alabama Curr Acc],'Date'[Date])  ",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Year To Date - Revenue Per Ton Ex Alabama Curr Trans",
            "expression": "TOTALYTD([Revenue Per Ton Ex Alabama Curr Trans],'Date'[Date])  ",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Year To Date - Revenue Per Ton Ex Alabama Curr Reg",
            "expression": "TOTALYTD([Revenue Per Ton Ex Alabama Curr Reg],'Date'[Date])  ",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Year To Date - Short Tons Ex Alabama",
            "expression": "TOTALYTD([Short Tons Ex Alabama],'Date'[Date])  ",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Year To Date - Metric Tons Ex Alabama",
            "expression": "TOTALYTD([Metric Tons Ex Alabama],'Date'[Date])  ",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Year To Date Last Year - Qty Invoiced Sales Unit",
            "expression": "CALCULATE([Year To Date - Qty Invoiced Sales Unit],SAMEPERIODLASTYEAR('Date'[Date]))",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Year To Date Last Year - Net Weight",
            "expression": "CALCULATE([Year To Date - Net Weight],SAMEPERIODLASTYEAR('Date'[Date]))",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Year To Date Last Year - Qty Invoiced Ton",
            "expression": "CALCULATE([Year To Date - Qty Invoiced Ton],SAMEPERIODLASTYEAR('Date'[Date]))",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Year To Date Last Year - Net Sales Amount Curr Acc",
            "expression": "CALCULATE([Year To Date - Net Sales Amount Curr Acc],SAMEPERIODLASTYEAR('Date'[Date]))",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Year To Date Last Year - Net Sales Amount Curr Reg",
            "expression": "CALCULATE([Year To Date - Net Sales Amount Curr Reg],SAMEPERIODLASTYEAR('Date'[Date]))",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Year To Date Last Year - Net Sales Amount Curr Trans",
            "expression": "CALCULATE([Year To Date - Net Sales Amount Curr Trans],SAMEPERIODLASTYEAR('Date'[Date]))",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Year To Date Last Year - Revenue Amount Curr Acc",
            "expression": "CALCULATE([Year To Date - Revenue Amount Curr Acc],SAMEPERIODLASTYEAR('Date'[Date]))",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Year To Date Last Year - Revenue Amount Curr Reg",
            "expression": "CALCULATE([Year To Date - Revenue Amount Curr Reg],SAMEPERIODLASTYEAR('Date'[Date]))",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Year To Date Last Year - Revenue Amount Curr Trans",
            "expression": "CALCULATE([Year To Date - Revenue Amount Curr Trans],SAMEPERIODLASTYEAR('Date'[Date]))",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Year To Date Last Year - Net Sales Per Ton Curr Acc",
            "expression": "CALCULATE([Year To Date - Net Sales Per Ton Curr Acc],SAMEPERIODLASTYEAR('Date'[Date]))",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Year To Date Last Year - Net Sales Per Ton Curr Reg",
            "expression": "CALCULATE([Year To Date - Net Sales Per Ton Curr Reg],SAMEPERIODLASTYEAR('Date'[Date]))",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Year To Date Last Year - Revenue Per Ton Ex Alabama Curr Acc",
            "expression": "CALCULATE([Year To Date - Revenue Per Ton Ex Alabama Curr Acc],SAMEPERIODLASTYEAR('Date'[Date]))",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Year To Date Last Year - Revenue Per Ton Ex Alabama Curr Trans",
            "expression": "CALCULATE([Year To Date - Revenue Per Ton Ex Alabama Curr Trans],SAMEPERIODLASTYEAR('Date'[Date]))",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Year To Date Last Year - Revenue Per Ton Ex Alabama Curr Reg",
            "expression": "CALCULATE([Year To Date - Revenue Per Ton Ex Alabama Curr Reg],SAMEPERIODLASTYEAR('Date'[Date]))",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Year To Date Last Year - Short Tons Ex Alabama",
            "expression": "CALCULATE([Year To Date - Short Tons Ex Alabama],SAMEPERIODLASTYEAR('Date'[Date]))",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Year To Date Last Year - Metric Tons Ex Alabama",
            "expression": "CALCULATE([Year To Date - Metric Tons Ex Alabama],SAMEPERIODLASTYEAR('Date'[Date]))",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Qty Invoiced Sales Unit - Growth YTD",
            "expression": "[Year To Date - Qty Invoiced Sales Unit]-[Year To Date Last Year - Qty Invoiced Sales Unit]",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Net Weight - Growth YTD",
            "expression": "[Year To Date - Net Weight]-[Year To Date Last Year - Net Weight]",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Qty Invoiced Ton - Growth YTD",
            "expression": "[Year To Date - Qty Invoiced Ton]-[Year To Date Last Year - Qty Invoiced Ton]",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Net Sales Amount Curr Acc - Growth YTD",
            "expression": "[Year To Date - Net Sales Amount Curr Acc]-[Year To Date Last Year - Net Sales Amount Curr Acc]",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Net Sales Amount Curr Reg - Growth YTD",
            "expression": "[Year To Date - Net Sales Amount Curr Reg]-[Year To Date Last Year - Net Sales Amount Curr Reg]",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Net Sales Amount Curr Trans - Growth YTD",
            "expression": "[Year To Date - Net Sales Amount Curr Trans]-[Year To Date Last Year - Net Sales Amount Curr Trans]",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Revenue Amount Curr Acc - Growth YTD",
            "expression": "[Year To Date - Revenue Amount Curr Acc]-[Year To Date Last Year - Revenue Amount Curr Acc]",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Revenue Amount Curr Reg - Growth YTD",
            "expression": "[Year To Date - Revenue Amount Curr Reg]-[Year To Date Last Year - Revenue Amount Curr Reg]",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Revenue Amount Curr Trans - Growth YTD",
            "expression": "[Year To Date - Revenue Amount Curr Trans]-[Year To Date Last Year - Revenue Amount Curr Trans]",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Net Sales Per Ton Curr Acc - Growth YTD",
            "expression": "[Year To Date - Net Sales Per Ton Curr Acc]-[Year To Date Last Year - Net Sales Per Ton Curr Acc]",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Net Sales Per Ton Curr Reg - Growth YTD",
            "expression": "[Year To Date - Net Sales Per Ton Curr Reg]-[Year To Date Last Year - Net Sales Per Ton Curr Reg]",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Revenue Per Ton Ex Alabama Curr Acc - Growth YTD",
            "expression": "[Year To Date - Revenue Per Ton Ex Alabama Curr Acc]-[Year To Date Last Year - Revenue Per Ton Ex Alabama Curr Acc]",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Revenue Per Ton Ex Alabama Curr Trans - Growth YTD",
            "expression": "[Year To Date - Revenue Per Ton Ex Alabama Curr Trans]-[Year To Date Last Year - Revenue Per Ton Ex Alabama Curr Trans]",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Revenue Per Ton Ex Alabama Curr Reg - Growth YTD",
            "expression": "[Year To Date - Revenue Per Ton Ex Alabama Curr Reg]-[Year To Date Last Year - Revenue Per Ton Ex Alabama Curr Reg]",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Short Tons Ex Alabama - Growth YTD",
            "expression": "[Year To Date - Short Tons Ex Alabama]-[Year To Date Last Year - Short Tons Ex Alabama]",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Metric Tons Ex Alabama - Growth YTD",
            "expression": "[Year To Date - Metric Tons Ex Alabama]-[Year To Date Last Year - Metric Tons Ex Alabama]",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Qty Invoiced Sales Unit - Growth YTD %",
            "expression": "IF(ISBLANK([Year To Date Last Year - Qty Invoiced Sales Unit])=TRUE,BLANK(),DIVIDE([Year To Date - Qty Invoiced Sales Unit],[Year To Date Last Year - Qty Invoiced Sales Unit])-1)",
            "formatString": "0.0%;-0.0%;0.0%",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Net Weight - Growth YTD %",
            "expression": "IF(ISBLANK([Year To Date Last Year - Net Weight])=TRUE,BLANK(),DIVIDE([Year To Date - Net Weight],[Year To Date Last Year - Net Weight])-1)",
            "formatString": "0.0%;-0.0%;0.0%",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Qty Invoiced Ton - Growth YTD %",
            "expression": "IF(ISBLANK([Year To Date Last Year - Qty Invoiced Ton])=TRUE,BLANK(),DIVIDE([Year To Date - Qty Invoiced Ton],[Year To Date Last Year - Qty Invoiced Ton])-1)",
            "formatString": "0.0%;-0.0%;0.0%",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Net Sales Amount Curr Acc - Growth YTD %",
            "expression": "IF(ISBLANK([Year To Date Last Year - Net Sales Amount Curr Acc])=TRUE,BLANK(),DIVIDE([Year To Date - Net Sales Amount Curr Acc],[Year To Date Last Year - Net Sales Amount Curr Acc])-1)",
            "formatString": "0.0%;-0.0%;0.0%",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Net Sales Amount Curr Reg - Growth YTD %",
            "expression": "IF(ISBLANK([Year To Date Last Year - Net Sales Amount Curr Reg])=TRUE,BLANK(),DIVIDE([Year To Date - Net Sales Amount Curr Reg],[Year To Date Last Year - Net Sales Amount Curr Reg])-1)",
            "formatString": "0.0%;-0.0%;0.0%",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Net Sales Per Ton Curr Acc - Growth YTD %",
            "expression": "IF(ISBLANK([Year To Date Last Year - Net Sales Per Ton Curr Acc])=TRUE,BLANK(),DIVIDE([Year To Date - Net Sales Per Ton Curr Acc],[Year To Date Last Year - Net Sales Per Ton Curr Acc])-1)",
            "formatString": "0.0%;-0.0%;0.0%",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Net Sales Per Ton Curr Reg - Growth YTD %",
            "expression": "IF(ISBLANK([Year To Date Last Year - Net Sales Per Ton Curr Reg])=TRUE,BLANK(),DIVIDE([Year To Date - Net Sales Per Ton Curr Reg],[Year To Date Last Year - Net Sales Per Ton Curr Reg])-1)",
            "formatString": "0.0%;-0.0%;0.0%",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Revenue Amount Curr Acc - Growth YTD %",
            "expression": "IF(ISBLANK([Year To Date Last Year - Revenue Amount Curr Acc])=TRUE,BLANK(),DIVIDE([Year To Date - Revenue Amount Curr Acc],[Year To Date Last Year - Revenue Amount Curr Acc])-1)",
            "formatString": "0.0%;-0.0%;0.0%",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Revenue Amount Curr Reg - Growth YTD %",
            "expression": "IF(ISBLANK([Year To Date Last Year - Revenue Amount Curr Reg])=TRUE,BLANK(),DIVIDE([Year To Date - Revenue Amount Curr Reg],[Year To Date Last Year - Revenue Amount Curr Reg])-1)",
            "formatString": "0.0%;-0.0%;0.0%",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Net Sales Amount Curr Trans - Growth YTD %",
            "expression": "IF(ISBLANK([Year To Date Last Year - Net Sales Amount Curr Trans])=TRUE,BLANK(),DIVIDE([Year To Date - Net Sales Amount Curr Trans],[Year To Date Last Year - Net Sales Amount Curr Trans])-1)",
            "formatString": "0.0%;-0.0%;0.0%",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Revenue Amount Curr Trans - Growth YTD %",
            "expression": "IF(ISBLANK([Year To Date Last Year - Revenue Amount Curr Trans])=TRUE,BLANK(),DIVIDE([Year To Date - Revenue Amount Curr Trans],[Year To Date Last Year - Revenue Amount Curr Trans])-1)",
            "formatString": "0.0%;-0.0%;0.0%",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Revenue Per Ton Ex Alabama Curr Acc - Growth YTD %",
            "expression": "IF(ISBLANK([Year To Date Last Year - Revenue Per Ton Ex Alabama Curr Acc])=TRUE,BLANK(),DIVIDE([Year To Date - Revenue Per Ton Ex Alabama Curr Acc],[Year To Date Last Year - Revenue Per Ton Ex Alabama Curr Acc])-1)",
            "formatString": "0.0%;-0.0%;0.0%",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Revenue Per Ton Ex Alabama Curr Trans - Growth YTD %",
            "expression": "IF(ISBLANK([Year To Date Last Year - Revenue Per Ton Ex Alabama Curr Trans])=TRUE,BLANK(),DIVIDE([Year To Date - Revenue Per Ton Ex Alabama Curr Trans],[Year To Date Last Year - Revenue Per Ton Ex Alabama Curr Trans])-1)",
            "formatString": "0.0%;-0.0%;0.0%",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Revenue Per Ton Ex Alabama Curr Reg - Growth YTD %",
            "expression": "IF(ISBLANK([Year To Date Last Year - Revenue Per Ton Ex Alabama Curr Reg])=TRUE,BLANK(),DIVIDE([Year To Date - Revenue Per Ton Ex Alabama Curr Reg],[Year To Date Last Year - Revenue Per Ton Ex Alabama Curr Reg])-1)",
            "formatString": "0.0%;-0.0%;0.0%",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Short Tons Ex Alabama - Growth YTD %",
            "expression": "IF(ISBLANK([Year To Date Last Year - Short Tons Ex Alabama])=TRUE,BLANK(),DIVIDE([Year To Date - Short Tons Ex Alabama],[Year To Date Last Year - Short Tons Ex Alabama])-1)",
            "formatString": "0.0%;-0.0%;0.0%",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Metric Tons Ex Alabama - Growth YTD %",
            "expression": "IF(ISBLANK([Year To Date Last Year - Metric Tons Ex Alabama])=TRUE,BLANK(),DIVIDE([Year To Date - Metric Tons Ex Alabama],[Year To Date Last Year - Metric Tons Ex Alabama])-1)",
            "formatString": "0.0%;-0.0%;0.0%",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Previous Month - Revenue Per Ton Ex Alabama Curr Reg",
            "expression": "CALCULATE([Revenue Per Ton Ex Alabama Curr Reg],PREVIOUSMONTH('Date'[Date]))",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Previous Month"
          },
          {
            "name": "Previous Month - Revenue Per Ton Ex Alabama Curr Acc",
            "expression": "CALCULATE([Revenue Per Ton Ex Alabama Curr Acc],PREVIOUSMONTH('Date'[Date]))",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Previous Month"
          },
          {
            "name": "Previous Month - Revenue Per Ton Ex Alabama Curr Trans",
            "expression": "CALCULATE([Revenue Per Ton Ex Alabama Curr Trans],PREVIOUSMONTH('Date'[Date]))",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Previous Month"
          },
          {
            "name": "Revenue Per Ton Ex Alabama Curr Acc - Growth Month",
            "expression": "[Revenue Per Ton Ex Alabama Curr Acc]-[Previous Month - Revenue Per Ton Ex Alabama Curr Acc]",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Previous Month"
          },
          {
            "name": "Revenue Per Ton Ex Alabama Curr Trans - Growth Month",
            "expression": "[Revenue Per Ton Ex Alabama Curr Trans]-[Previous Month - Revenue Per Ton Ex Alabama Curr Trans]",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Previous Month"
          },
          {
            "name": "Revenue Per Ton Ex Alabama Curr Acc - Growth Month %",
            "expression": "IF(ISBLANK([Previous Month - Revenue Per Ton Ex Alabama Curr Acc])=TRUE,BLANK(),DIVIDE([Revenue Per Ton Ex Alabama Curr Acc],[Previous Month - Revenue Per Ton Ex Alabama Curr Acc])-1)",
            "formatString": "0.0%;-0.0%;0.0%",
            "displayFolder": "Time Intelligence - Previous Month"
          },
          {
            "name": "Revenue Per Ton Ex Alabama Curr Trans - Growth Month %",
            "expression": "IF(ISBLANK([Previous Month - Revenue Per Ton Ex Alabama Curr Trans])=TRUE,BLANK(),DIVIDE([Revenue Per Ton Ex Alabama Curr Trans],[Previous Month - Revenue Per Ton Ex Alabama Curr Trans])-1)",
            "formatString": "0.0%;-0.0%;0.0%",
            "displayFolder": "Time Intelligence - Previous Month"
          },
          {
            "name": "Revenue Per Ton Ex Alabama Curr Reg - Growth Month %",
            "expression": "IF(ISBLANK([Previous Month - Revenue Per Ton Ex Alabama Curr Reg])=TRUE,BLANK(),DIVIDE([Revenue Per Ton Ex Alabama Curr Reg],[Previous Month - Revenue Per Ton Ex Alabama Curr Reg])-1)",
            "formatString": "0.0%;-0.0%;0.0%",
            "displayFolder": "Time Intelligence - Previous Month"
          },
          {
            "name": "Revenue Per Ton Ex Alabama Curr Reg - Growth Month",
            "expression": "[Revenue Per Ton Ex Alabama Curr Reg]-[Previous Month - Revenue Per Ton Ex Alabama Curr Reg]",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Previous Month"
          },
          {
            "name": "Short Tons Ex Alabama (k)",
            "expression": "DIVIDE(SUMX(FILTER('Sales Invoices','Sales Invoices'[Charge Group]<>\"ALABAMA SEVERANCE TAX\"),[NetWeightShortTons]),1000)",
            "formatString": "#,0.00",
            "displayFolder": "Sales Invoice Regional Measures"
          },
          {
            "name": "Previous Month - Short Tons Ex Alabama (k)",
            "expression": "DIVIDE(CALCULATE([Short Tons Ex Alabama],PREVIOUSMONTH('Date'[Date])),1000)",
            "formatString": "#,0.00",
            "displayFolder": "Sales Invoice Regional Measures"
          },
          {
            "name": "Short Tons Ex Alabama - Growth Month (k)",
            "expression": "DIVIDE([Short Tons Ex Alabama]-[Previous Month - Short Tons Ex Alabama],1000)",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Previous Month"
          },
          {
            "name": "Year To Date Last Year - Short Tons Ex Alabama (k)",
            "expression": "DIVIDE(CALCULATE([Year To Date - Short Tons Ex Alabama],SAMEPERIODLASTYEAR('Date'[Date])),1000)",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Year To Date - Short Tons Ex Alabama (k)",
            "expression": "DIVIDE(TOTALYTD([Short Tons Ex Alabama],'Date'[Date]) ,1000)",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Short Tons Ex Alabama - Growth YTD (k)",
            "expression": "DIVIDE([Year To Date - Short Tons Ex Alabama]-[Year To Date Last Year - Short Tons Ex Alabama],1000)",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Year To Date - Revenue Amount Curr Reg (k)",
            "expression": "DIVIDE(TOTALYTD([Revenue Amount Curr Reg],'Date'[Date]) ,1000)",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Year To Date Last Year - Revenue Amount Curr Reg (k)",
            "expression": "DIVIDE(CALCULATE([Year To Date - Revenue Amount Curr Reg],SAMEPERIODLASTYEAR('Date'[Date])),1000)",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Revenue Amount Curr Reg - Growth YTD (k)",
            "expression": "DIVIDE([Year To Date - Revenue Amount Curr Reg]-[Year To Date Last Year - Revenue Amount Curr Reg],1000)",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Revenue Amount Curr Reg - Growth Month (k)",
            "expression": "DIVIDE([Revenue Amount Curr Reg]-[Previous Month - Revenue Amount Curr Reg],1000)",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Previous Month"
          },
          {
            "name": "Previous Month - Revenue Amount Curr Reg (k)",
            "expression": "DIVIDE(CALCULATE([Revenue Amount Curr Reg],PREVIOUSMONTH('Date'[Date])),1000)",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Previous Month"
          },
          {
            "name": "Revenue Amount Curr Reg (k)",
            "expression": "DIVIDE(SUM([RevenueAmountCurrReg]),1000)",
            "formatString": "#,0.00",
            "displayFolder": "Sales Invoice Amount Regional Currency"
          },
          {
            "name": "Previous Year - Short Tons",
            "expression": "CALCULATE([Short Tons],PREVIOUSYEAR('Date'[Date]))",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Previous Year"
          },
          {
            "name": "Previous Year - Short Tons Ex Alabama",
            "expression": "CALCULATE([Short Tons Ex Alabama],PREVIOUSYEAR('Date'[Date]))",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Previous Year"
          },
          {
            "name": "Previous Year - Short Tons Ex Alabama (k)",
            "expression": "DIVIDE(CALCULATE([Short Tons Ex Alabama],PREVIOUSYEAR('Date'[Date])),1000)",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Previous Year"
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "vFactSalesInvoices"
          },
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": "SELECT [dbo].[vFactSalesInvoices].[DIM_DataForest_SKEY],[dbo].[vFactSalesInvoices].[DIM_SalesOrderLine_SKEY],[dbo].[vFactSalesInvoices].[DIM_SalesInvoiceLine_SKEY],[dbo].[vFactSalesInvoices].[DIM_LegalEntity_SKEY],[dbo].[vFactSalesInvoices].[DIM_TgkLegalEntity_SKEY],[dbo].[vFactSalesInvoices].[DIM_Plant_SKEY],[dbo].[vFactSalesInvoices].[DIM_Date_Invoice_SKEY],[dbo].[vFactSalesInvoices].[DIM_Currency_Transaction_SKEY],[dbo].[vFactSalesInvoices].[DIM_Currency_Accounting_SKEY],[dbo].[vFactSalesInvoices].[DIM_Currency_Regional_SKEY],[dbo].[vFactSalesInvoices].[DIM_Customer_Invoice_SKEY],[dbo].[vFactSalesInvoices].[DIM_TermsOfDelivery_SKEY],[dbo].[vFactSalesInvoices].[DIM_Unit_Sales_SKEY],[dbo].[vFactSalesInvoices].[DIM_Product_SKEY],[dbo].[vFactSalesInvoices].[DIM_GroupSIC_SKEY],[dbo].[vFactSalesInvoices].[CURR_DIM_GroupSIC_SKEY],[dbo].[vFactSalesInvoices].[DIM_GroupSPC_SKEY],[dbo].[vFactSalesInvoices].[CURR_DIM_GroupSPC_SKEY],[dbo].[vFactSalesInvoices].[InvoiceNumberSequence],[dbo].[vFactSalesInvoices].[InvoiceNumber],[dbo].[vFactSalesInvoices].[InvoiceDate],[dbo].[vFactSalesInvoices].[SalesUnitId],[dbo].[vFactSalesInvoices].[InvoiceHasCreditNote],[dbo].[vFactSalesInvoices].[InvoiceNature],[dbo].[vFactSalesInvoices].[InvoiceNatureDescription],[dbo].[vFactSalesInvoices].[InvoiceFiscalCode],[dbo].[vFactSalesInvoices].[InvoiceFiscalDescription],[dbo].[vFactSalesInvoices].[SalesPrice],[dbo].[vFactSalesInvoices].[SalesPriceUnit],[dbo].[vFactSalesInvoices].[QtySalesUnit],[dbo].[vFactSalesInvoices].[QtyTon],[dbo].[vFactSalesInvoices].[GrossWeight],[dbo].[vFactSalesInvoices].[NetWeight],[dbo].[vFactSalesInvoices].[NetWeightShortTons],[dbo].[vFactSalesInvoices].[InvoiceLineId],[dbo].[vFactSalesInvoices].[FreightType],[dbo].[vFactSalesInvoices].[InvoiceReference],[dbo].[vFactSalesInvoices].[CustomerReference],[dbo].[vFactSalesInvoices].[ShipVia],[dbo].[vFactSalesInvoices].[InvoiceStatus],[dbo].[vFactSalesInvoices].[DueDate],[dbo].[vFactSalesInvoices].[TermsOfPaymentCode],[dbo].[vFactSalesInvoices].[MethodOfPaymentCode],[dbo].[vFactSalesInvoices].[LastUpdated],[dbo].[vFactSalesInvoices].[ChargeFlag],[dbo].[vFactSalesInvoices].[ChargeGroup],[dbo].[vFactSalesInvoices].[DIM_Customerdeliveryaddress_SKEY],[dbo].[vFactSalesInvoices].[SalesOrderLineId],[dbo].[vFactSalesInvoices].[ExchangeRateCurrAcc],[dbo].[vFactSalesInvoices].[ExchangeRateCurrReg],[dbo].[vFactSalesInvoices].[NetInvoiceAmountCurrTrans],[dbo].[vFactSalesInvoices].[NetInvoiceAmountCurrAcc],[dbo].[vFactSalesInvoices].[NetInvoiceAmountCurrReg],[dbo].[vFactSalesInvoices].[RevenueAmountCurrTrans],[dbo].[vFactSalesInvoices].[RevenueAmountCurrAcc],[dbo].[vFactSalesInvoices].[RevenueAmountCurrReg],[dbo].[vFactSalesInvoices].[FreightAmountCurrTrans],[dbo].[vFactSalesInvoices].[FreightAmountCurrAcc],[dbo].[vFactSalesInvoices].[FreightAmountCurrReg],[dbo].[vFactSalesInvoices].[NonFreightAmountCurrTrans],[dbo].[vFactSalesInvoices].[NonFreightAmountCurrAcc],[dbo].[vFactSalesInvoices].[NonFreightAmountCurrReg],[dbo].[vFactSalesInvoices].[VATTaxAmountCurrTrans],[dbo].[vFactSalesInvoices].[VATTaxAmountCurrAcc],[dbo].[vFactSalesInvoices].[VATTaxAmountCurrReg],[dbo].[vFactSalesInvoices].[FederalTaxAmountCurrTrans],[dbo].[vFactSalesInvoices].[FederalTaxAmountCurrAcc],[dbo].[vFactSalesInvoices].[FederalTaxAmountCurrReg],[dbo].[vFactSalesInvoices].[StateTaxAmountCurrTrans],[dbo].[vFactSalesInvoices].[StateTaxAmountCurrAcc],[dbo].[vFactSalesInvoices].[StateTaxAmountCurrReg],[dbo].[vFactSalesInvoices].[CityTaxAmountCurrTrans],[dbo].[vFactSalesInvoices].[CityTaxAmountCurrAcc],[dbo].[vFactSalesInvoices].[CityTaxAmountCurrReg],[dbo].[vFactSalesInvoices].[TaxAmountCurrTrans],[dbo].[vFactSalesInvoices].[TaxAmountCurrAcc],[dbo].[vFactSalesInvoices].[TaxAmountCurrReg],[dbo].[vFactSalesInvoices].[InvoiceAmountCurrTrans],[dbo].[vFactSalesInvoices].[InvoiceAmountCurrAcc],[dbo].[vFactSalesInvoices].[InvoiceAmountCurrReg],[dbo].[vFactSalesInvoices].[NetSalesAmountCurrTrans],[dbo].[vFactSalesInvoices].[NetSalesAmountCurrAcc],[dbo].[vFactSalesInvoices].[NetSalesAmountCurrReg],[dbo].[vFactSalesInvoices].[FreightAmountCurrRegSys],[dbo].[vFactSalesInvoices].[InvoiceAmountCurrRegSys],[dbo].[vFactSalesInvoices].[NetInvoiceAmountCurrRegSys],[dbo].[vFactSalesInvoices].[StateTaxAmountCurrRegSys],[dbo].[vFactSalesInvoices].[TaxAmountCurrRegSys],[dbo].[vFactSalesInvoices].[VATTaxAmountCurrRegSys] FROM [dbo].[vFactSalesInvoices] where DIM_DataForest_SKEY like '20%'"
          },
          {
            "name": "QueryEditorSerialization",
            "value": "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT [dbo].[vFactSalesInvoices].[DIM_DataForest_SKEY],[dbo].[vFactSalesInvoices].[DIM_SalesOrderLine_SKEY],[dbo].[vFactSalesInvoices].[DIM_SalesInvoiceLine_SKEY],[dbo].[vFactSalesInvoices].[DIM_LegalEntity_SKEY],[dbo].[vFactSalesInvoices].[DIM_TgkLegalEntity_SKEY],[dbo].[vFactSalesInvoices].[DIM_Plant_SKEY],[dbo].[vFactSalesInvoices].[DIM_Date_Invoice_SKEY],[dbo].[vFactSalesInvoices].[DIM_Currency_Transaction_SKEY],[dbo].[vFactSalesInvoices].[DIM_Currency_Accounting_SKEY],[dbo].[vFactSalesInvoices].[DIM_Currency_Regional_SKEY],[dbo].[vFactSalesInvoices].[DIM_Customer_Invoice_SKEY],[dbo].[vFactSalesInvoices].[DIM_TermsOfDelivery_SKEY],[dbo].[vFactSalesInvoices].[DIM_Unit_Sales_SKEY],[dbo].[vFactSalesInvoices].[DIM_Product_SKEY],[dbo].[vFactSalesInvoices].[DIM_GroupSIC_SKEY],[dbo].[vFactSalesInvoices].[CURR_DIM_GroupSIC_SKEY],[dbo].[vFactSalesInvoices].[DIM_GroupSPC_SKEY],[dbo].[vFactSalesInvoices].[CURR_DIM_GroupSPC_SKEY],[dbo].[vFactSalesInvoices].[InvoiceNumberSequence],[dbo].[vFactSalesInvoices].[InvoiceNumber],[dbo].[vFactSalesInvoices].[InvoiceDate],[dbo].[vFactSalesInvoices].[SalesUnitId],[dbo].[vFactSalesInvoices].[InvoiceHasCreditNote],[dbo].[vFactSalesInvoices].[InvoiceNature],[dbo].[vFactSalesInvoices].[InvoiceNatureDescription],[dbo].[vFactSalesInvoices].[InvoiceFiscalCode],[dbo].[vFactSalesInvoices].[InvoiceFiscalDescription],[dbo].[vFactSalesInvoices].[SalesPrice],[dbo].[vFactSalesInvoices].[SalesPriceUnit],[dbo].[vFactSalesInvoices].[QtySalesUnit],[dbo].[vFactSalesInvoices].[QtyTon],[dbo].[vFactSalesInvoices].[GrossWeight],[dbo].[vFactSalesInvoices].[NetWeight],[dbo].[vFactSalesInvoices].[NetWeightShortTons],[dbo].[vFactSalesInvoices].[InvoiceLineId],[dbo].[vFactSalesInvoices].[FreightType],[dbo].[vFactSalesInvoices].[InvoiceReference],[dbo].[vFactSalesInvoices].[CustomerReference],[dbo].[vFactSalesInvoices].[ShipVia],[dbo].[vFactSalesInvoices].[InvoiceStatus],[dbo].[vFactSalesInvoices].[DueDate],[dbo].[vFactSalesInvoices].[TermsOfPaymentCode],[dbo].[vFactSalesInvoices].[MethodOfPaymentCode],[dbo].[vFactSalesInvoices].[LastUpdated],[dbo].[vFactSalesInvoices].[ChargeFlag],[dbo].[vFactSalesInvoices].[ChargeGroup],[dbo].[vFactSalesInvoices].[DIM_Customerdeliveryaddress_SKEY],[dbo].[vFactSalesInvoices].[SalesOrderLineId],[dbo].[vFactSalesInvoices].[ExchangeRateCurrAcc],[dbo].[vFactSalesInvoices].[ExchangeRateCurrReg],[dbo].[vFactSalesInvoices].[NetInvoiceAmountCurrTrans],[dbo].[vFactSalesInvoices].[NetInvoiceAmountCurrAcc],[dbo].[vFactSalesInvoices].[NetInvoiceAmountCurrReg],[dbo].[vFactSalesInvoices].[RevenueAmountCurrTrans],[dbo].[vFactSalesInvoices].[RevenueAmountCurrAcc],[dbo].[vFactSalesInvoices].[RevenueAmountCurrReg],[dbo].[vFactSalesInvoices].[FreightAmountCurrTrans],[dbo].[vFactSalesInvoices].[FreightAmountCurrAcc],[dbo].[vFactSalesInvoices].[FreightAmountCurrReg],[dbo].[vFactSalesInvoices].[NonFreightAmountCurrTrans],[dbo].[vFactSalesInvoices].[NonFreightAmountCurrAcc],[dbo].[vFactSalesInvoices].[NonFreightAmountCurrReg],[dbo].[vFactSalesInvoices].[VATTaxAmountCurrTrans],[dbo].[vFactSalesInvoices].[VATTaxAmountCurrAcc],[dbo].[vFactSalesInvoices].[VATTaxAmountCurrReg],[dbo].[vFactSalesInvoices].[FederalTaxAmountCurrTrans],[dbo].[vFactSalesInvoices].[FederalTaxAmountCurrAcc],[dbo].[vFactSalesInvoices].[FederalTaxAmountCurrReg],[dbo].[vFactSalesInvoices].[StateTaxAmountCurrTrans],[dbo].[vFactSalesInvoices].[StateTaxAmountCurrAcc],[dbo].[vFactSalesInvoices].[StateTaxAmountCurrReg],[dbo].[vFactSalesInvoices].[CityTaxAmountCurrTrans],[dbo].[vFactSalesInvoices].[CityTaxAmountCurrAcc],[dbo].[vFactSalesInvoices].[CityTaxAmountCurrReg],[dbo].[vFactSalesInvoices].[TaxAmountCurrTrans],[dbo].[vFactSalesInvoices].[TaxAmountCurrAcc],[dbo].[vFactSalesInvoices].[TaxAmountCurrReg],[dbo].[vFactSalesInvoices].[InvoiceAmountCurrTrans],[dbo].[vFactSalesInvoices].[InvoiceAmountCurrAcc],[dbo].[vFactSalesInvoices].[InvoiceAmountCurrReg],[dbo].[vFactSalesInvoices].[NetSalesAmountCurrTrans],[dbo].[vFactSalesInvoices].[NetSalesAmountCurrAcc],[dbo].[vFactSalesInvoices].[NetSalesAmountCurrReg],[dbo].[vFactSalesInvoices].[FreightAmountCurrRegSys],[dbo].[vFactSalesInvoices].[InvoiceAmountCurrRegSys],[dbo].[vFactSalesInvoices].[NetInvoiceAmountCurrRegSys],[dbo].[vFactSalesInvoices].[StateTaxAmountCurrRegSys],[dbo].[vFactSalesInvoices].[TaxAmountCurrRegSys],[dbo].[vFactSalesInvoices].[VATTaxAmountCurrRegSys] FROM [dbo].[vFactSalesInvoices] where DIM_DataForest_SKEY like '20%'</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
          }
        ]
      },
      {
        "name": "Regional Currency",
        "columns": [
          {
            "name": "DIM_Currency_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_Currency_SKEY"
          },
          {
            "name": "Currency Code",
            "dataType": "string",
            "sourceColumn": "CurrencyCode"
          },
          {
            "name": "Currency Description",
            "dataType": "string",
            "sourceColumn": "CurrencyDescription"
          },
          {
            "name": "ISO Code",
            "dataType": "string",
            "sourceColumn": "ISOCode"
          },
          {
            "name": "Last Updated",
            "dataType": "dateTime",
            "sourceColumn": "LastUpdated"
          },
          {
            "name": "DIM_DataForest_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_DataForest_SKEY"
          },
          {
            "name": "ISO Description",
            "dataType": "string",
            "sourceColumn": "ISODescription"
          }
        ],
        "partitions": [
          {
            "name": "vwDimCurrency",
            "source": {
              "query": "SELECT [dbo].[vDimCurrency].[DIM_Currency_SKEY],[dbo].[vDimCurrency].[CurrencyCode],[dbo].[vDimCurrency].[CurrencyDescription],[dbo].[vDimCurrency].[ISOCode],[dbo].[vDimCurrency].[ISODescription],[dbo].[vDimCurrency].[LastUpdated],[dbo].[vDimCurrency].[DIM_DataForest_SKEY] FROM [dbo].[vDimCurrency] where DIM_DataForest_SKEY like '20%'",
              "dataSource": "sibgrpudmsqlsrvd0001"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT [dbo].[vDimCurrency].[DIM_Currency_SKEY],[dbo].[vDimCurrency].[CurrencyCode],[dbo].[vDimCurrency].[CurrencyDescription],[dbo].[vDimCurrency].[ISOCode],[dbo].[vDimCurrency].[ISODescription],[dbo].[vDimCurrency].[LastUpdated],[dbo].[vDimCurrency].[DIM_DataForest_SKEY] FROM [dbo].[vDimCurrency] where DIM_DataForest_SKEY like '20%'</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "vDimCurrency"
          },
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": "SELECT [dbo].[vDimCurrency].[DIM_Currency_SKEY],[dbo].[vDimCurrency].[CurrencyCode],[dbo].[vDimCurrency].[CurrencyDescription],[dbo].[vDimCurrency].[ISOCode],[dbo].[vDimCurrency].[ISODescription],[dbo].[vDimCurrency].[LastUpdated],[dbo].[vDimCurrency].[DIM_DataForest_SKEY] FROM [dbo].[vDimCurrency] where DIM_DataForest_SKEY like '20%'"
          },
          {
            "name": "QueryEditorSerialization",
            "value": "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT [dbo].[vDimCurrency].[DIM_Currency_SKEY],[dbo].[vDimCurrency].[CurrencyCode],[dbo].[vDimCurrency].[CurrencyDescription],[dbo].[vDimCurrency].[ISOCode],[dbo].[vDimCurrency].[ISODescription],[dbo].[vDimCurrency].[LastUpdated],[dbo].[vDimCurrency].[DIM_DataForest_SKEY] FROM [dbo].[vDimCurrency] where DIM_DataForest_SKEY like '20%'</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
          }
        ]
      },
      {
        "name": "Sales Budgets",
        "columns": [
          {
            "name": "DIM_LegalEntity_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_LegalEntity_SKEY"
          },
          {
            "name": "DIM_Plant_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_Plant_SKEY"
          },
          {
            "name": "DIM_Date_Period_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_Date_Period_SKEY"
          },
          {
            "name": "DIM_Currency_Accounting_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_Currency_Accounting_SKEY"
          },
          {
            "name": "DIM_Currency_Regional_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_Currency_Regional_SKEY"
          },
          {
            "name": "DIM_Customer_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_Customer_SKEY"
          },
          {
            "name": "DIM_Unit_Sales_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_Unit_Sales_SKEY"
          },
          {
            "name": "DIM_Product_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_Product_SKEY"
          },
          {
            "name": "QtySalesUnit",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "QtySalesUnit"
          },
          {
            "name": "CogsAmountCurrAcc",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "CogsAmountCurrAcc"
          },
          {
            "name": "CogsAmountCurrReg",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "CogsAmountCurrReg"
          },
          {
            "name": "NetSalesAmountCurrAcc",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "NetSalesAmountCurrAcc"
          },
          {
            "name": "NetSalesAmountCurrReg",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "NetSalesAmountCurrReg"
          },
          {
            "name": "FreightAmountCurrAcc",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "FreightAmountCurrAcc"
          },
          {
            "name": "FreightAmountCurrReg",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "FreightAmountCurrReg"
          },
          {
            "name": "RevenueAmountCurrAcc",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "RevenueAmountCurrAcc"
          },
          {
            "name": "RevenueAmountCurrReg",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "RevenueAmountCurrReg"
          },
          {
            "name": "DIM_GroupSIC_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_GroupSIC_SKEY"
          },
          {
            "name": "DIM_GroupSPC_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_GroupSPC_SKEY"
          },
          {
            "name": "CURR_DIM_GroupSIC_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CURR_DIM_GroupSIC_SKEY"
          },
          {
            "name": "CURR_DIM_GroupSPC_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CURR_DIM_GroupSPC_SKEY"
          },
          {
            "name": "DIM_DataForest_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_DataForest_SKEY"
          },
          {
            "name": "DIM_TgkLegalEntity_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_TgkLegalEntity_SKEY"
          },
          {
            "name": "DIM_Currency_Transaction_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_Currency_Transaction_SKEY"
          },
          {
            "name": "DIM_Customerdeliveryaddress_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_Customerdeliveryaddress_SKEY"
          }
        ],
        "partitions": [
          {
            "name": "vwFactSalesBudgets",
            "source": {
              "query": "SELECT [dbo].[vFactSalesBudgets].[DIM_LegalEntity_SKEY],[dbo].[vFactSalesBudgets].[DIM_TgkLegalEntity_SKEY],[dbo].[vFactSalesBudgets].[DIM_Plant_SKEY],[dbo].[vFactSalesBudgets].[DIM_Date_Period_SKEY],[dbo].[vFactSalesBudgets].[DIM_Currency_Transaction_SKEY],[dbo].[vFactSalesBudgets].[DIM_Currency_Accounting_SKEY],[dbo].[vFactSalesBudgets].[DIM_Currency_Regional_SKEY],[dbo].[vFactSalesBudgets].[DIM_Customerdeliveryaddress_SKEY],[dbo].[vFactSalesBudgets].[DIM_Customer_SKEY],[dbo].[vFactSalesBudgets].[DIM_Unit_Sales_SKEY],[dbo].[vFactSalesBudgets].[DIM_Product_SKEY],[dbo].[vFactSalesBudgets].[DIM_GroupSIC_SKEY],[dbo].[vFactSalesBudgets].[CURR_DIM_GroupSIC_SKEY],[dbo].[vFactSalesBudgets].[DIM_GroupSPC_SKEY],[dbo].[vFactSalesBudgets].[CURR_DIM_GroupSPC_SKEY],[dbo].[vFactSalesBudgets].[QtySalesUnit],[dbo].[vFactSalesBudgets].[CogsAmountCurrAcc],[dbo].[vFactSalesBudgets].[CogsAmountCurrReg],[dbo].[vFactSalesBudgets].[NetSalesAmountCurrAcc],[dbo].[vFactSalesBudgets].[NetSalesAmountCurrReg],[dbo].[vFactSalesBudgets].[FreightAmountCurrAcc],[dbo].[vFactSalesBudgets].[FreightAmountCurrReg],[dbo].[vFactSalesBudgets].[RevenueAmountCurrAcc],[dbo].[vFactSalesBudgets].[RevenueAmountCurrReg],[dbo].[vFactSalesBudgets].[DIM_DataForest_SKEY] FROM [dbo].[vFactSalesBudgets] where DIM_DataForest_SKEY like '20%'",
              "dataSource": "sibgrpudmsqlsrvd0001"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT [dbo].[vFactSalesBudgets].[DIM_LegalEntity_SKEY],[dbo].[vFactSalesBudgets].[DIM_TgkLegalEntity_SKEY],[dbo].[vFactSalesBudgets].[DIM_Plant_SKEY],[dbo].[vFactSalesBudgets].[DIM_Date_Period_SKEY],[dbo].[vFactSalesBudgets].[DIM_Currency_Transaction_SKEY],[dbo].[vFactSalesBudgets].[DIM_Currency_Accounting_SKEY],[dbo].[vFactSalesBudgets].[DIM_Currency_Regional_SKEY],[dbo].[vFactSalesBudgets].[DIM_Customerdeliveryaddress_SKEY],[dbo].[vFactSalesBudgets].[DIM_Customer_SKEY],[dbo].[vFactSalesBudgets].[DIM_Unit_Sales_SKEY],[dbo].[vFactSalesBudgets].[DIM_Product_SKEY],[dbo].[vFactSalesBudgets].[DIM_GroupSIC_SKEY],[dbo].[vFactSalesBudgets].[CURR_DIM_GroupSIC_SKEY],[dbo].[vFactSalesBudgets].[DIM_GroupSPC_SKEY],[dbo].[vFactSalesBudgets].[CURR_DIM_GroupSPC_SKEY],[dbo].[vFactSalesBudgets].[QtySalesUnit],[dbo].[vFactSalesBudgets].[CogsAmountCurrAcc],[dbo].[vFactSalesBudgets].[CogsAmountCurrReg],[dbo].[vFactSalesBudgets].[NetSalesAmountCurrAcc],[dbo].[vFactSalesBudgets].[NetSalesAmountCurrReg],[dbo].[vFactSalesBudgets].[FreightAmountCurrAcc],[dbo].[vFactSalesBudgets].[FreightAmountCurrReg],[dbo].[vFactSalesBudgets].[RevenueAmountCurrAcc],[dbo].[vFactSalesBudgets].[RevenueAmountCurrReg],[dbo].[vFactSalesBudgets].[DIM_DataForest_SKEY] FROM [dbo].[vFactSalesBudgets] where DIM_DataForest_SKEY like '20%'</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
              }
            ]
          }
        ],
        "measures": [
          {
            "name": "Qty Budgeted Sales Unit",
            "expression": "SUM([QtySalesUnit])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Budget Qty"
          },
          {
            "name": "Budgeted Cogs Amount Curr Acc",
            "expression": "SUM([CogsAmountCurrAcc])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Budget Amount Accounting Currency"
          },
          {
            "name": "Budgeted Cogs Amount Curr Reg",
            "expression": "SUM([CogsAmountCurrReg])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Budget Amount Regional Currency"
          },
          {
            "name": "Budgeted Net Sales Amount Curr Acc",
            "expression": "SUM([NetSalesAmountCurrAcc])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Budget Amount Accounting Currency"
          },
          {
            "name": "Budgeted Net Sales Amount Curr Reg",
            "expression": "SUM([NetSalesAmountCurrReg])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Budget Amount Regional Currency"
          },
          {
            "name": "Budgeted Revenue Amount Curr Acc",
            "expression": "SUM([RevenueAmountCurrAcc])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Budget Amount Accounting Currency"
          },
          {
            "name": "Budgeted Revenue Amount Curr Reg",
            "expression": "SUM([RevenueAmountCurrReg])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Budget Amount Regional Currency"
          },
          {
            "name": "Budgeted Price Per Ton Curr Acc",
            "expression": "DIVIDE(SUM('Sales Budgets'[NetSalesAmountCurrAcc]),SUM('Sales Budgets'[QtySalesUnit]))",
            "formatString": "#,0.00",
            "displayFolder": "Sales Budget Amount Accounting Currency"
          },
          {
            "name": "Budgeted Price Per Ton Curr Reg",
            "expression": "DIVIDE(SUM('Sales Budgets'[NetSalesAmountCurrReg]),SUM('Sales Budgets'[QtySalesUnit]))",
            "formatString": "#,0.00",
            "displayFolder": "Sales Budget Amount Regional Currency"
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "vFactSalesBudgets"
          },
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": "SELECT [dbo].[vFactSalesBudgets].[DIM_LegalEntity_SKEY],[dbo].[vFactSalesBudgets].[DIM_TgkLegalEntity_SKEY],[dbo].[vFactSalesBudgets].[DIM_Plant_SKEY],[dbo].[vFactSalesBudgets].[DIM_Date_Period_SKEY],[dbo].[vFactSalesBudgets].[DIM_Currency_Transaction_SKEY],[dbo].[vFactSalesBudgets].[DIM_Currency_Accounting_SKEY],[dbo].[vFactSalesBudgets].[DIM_Currency_Regional_SKEY],[dbo].[vFactSalesBudgets].[DIM_Customerdeliveryaddress_SKEY],[dbo].[vFactSalesBudgets].[DIM_Customer_SKEY],[dbo].[vFactSalesBudgets].[DIM_Unit_Sales_SKEY],[dbo].[vFactSalesBudgets].[DIM_Product_SKEY],[dbo].[vFactSalesBudgets].[DIM_GroupSIC_SKEY],[dbo].[vFactSalesBudgets].[CURR_DIM_GroupSIC_SKEY],[dbo].[vFactSalesBudgets].[DIM_GroupSPC_SKEY],[dbo].[vFactSalesBudgets].[CURR_DIM_GroupSPC_SKEY],[dbo].[vFactSalesBudgets].[QtySalesUnit],[dbo].[vFactSalesBudgets].[CogsAmountCurrAcc],[dbo].[vFactSalesBudgets].[CogsAmountCurrReg],[dbo].[vFactSalesBudgets].[NetSalesAmountCurrAcc],[dbo].[vFactSalesBudgets].[NetSalesAmountCurrReg],[dbo].[vFactSalesBudgets].[FreightAmountCurrAcc],[dbo].[vFactSalesBudgets].[FreightAmountCurrReg],[dbo].[vFactSalesBudgets].[RevenueAmountCurrAcc],[dbo].[vFactSalesBudgets].[RevenueAmountCurrReg],[dbo].[vFactSalesBudgets].[DIM_DataForest_SKEY] FROM [dbo].[vFactSalesBudgets] where DIM_DataForest_SKEY like '20%'"
          },
          {
            "name": "QueryEditorSerialization",
            "value": "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT [dbo].[vFactSalesBudgets].[DIM_LegalEntity_SKEY],[dbo].[vFactSalesBudgets].[DIM_TgkLegalEntity_SKEY],[dbo].[vFactSalesBudgets].[DIM_Plant_SKEY],[dbo].[vFactSalesBudgets].[DIM_Date_Period_SKEY],[dbo].[vFactSalesBudgets].[DIM_Currency_Transaction_SKEY],[dbo].[vFactSalesBudgets].[DIM_Currency_Accounting_SKEY],[dbo].[vFactSalesBudgets].[DIM_Currency_Regional_SKEY],[dbo].[vFactSalesBudgets].[DIM_Customerdeliveryaddress_SKEY],[dbo].[vFactSalesBudgets].[DIM_Customer_SKEY],[dbo].[vFactSalesBudgets].[DIM_Unit_Sales_SKEY],[dbo].[vFactSalesBudgets].[DIM_Product_SKEY],[dbo].[vFactSalesBudgets].[DIM_GroupSIC_SKEY],[dbo].[vFactSalesBudgets].[CURR_DIM_GroupSIC_SKEY],[dbo].[vFactSalesBudgets].[DIM_GroupSPC_SKEY],[dbo].[vFactSalesBudgets].[CURR_DIM_GroupSPC_SKEY],[dbo].[vFactSalesBudgets].[QtySalesUnit],[dbo].[vFactSalesBudgets].[CogsAmountCurrAcc],[dbo].[vFactSalesBudgets].[CogsAmountCurrReg],[dbo].[vFactSalesBudgets].[NetSalesAmountCurrAcc],[dbo].[vFactSalesBudgets].[NetSalesAmountCurrReg],[dbo].[vFactSalesBudgets].[FreightAmountCurrAcc],[dbo].[vFactSalesBudgets].[FreightAmountCurrReg],[dbo].[vFactSalesBudgets].[RevenueAmountCurrAcc],[dbo].[vFactSalesBudgets].[RevenueAmountCurrReg],[dbo].[vFactSalesBudgets].[DIM_DataForest_SKEY] FROM [dbo].[vFactSalesBudgets] where DIM_DataForest_SKEY like '20%'</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
          }
        ]
      },
      {
        "name": "Transaction Currency",
        "columns": [
          {
            "name": "DIM_Currency_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_Currency_SKEY"
          },
          {
            "name": "Currency Code",
            "dataType": "string",
            "sourceColumn": "CurrencyCode"
          },
          {
            "name": "Currency Description",
            "dataType": "string",
            "sourceColumn": "CurrencyDescription"
          },
          {
            "name": "ISO Code",
            "dataType": "string",
            "sourceColumn": "ISOCode"
          },
          {
            "name": "Last Updated",
            "dataType": "dateTime",
            "sourceColumn": "LastUpdated"
          },
          {
            "name": "DIM_DataForest_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_DataForest_SKEY"
          },
          {
            "name": "ISO Description",
            "dataType": "string",
            "sourceColumn": "ISODescription"
          }
        ],
        "partitions": [
          {
            "name": "vwDimCurrency",
            "source": {
              "query": "SELECT [dbo].[vDimCurrency].[DIM_Currency_SKEY],[dbo].[vDimCurrency].[CurrencyCode],[dbo].[vDimCurrency].[CurrencyDescription],[dbo].[vDimCurrency].[ISOCode],[dbo].[vDimCurrency].[ISODescription],[dbo].[vDimCurrency].[LastUpdated],[dbo].[vDimCurrency].[DIM_DataForest_SKEY] FROM [dbo].[vDimCurrency] where DIM_DataForest_SKEY like '20%'",
              "dataSource": "sibgrpudmsqlsrvd0001"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT [dbo].[vDimCurrency].[DIM_Currency_SKEY],[dbo].[vDimCurrency].[CurrencyCode],[dbo].[vDimCurrency].[CurrencyDescription],[dbo].[vDimCurrency].[ISOCode],[dbo].[vDimCurrency].[ISODescription],[dbo].[vDimCurrency].[LastUpdated],[dbo].[vDimCurrency].[DIM_DataForest_SKEY] FROM [dbo].[vDimCurrency] where DIM_DataForest_SKEY like '20%'</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "vDimCurrency"
          },
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": "SELECT [dbo].[vDimCurrency].[DIM_Currency_SKEY],[dbo].[vDimCurrency].[CurrencyCode],[dbo].[vDimCurrency].[CurrencyDescription],[dbo].[vDimCurrency].[ISOCode],[dbo].[vDimCurrency].[ISODescription],[dbo].[vDimCurrency].[LastUpdated],[dbo].[vDimCurrency].[DIM_DataForest_SKEY] FROM [dbo].[vDimCurrency] where DIM_DataForest_SKEY like '20%'"
          },
          {
            "name": "QueryEditorSerialization",
            "value": "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT [dbo].[vDimCurrency].[DIM_Currency_SKEY],[dbo].[vDimCurrency].[CurrencyCode],[dbo].[vDimCurrency].[CurrencyDescription],[dbo].[vDimCurrency].[ISOCode],[dbo].[vDimCurrency].[ISODescription],[dbo].[vDimCurrency].[LastUpdated],[dbo].[vDimCurrency].[DIM_DataForest_SKEY] FROM [dbo].[vDimCurrency] where DIM_DataForest_SKEY like '20%'</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
          }
        ]
      },
      {
        "name": "SIC",
        "columns": [
          {
            "name": "DIM_GroupSIC_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_GroupSIC_SKEY"
          },
          {
            "name": "SIC Code",
            "dataType": "string",
            "sourceColumn": "SICCode"
          },
          {
            "name": "SIC Description",
            "dataType": "string",
            "sourceColumn": "SICDescription"
          },
          {
            "name": "Industry Code",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "IndustryCode"
          },
          {
            "name": "Application Code",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "ApplicationCode"
          },
          {
            "name": "SBS",
            "dataType": "string",
            "sourceColumn": "IndustryName"
          },
          {
            "name": "SBL",
            "dataType": "string",
            "sourceColumn": "ApplicationName"
          },
          {
            "name": "Major Market",
            "dataType": "string",
            "sourceColumn": "MajorMarket"
          },
          {
            "name": "Substream Leader",
            "dataType": "string",
            "sourceColumn": "SubstreamLeader"
          }
        ],
        "partitions": [
          {
            "name": "vwDimCurrGroupSIC",
            "source": {
              "query": " SELECT [grp].[vDimGroupSIC].* FROM [grp].[vDimGroupSIC] ",
              "dataSource": "sibgrpudmsqlsrvd0001"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
                  "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
                  "  <ColumnSuggestedType />",
                  "  <ColumnFormat />",
                  "  <ColumnAccuracy />",
                  "  <ColumnCurrencySymbol />",
                  "  <ColumnPositivePattern />",
                  "  <ColumnNegativePattern />",
                  "  <ColumnWidths>",
                  "    <item>",
                  "      <key>",
                  "        <string>DIM_GroupSIC_SKEY</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>166</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>SICCode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>88</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>SICDescription</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>124</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>IndustryCode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>119</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>IndustryName</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>122</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>ApplicationCode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>132</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>ApplicationName</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>135</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>MajorMarket</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>110</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>SubstreamLeader</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>142</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnWidths>",
                  "  <ColumnDisplayIndex>",
                  "    <item>",
                  "      <key>",
                  "        <string>DIM_GroupSIC_SKEY</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>0</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>SICCode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>1</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>SICDescription</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>2</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>IndustryCode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>3</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>IndustryName</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>4</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>ApplicationCode</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>5</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>ApplicationName</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>6</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>MajorMarket</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>7</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>SubstreamLeader</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>8</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnDisplayIndex>",
                  "  <ColumnFrozen />",
                  "  <ColumnChecked>",
                  "    <item>",
                  "      <key>",
                  "        <string>MajorMarket</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>SubstreamLeader</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnChecked>",
                  "  <ColumnFilter />",
                  "  <SelectionFilter />",
                  "  <FilterParameters />",
                  "  <IsSortDescending>false</IsSortDescending>",
                  "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "grp"
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "vDimGroupSIC"
          },
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [grp].[vDimGroupSIC].* FROM [grp].[vDimGroupSIC] "
          },
          {
            "name": "TableWidgetSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
              "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
              "  <ColumnSuggestedType />",
              "  <ColumnFormat />",
              "  <ColumnAccuracy />",
              "  <ColumnCurrencySymbol />",
              "  <ColumnPositivePattern />",
              "  <ColumnNegativePattern />",
              "  <ColumnWidths>",
              "    <item>",
              "      <key>",
              "        <string>DIM_GroupSIC_SKEY</string>",
              "      </key>",
              "      <value>",
              "        <int>166</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>SICCode</string>",
              "      </key>",
              "      <value>",
              "        <int>88</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>SICDescription</string>",
              "      </key>",
              "      <value>",
              "        <int>124</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>IndustryCode</string>",
              "      </key>",
              "      <value>",
              "        <int>119</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>IndustryName</string>",
              "      </key>",
              "      <value>",
              "        <int>122</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>ApplicationCode</string>",
              "      </key>",
              "      <value>",
              "        <int>132</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>ApplicationName</string>",
              "      </key>",
              "      <value>",
              "        <int>135</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>MajorMarket</string>",
              "      </key>",
              "      <value>",
              "        <int>110</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>SubstreamLeader</string>",
              "      </key>",
              "      <value>",
              "        <int>142</int>",
              "      </value>",
              "    </item>",
              "  </ColumnWidths>",
              "  <ColumnDisplayIndex>",
              "    <item>",
              "      <key>",
              "        <string>DIM_GroupSIC_SKEY</string>",
              "      </key>",
              "      <value>",
              "        <int>0</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>SICCode</string>",
              "      </key>",
              "      <value>",
              "        <int>1</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>SICDescription</string>",
              "      </key>",
              "      <value>",
              "        <int>2</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>IndustryCode</string>",
              "      </key>",
              "      <value>",
              "        <int>3</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>IndustryName</string>",
              "      </key>",
              "      <value>",
              "        <int>4</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>ApplicationCode</string>",
              "      </key>",
              "      <value>",
              "        <int>5</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>ApplicationName</string>",
              "      </key>",
              "      <value>",
              "        <int>6</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>MajorMarket</string>",
              "      </key>",
              "      <value>",
              "        <int>7</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>SubstreamLeader</string>",
              "      </key>",
              "      <value>",
              "        <int>8</int>",
              "      </value>",
              "    </item>",
              "  </ColumnDisplayIndex>",
              "  <ColumnFrozen />",
              "  <ColumnChecked>",
              "    <item>",
              "      <key>",
              "        <string>MajorMarket</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>SubstreamLeader</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "  </ColumnChecked>",
              "  <ColumnFilter />",
              "  <SelectionFilter />",
              "  <FilterParameters />",
              "  <IsSortDescending>false</IsSortDescending>",
              "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "SPC",
        "columns": [
          {
            "name": "DIM_GroupSPC_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_GroupSPC_SKEY"
          },
          {
            "name": "SPC Code",
            "dataType": "string",
            "sourceColumn": "SPCCode"
          },
          {
            "name": "SPC Description",
            "dataType": "string",
            "sourceColumn": "SPCDescription"
          },
          {
            "name": "SPC Category Code",
            "dataType": "string",
            "sourceColumn": "SPCCategoryCode"
          },
          {
            "name": "SPC Category Description",
            "dataType": "string",
            "sourceColumn": "SPCCategoryDescription"
          }
        ],
        "partitions": [
          {
            "name": "vwDimCurrGroupSPC",
            "source": {
              "query": "SELECT [grp].[vDimGroupSPC].* FROM [grp].[vDimGroupSPC]",
              "dataSource": "sibgrpudmsqlsrvd0001"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "&lt;?xml version=\"1.0\" encoding=\"UTF-16\"?&gt;&lt;Gemini xmlns=\"TableWidgetSerialization\"&gt;&lt;AnnotationContent&gt;&lt;![CDATA[&lt;?xml version=\"1.0\"?&gt;",
                  "&lt;TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\"&gt;",
                  "  &lt;ColumnSuggestedType /&gt;",
                  "  &lt;ColumnFormat /&gt;",
                  "  &lt;ColumnAccuracy /&gt;",
                  "  &lt;ColumnCurrencySymbol /&gt;",
                  "  &lt;ColumnPositivePattern /&gt;",
                  "  &lt;ColumnNegativePattern /&gt;",
                  "  &lt;ColumnWidths&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;DIM_GroupSPC_SKEY&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;377&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;SPCCode&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;92&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;SPCDescription&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;128&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;SPCCategoryCode&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;149&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;SPCCategoryDescription&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;185&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "  &lt;/ColumnWidths&gt;",
                  "  &lt;ColumnDisplayIndex&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;DIM_GroupSPC_SKEY&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;0&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;SPCCode&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;1&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;SPCDescription&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;2&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;SPCCategoryCode&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;3&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;SPCCategoryDescription&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;4&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "  &lt;/ColumnDisplayIndex&gt;",
                  "  &lt;ColumnFrozen /&gt;",
                  "  &lt;ColumnChecked /&gt;",
                  "  &lt;ColumnFilter /&gt;",
                  "  &lt;SelectionFilter /&gt;",
                  "  &lt;FilterParameters /&gt;",
                  "  &lt;SortByColumn&gt;SPCCode&lt;/SortByColumn&gt;",
                  "  &lt;IsSortDescending&gt;false&lt;/IsSortDescending&gt;",
                  "&lt;/TableWidgetGridSerialization&gt;]]&gt;&lt;/AnnotationContent&gt;&lt;/Gemini&gt;"
                ]
              }
            ]
          }
        ],
        "hierarchies": [
          {
            "name": "Current By Category",
            "levels": [
              {
                "name": "SPC Category Description",
                "ordinal": 0,
                "column": "SPC Category Description"
              },
              {
                "name": "SPC Description",
                "ordinal": 1,
                "column": "SPC Description"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "grp"
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "vDimGroupSPC"
          },
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [grp].[vDimGroupSPC].* FROM [grp].[vDimGroupSPC] "
          }
        ]
      },
      {
        "name": "Sales Orders",
        "columns": [
          {
            "name": "RecId",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "RecId"
          },
          {
            "name": "CertificateId",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CertificateId"
          },
          {
            "name": "DIM_LegalEntity_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_LegalEntity_SKEY"
          },
          {
            "name": "DIM_Plant_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_Plant_SKEY"
          },
          {
            "name": "DIM_Date_Invoice_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_Date_Invoice_SKEY"
          },
          {
            "name": "DIM_Currency_Transaction_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_Currency_Transaction_SKEY"
          },
          {
            "name": "DIM_Currency_Accounting_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_Currency_Accounting_SKEY"
          },
          {
            "name": "DIM_Currency_Regional_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_Currency_Regional_SKEY"
          },
          {
            "name": "DIM_Customer_Invoice_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_Customer_Invoice_SKEY"
          },
          {
            "name": "DIM_TermsOfDelivery_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_TermsOfDelivery_SKEY"
          },
          {
            "name": "DIM_Unit_Sales_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_Unit_Sales_SKEY"
          },
          {
            "name": "DIM_Product_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_Product_SKEY"
          },
          {
            "name": "DIM_GroupSIC_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_GroupSIC_SKEY"
          },
          {
            "name": "CURR_DIM_GroupSIC_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CURR_DIM_GroupSIC_SKEY"
          },
          {
            "name": "DIM_GroupSPC_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_GroupSPC_SKEY"
          },
          {
            "name": "CURR_DIM_GroupSPC_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CURR_DIM_GroupSPC_SKEY"
          },
          {
            "name": "Sales Order Number Sequence",
            "dataType": "string",
            "sourceColumn": "SalesOrderNumberSequence",
            "displayFolder": "Sales Order Meta"
          },
          {
            "name": "Sales Order Number",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "SalesOrderNumber",
            "displayFolder": "Sales Order Meta"
          },
          {
            "name": "Sales Order Line Number",
            "dataType": "string",
            "sourceColumn": "SalesOrderLineNumber",
            "displayFolder": "Sales Order Meta"
          },
          {
            "name": "Sales Order Line Number Release Number",
            "dataType": "string",
            "sourceColumn": "SalesOrderLineNumberReleaseNumber",
            "displayFolder": "Sales Order Meta"
          },
          {
            "name": "OrderDate",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "OrderDate",
            "formatString": "General Date"
          },
          {
            "name": "Sales Price",
            "dataType": "double",
            "sourceColumn": "SalesPrice",
            "displayFolder": "Sales Order Meta"
          },
          {
            "name": "QtyOrderedSalesUnit",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "QtyOrderedSalesUnit"
          },
          {
            "name": "QtyTon",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "QtyTon"
          },
          {
            "name": "GrossWeight",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "GrossWeight"
          },
          {
            "name": "Sales Order Line Id",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "SalesOrderLineId",
            "displayFolder": "Sales Order Meta"
          },
          {
            "name": "Salesman Code",
            "dataType": "string",
            "sourceColumn": "SalesmanCode",
            "displayFolder": "Sales Order Meta"
          },
          {
            "name": "Customer Reference",
            "dataType": "string",
            "sourceColumn": "CustomerReference",
            "displayFolder": "Sales Order Meta"
          },
          {
            "name": "Ship Via",
            "dataType": "string",
            "sourceColumn": "ShipVia",
            "displayFolder": "Sales Order Meta"
          },
          {
            "name": "Terms Of Payment Code",
            "dataType": "string",
            "sourceColumn": "TermsOfPaymentCode",
            "displayFolder": "Sales Order Meta"
          },
          {
            "name": "Terms Of Delivery Code",
            "dataType": "string",
            "sourceColumn": "TermsOfDeliveryCode",
            "displayFolder": "Sales Order Meta"
          },
          {
            "name": "LastUpdated",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "LastUpdated",
            "formatString": "General Date"
          },
          {
            "name": "Delivery Address Id",
            "dataType": "string",
            "sourceColumn": "DeliveryAddressId",
            "displayFolder": "Sales Order Meta"
          },
          {
            "name": "Delivery Address Name",
            "dataType": "string",
            "sourceColumn": "DeliveryAddressName",
            "displayFolder": "Sales Order Meta"
          },
          {
            "name": "Delivery Address City",
            "dataType": "string",
            "sourceColumn": "DeliveryAddressCity",
            "displayFolder": "Sales Order Meta"
          },
          {
            "name": "Forwarder Code",
            "dataType": "string",
            "sourceColumn": "ForwarderCode",
            "displayFolder": "Sales Order Meta"
          },
          {
            "name": "Forwarder Name",
            "dataType": "string",
            "sourceColumn": "ForwarderName",
            "displayFolder": "Sales Order Meta"
          },
          {
            "name": "Vehicle Equipment Type",
            "dataType": "string",
            "sourceColumn": "VehicleEquipmentType",
            "displayFolder": "Sales Order Meta"
          },
          {
            "name": "Vehicle Equipment Type Description",
            "dataType": "string",
            "sourceColumn": "VehicleEquipmentTypeDescription",
            "displayFolder": "Sales Order Meta"
          },
          {
            "name": "Wanted Delivery Date Hour",
            "dataType": "dateTime",
            "sourceColumn": "WantedDeliveryDateHour",
            "formatString": "General Date",
            "displayFolder": "Sales Order Meta"
          },
          {
            "name": "Bill Of Lading Number",
            "dataType": "string",
            "sourceColumn": "BillOfLadingNumber",
            "displayFolder": "Sales Order Meta"
          },
          {
            "name": "Bourque Status",
            "dataType": "string",
            "sourceColumn": "BourqueStatus",
            "displayFolder": "Sales Order Meta"
          },
          {
            "name": "Cash In Advance",
            "dataType": "string",
            "sourceColumn": "CashInAdvance",
            "displayFolder": "Sales Order Meta"
          },
          {
            "name": "NAFTA",
            "dataType": "string",
            "sourceColumn": "NAFTA",
            "displayFolder": "Sales Order Meta"
          },
          {
            "name": "Delivery Note Number",
            "dataType": "string",
            "sourceColumn": "DeliveryNoteNumber",
            "displayFolder": "Sales Order Meta"
          },
          {
            "name": "Shipment Date",
            "dataType": "dateTime",
            "sourceColumn": "ShipmentDate",
            "formatString": "General Date",
            "displayFolder": "Sales Order Meta"
          },
          {
            "name": "Vehicle Id",
            "dataType": "string",
            "sourceColumn": "VehicleId",
            "displayFolder": "Sales Order Meta"
          },
          {
            "name": "Price List Number",
            "dataType": "string",
            "sourceColumn": "PriceListNumber",
            "displayFolder": "Sales Order Meta"
          },
          {
            "name": "Sales Order Line Status",
            "dataType": "string",
            "sourceColumn": "SalesOrderLineStatus",
            "displayFolder": "Sales Order Meta"
          },
          {
            "name": "Customer Product Description",
            "dataType": "string",
            "sourceColumn": "CustomerProductDescription",
            "displayFolder": "Sales Order Meta"
          },
          {
            "name": "CostPrice",
            "dataType": "double",
            "sourceColumn": "CostPrice",
            "displayFolder": "Sales Order Meta"
          },
          {
            "name": "QtyDeliveredSalesUnit",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "QtyDeliveredSalesUnit"
          },
          {
            "name": "RevenueAmountCurrTrans",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "RevenueAmountCurrTrans"
          },
          {
            "name": "RevenueAmountCurrAcc",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "RevenueAmountCurrAcc"
          },
          {
            "name": "RevenueAmountCurrReg",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "RevenueAmountCurrReg"
          },
          {
            "name": "FreightAmountCurrTrans",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "FreightAmountCurrTrans"
          },
          {
            "name": "FreightAmountCurrAcc",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "FreightAmountCurrAcc"
          },
          {
            "name": "FreightAmountCurrReg",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "FreightAmountCurrReg"
          },
          {
            "name": "VATTaxAmountCurrTrans",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "VATTaxAmountCurrTrans"
          },
          {
            "name": "VATTaxAmountCurrAcc",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "VATTaxAmountCurrAcc"
          },
          {
            "name": "VATTaxAmountCurrReg",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "VATTaxAmountCurrReg"
          },
          {
            "name": "FederalTaxAmountCurrTrans",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "FederalTaxAmountCurrTrans"
          },
          {
            "name": "FederalTaxAmountCurrAcc",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "FederalTaxAmountCurrAcc"
          },
          {
            "name": "FederalTaxAmountCurrReg",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "FederalTaxAmountCurrReg"
          },
          {
            "name": "StateTaxAmountCurrTrans",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "StateTaxAmountCurrTrans"
          },
          {
            "name": "StateTaxAmountCurrAcc",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "StateTaxAmountCurrAcc"
          },
          {
            "name": "StateTaxAmountCurrReg",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "StateTaxAmountCurrReg"
          },
          {
            "name": "CityTaxAmountCurrTrans",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "CityTaxAmountCurrTrans"
          },
          {
            "name": "CityTaxAmountCurrAcc",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "CityTaxAmountCurrAcc"
          },
          {
            "name": "CityTaxAmountCurrReg",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "CityTaxAmountCurrReg"
          },
          {
            "name": "TaxAmountCurrTrans",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "TaxAmountCurrTrans"
          },
          {
            "name": "TaxAmountCurrAcc",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "TaxAmountCurrAcc"
          },
          {
            "name": "TaxAmountCurrReg",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "TaxAmountCurrReg"
          },
          {
            "name": "SalesOrderAmountCurrTrans",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "SalesOrderAmountCurrTrans"
          },
          {
            "name": "SalesOrderAmountCurrAcc",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "SalesOrderAmountCurrAcc"
          },
          {
            "name": "SalesOrderAmountCurrReg",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "SalesOrderAmountCurrReg"
          },
          {
            "name": "NetSalesOrderAmountCurrTrans",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "NetSalesOrderAmountCurrTrans"
          },
          {
            "name": "NetSalesOrderAmountCurrAcc",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "NetSalesOrderAmountCurrAcc"
          },
          {
            "name": "NetSalesOrderAmountCurrReg",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "NetSalesOrderAmountCurrReg"
          },
          {
            "name": "DIM_DataForest_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_DataForest_SKEY"
          },
          {
            "name": "CostOfGoods",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "CostOfGoods"
          },
          {
            "name": "DIM_Customerdeliveryaddress_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_Customerdeliveryaddress_SKEY"
          },
          {
            "name": "DIM_TgkLegalEntity_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_TgkLegalEntity_SKEY"
          },
          {
            "name": "CostOfGoodsCurrReg",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "CostOfGoodsCurrReg"
          },
          {
            "name": "Sales Unit",
            "dataType": "string",
            "sourceColumn": "SalesUnitId",
            "displayFolder": "Sales Order Meta"
          },
          {
            "name": "NetWeight",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "NetWeight"
          },
          {
            "name": "Sales Order Type",
            "dataType": "string",
            "sourceColumn": "SalesOrderType",
            "displayFolder": "Sales Order Meta"
          },
          {
            "name": "Sales Order Type Description",
            "dataType": "string",
            "sourceColumn": "SalesOrderTypeDescription",
            "displayFolder": "Sales Order Meta"
          },
          {
            "name": "QtyInvoicedSalesUnit",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "QtyInvoicedSalesUnit"
          },
          {
            "name": "ReturnedQtyOrderedSalesUnit",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "ReturnedQtyOrderedSalesUnit"
          },
          {
            "name": "DIM_SalesOrderLine_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_SalesOrderLine_SKEY"
          }
        ],
        "partitions": [
          {
            "name": "Sales Orders",
            "source": {
              "query": "SELECT [dbo].[vFactSalesOrders].* FROM [dbo].[vFactSalesOrders] where DIM_DataForest_SKEY like '20%'",
              "dataSource": "sibgrpudmsqlsrvd0001"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT [dbo].[vFactSalesOrders].* FROM [dbo].[vFactSalesOrders] where DIM_DataForest_SKEY like '20%'</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
              }
            ]
          }
        ],
        "measures": [
          {
            "name": "Qty Ordered Sales Unit",
            "expression": "SUM([QtyOrderedSalesUnit])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Order Qty"
          },
          {
            "name": "Qty Ordered Ton",
            "expression": "SUM([QtyTon])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Order Qty"
          },
          {
            "name": "Qty Delivered Sales Unit",
            "expression": "SUM([QtyDeliveredSalesUnit])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Order Qty"
          },
          {
            "name": "Ordered Revenue Amount Curr Trans",
            "expression": "SUM([RevenueAmountCurrTrans])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Order Amount Transactional Currency"
          },
          {
            "name": "Ordered Revenue Amount Curr Acc",
            "expression": "SUM([RevenueAmountCurrAcc])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Order Amount Accounting Currency"
          },
          {
            "name": "Ordered Revenue Amount Curr Reg",
            "expression": "SUM([RevenueAmountCurrReg])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Order Amount Regional Currency"
          },
          {
            "name": "Ordered Freight Amount Curr Trans",
            "expression": "SUM([FreightAmountCurrTrans])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Order Amount Transactional Currency"
          },
          {
            "name": "Ordered Freight Amount Curr Acc",
            "expression": "SUM([FreightAmountCurrAcc])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Order Amount Accounting Currency"
          },
          {
            "name": "Ordered Freight Amount Curr Reg",
            "expression": "SUM([FreightAmountCurrReg])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Order Amount Regional Currency"
          },
          {
            "name": "Ordered VAT Tax Amount Curr Trans",
            "expression": "SUM([VATTaxAmountCurrTrans])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Order Amount Transactional Currency"
          },
          {
            "name": "Ordered VAT Tax Amount Curr Acc",
            "expression": "SUM([VATTaxAmountCurrAcc])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Order Amount Accounting Currency"
          },
          {
            "name": "Ordered VAT Tax Amount Curr Reg",
            "expression": "SUM([VATTaxAmountCurrReg])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Order Amount Regional Currency"
          },
          {
            "name": "Ordered Federal Tax Amount Curr Trans",
            "expression": "SUM([FederalTaxAmountCurrTrans])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Order Amount Transactional Currency"
          },
          {
            "name": "Ordered Federal Tax Amount Curr Acc",
            "expression": "SUM([FederalTaxAmountCurrAcc])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Order Amount Accounting Currency"
          },
          {
            "name": "Ordered Federal Tax Amount Curr Reg",
            "expression": "SUM([FederalTaxAmountCurrReg])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Order Amount Regional Currency"
          },
          {
            "name": "Ordered State Tax Amount Curr Trans",
            "expression": "SUM([StateTaxAmountCurrTrans])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Order Amount Transactional Currency"
          },
          {
            "name": "Ordered State Tax Amount Curr Acc",
            "expression": "SUM([StateTaxAmountCurrAcc])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Order Amount Accounting Currency"
          },
          {
            "name": "Ordered State Tax Amount Curr Reg",
            "expression": "SUM([StateTaxAmountCurrReg])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Order Amount Regional Currency"
          },
          {
            "name": "Ordered City Tax Amount Curr Trans",
            "expression": "SUM([CityTaxAmountCurrTrans])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Order Amount Transactional Currency"
          },
          {
            "name": "Ordered City Tax Amount Curr Acc",
            "expression": "SUM([CityTaxAmountCurrAcc])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Order Amount Accounting Currency"
          },
          {
            "name": "Ordered City Tax Amount Curr Reg",
            "expression": "SUM([CityTaxAmountCurrReg])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Order Amount Regional Currency"
          },
          {
            "name": "Ordered Tax Amount Curr Trans",
            "expression": "SUM([TaxAmountCurrTrans])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Order Amount Transactional Currency"
          },
          {
            "name": "Ordered Tax Amount Curr Acc",
            "expression": "SUM([TaxAmountCurrAcc])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Order Amount Accounting Currency"
          },
          {
            "name": "Ordered Tax Amount Curr Reg",
            "expression": "SUM([TaxAmountCurrReg])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Order Amount Regional Currency"
          },
          {
            "name": "Ordered Sales Amount Curr Trans",
            "expression": "SUM([SalesOrderAmountCurrTrans])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Order Amount Transactional Currency"
          },
          {
            "name": "Ordered Sales Amount Curr Acc",
            "expression": "SUM([SalesOrderAmountCurrAcc])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Order Amount Accounting Currency"
          },
          {
            "name": "Ordered Sales Amount Curr Reg",
            "expression": "SUM([SalesOrderAmountCurrReg])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Order Amount Regional Currency"
          },
          {
            "name": "Ordered Net Sales Amount Curr Trans",
            "expression": "SUM([NetSalesOrderAmountCurrTrans])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Order Amount Transactional Currency"
          },
          {
            "name": "Ordered Net Sales Amount Curr Acc",
            "expression": "SUM([NetSalesOrderAmountCurrAcc])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Order Amount Accounting Currency"
          },
          {
            "name": "Ordered Net Sales Amount Curr Reg",
            "expression": "SUM([NetSalesOrderAmountCurrReg])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Order Amount Regional Currency"
          },
          {
            "name": "Order Pipeline Curr Acc",
            "expression": "calculate(sum('Sales Orders'[SalesOrderAmountCurrAcc]),'Sales Orders'[Sales Order Line Status]=\"Reserved\" || 'Sales Orders'[Sales Order Line Status]=\"Released\"|| 'Sales Orders'[Sales Order Line Status]=\"Picked\"|| 'Sales Orders'[Sales Order Line Status]=\"Partially Delivered\"|| 'Sales Orders'[Sales Order Line Status]=\"Registered/Shipping\" || 'Sales Orders'[Sales Order Line Status]=\"Open\")",
            "formatString": "#,0.00",
            "displayFolder": "Sales Order KPI"
          },
          {
            "name": "Cost Of Goods Ordered Curr Acc",
            "expression": "SUM([CostOfGoods])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Order KPI"
          },
          {
            "name": "Cost of Goods Sold",
            "expression": "calculate(sum('Sales Orders'[CostOfGoods]),'Sales Orders'[Sales Order Line Status]=\"Invoiced/Closed\"||'Sales Orders'[Sales Order Line Status]=\"Shipped/Invoicing\"||'Sales Orders'[Sales Order Line Status]=\"Invoiced/Closed\"||'Sales Orders'[Sales Order Line Status]=\"Invoiced/Closing\")",
            "isHidden": true
          },
          {
            "name": "Contribution per Ton Curr Acc",
            "expression": "DIVIDE(([Ordered Net Sales Amount Curr Acc]-[Cost of Goods Ordered Curr Acc]),[Qty Ordered Ton])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Order KPI"
          },
          {
            "name": "Gross Margin per Ton Curr Acc",
            "expression": "DIVIDE(([Ordered Net Sales Amount Curr Acc]-[Cost of Goods Ordered Curr Acc]),[Qty Ordered Ton])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Order KPI"
          },
          {
            "name": "Gross Margin Pct Curr Acc",
            "expression": "DIVIDE(([Ordered Net Sales Amount Curr Acc]-[Cost Of Goods Ordered Curr Acc]),[Ordered Net Sales Amount Curr Acc])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Order KPI"
          },
          {
            "name": "Ordered Gross Weight",
            "expression": "SUM([GrossWeight])",
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Sales Order Qty"
          },
          {
            "name": "Net Sales Sold",
            "expression": "calculate(sum('Sales Orders'[NetSalesOrderAmountCurrAcc]),'Sales Orders'[Sales Order Line Status]=\"Invoiced/Closed\"||'Sales Orders'[Sales Order Line Status]=\"Shipped/Invoicing\"||'Sales Orders'[Sales Order Line Status]=\"Invoiced/Closed\"||'Sales Orders'[Sales Order Line Status]=\"Invoiced/Closing\")",
            "isHidden": true
          },
          {
            "name": "Order Pipeline Curr Reg",
            "expression": "calculate(sum('Sales Orders'[SalesOrderAmountCurrReg]),'Sales Orders'[Sales Order Line Status]=\"Reserved\" || 'Sales Orders'[Sales Order Line Status]=\"Released\"|| 'Sales Orders'[Sales Order Line Status]=\"Picked\"|| 'Sales Orders'[Sales Order Line Status]=\"Partially Delivered\"|| 'Sales Orders'[Sales Order Line Status]=\"Registered/Shipping\" || 'Sales Orders'[Sales Order Line Status]=\"Open\")",
            "formatString": "#,0.00",
            "displayFolder": "Sales Order KPI"
          },
          {
            "name": "Cost Of Goods Ordered Curr Reg",
            "expression": "SUM([CostOfGoodsCurrReg])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Order KPI"
          },
          {
            "name": "Contribution per Ton Curr Reg",
            "expression": "DIVIDE(([Ordered Net Sales Amount Curr Reg]-[Cost of Goods Ordered Curr Reg]),[Qty Ordered Ton])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Order KPI"
          },
          {
            "name": "Gross Margin per Ton Curr Reg",
            "expression": "DIVIDE(([Ordered Net Sales Amount Curr Reg]-[Cost Of Goods Ordered Curr Reg]),[Qty Ordered Ton])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Order KPI"
          },
          {
            "name": "Gross Margin Pct Curr Reg",
            "expression": "DIVIDE(([Ordered Net Sales Amount Curr Reg]-[Cost Of Goods Ordered Curr Reg]),[Ordered Net Sales Amount Curr Reg])",
            "formatString": "0.00",
            "displayFolder": "Sales Order KPI"
          },
          {
            "name": "Contribution Curr Acc",
            "expression": "([Ordered Net Sales Amount Curr Acc]-[Cost of Goods Ordered Curr Acc])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Order KPI"
          },
          {
            "name": "Contribution Curr Reg",
            "expression": "([Ordered Net Sales Amount Curr Reg]-[Cost of Goods Ordered Curr Reg])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Order KPI"
          },
          {
            "name": "Gross Margin Curr Reg",
            "expression": "[Ordered Net Sales Amount Curr Reg]-[Cost Of Goods Ordered Curr Reg]",
            "formatString": "#,0.00",
            "displayFolder": "Sales Order KPI"
          },
          {
            "name": "Gross Margin Curr Acc",
            "expression": "[Ordered Net Sales Amount Curr Acc]-[Cost Of Goods Ordered Curr Acc]",
            "formatString": "#,0.00",
            "displayFolder": "Sales Order KPI"
          },
          {
            "name": "Ordered Net Weight",
            "expression": "SUM([NetWeight])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Order Qty"
          },
          {
            "name": "Quantity Invoiced Sales Unit",
            "expression": "SUM([QtyInvoicedSalesUnit])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Order Qty"
          },
          {
            "name": "RMA Qty Returned",
            "expression": "SUM([ReturnedQtyOrderedSalesUnit])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Order Qty"
          },
          {
            "name": "Qty Ordered Adjusted Sales Unit",
            "expression": "[Qty Ordered Sales Unit]-[RMA Qty Returned]",
            "formatString": "#,0.00",
            "displayFolder": "Sales Order Qty"
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "vFactSalesOrders"
          },
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": "SELECT [dbo].[vFactSalesOrders].* FROM [dbo].[vFactSalesOrders] where DIM_DataForest_SKEY like '20%'"
          },
          {
            "name": "QueryEditorSerialization",
            "value": "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT [dbo].[vFactSalesOrders].* FROM [dbo].[vFactSalesOrders] where DIM_DataForest_SKEY like '20%'</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
          }
        ]
      },
      {
        "name": "Data Forest",
        "columns": [
          {
            "name": "DIM_DataForest_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_DataForest_SKEY"
          },
          {
            "name": "Region Id",
            "dataType": "string",
            "sourceColumn": "RegionId"
          },
          {
            "name": "Forest Number",
            "dataType": "string",
            "sourceColumn": "ForestNumber"
          },
          {
            "name": "Forest Name",
            "dataType": "string",
            "sourceColumn": "ForestName"
          },
          {
            "name": "Data Forest Id",
            "dataType": "string",
            "sourceColumn": "DataForestId"
          }
        ],
        "partitions": [
          {
            "name": "Data Forest",
            "source": {
              "query": "SELECT [dbo].[vDimDataForest].* FROM [dbo].[vDimDataForest] where DIM_DataForest_SKEY like '20%'",
              "dataSource": "sibgrpudmsqlsrvd0001"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT [dbo].[vDimDataForest].* FROM [dbo].[vDimDataForest] where DIM_DataForest_SKEY like '20%'</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "vDimDataForest"
          },
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": "SELECT [dbo].[vDimDataForest].* FROM [dbo].[vDimDataForest] where DIM_DataForest_SKEY like '20%'"
          },
          {
            "name": "QueryEditorSerialization",
            "value": "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT [dbo].[vDimDataForest].* FROM [dbo].[vDimDataForest] where DIM_DataForest_SKEY like '20%'</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
          }
        ]
      },
      {
        "name": "Customer Delivery Address",
        "columns": [
          {
            "name": "DIM_Customerdeliveryaddress_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_Customerdeliveryaddress_SKEY"
          },
          {
            "name": "Address ID",
            "dataType": "string",
            "sourceColumn": "AddressID"
          },
          {
            "name": "Customer ID",
            "dataType": "string",
            "sourceColumn": "CustomerID"
          },
          {
            "name": "Delivery address",
            "dataType": "string",
            "sourceColumn": "Deliveryaddress"
          },
          {
            "name": "Delivery Address 1",
            "dataType": "string",
            "sourceColumn": "DeliveryAddress1"
          },
          {
            "name": "Delivery Address 2",
            "dataType": "string",
            "sourceColumn": "DeliveryAddress2"
          },
          {
            "name": "Delivery City",
            "dataType": "string",
            "sourceColumn": "DeliveryCity"
          },
          {
            "name": "Delivery Country Description",
            "dataType": "string",
            "sourceColumn": "DeliveryCountryDescription"
          },
          {
            "name": "Delivery Region Name",
            "dataType": "string",
            "sourceColumn": "DeliveryRegionName"
          },
          {
            "name": "Delivery State Code",
            "dataType": "string",
            "sourceColumn": "DeliveryStateCode"
          },
          {
            "name": "Delivery ZIP code",
            "dataType": "string",
            "sourceColumn": "DeliveryZIPcode"
          },
          {
            "name": "Prefered delivery address transportmodus",
            "dataType": "string",
            "sourceColumn": "Prefereddeliveryaddresstransportmodus"
          },
          {
            "name": "Terms of delivery code",
            "dataType": "string",
            "sourceColumn": "Termsofdeliverycode"
          },
          {
            "name": "DIM_DataForest_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_DataForest_SKEY"
          },
          {
            "name": "DIM_ShalePlay_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_ShalePlay_SKEY"
          },
          {
            "name": "Ship Via Code",
            "dataType": "string",
            "sourceColumn": "ShipViaCode"
          },
          {
            "name": "Ship Via Description",
            "dataType": "string",
            "sourceColumn": "ShipViaDescription"
          },
          {
            "name": "Customer Delivery Name",
            "dataType": "string",
            "sourceColumn": "CustomerDeliveryName"
          }
        ],
        "partitions": [
          {
            "name": "Customer Delivery Address",
            "source": {
              "query": "SELECT [dbo].[vDimCustomerdeliveryaddress].* FROM [dbo].[vDimCustomerdeliveryaddress] where DIM_DataForest_SKEY like '20%'",
              "dataSource": "sibgrpudmsqlsrvd0001"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT [dbo].[vDimCustomerdeliveryaddress].* FROM [dbo].[vDimCustomerdeliveryaddress] where DIM_DataForest_SKEY like '20%'</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "vDimCustomerdeliveryaddress"
          },
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": "SELECT [dbo].[vDimCustomerdeliveryaddress].* FROM [dbo].[vDimCustomerdeliveryaddress] where DIM_DataForest_SKEY like '20%'"
          },
          {
            "name": "QueryEditorSerialization",
            "value": "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT [dbo].[vDimCustomerdeliveryaddress].* FROM [dbo].[vDimCustomerdeliveryaddress] where DIM_DataForest_SKEY like '20%'</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
          }
        ]
      },
      {
        "name": "Tagetik Legal Entity",
        "columns": [
          {
            "name": "DIM_TgkLegalEntity_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_TgkLegalEntity_SKEY"
          },
          {
            "name": "Tgk Legal Entity Code",
            "dataType": "string",
            "sourceColumn": "TgkLegalEntityCode"
          },
          {
            "name": "Tgk Legal Entity Name",
            "dataType": "string",
            "sourceColumn": "TgkLegalEntityName"
          }
        ],
        "partitions": [
          {
            "name": "Tagetik Legal Entity",
            "source": {
              "query": "SELECT [grp].[vDimTgkLegalEntity].* FROM [grp].[vDimTgkLegalEntity]",
              "dataSource": "sibgrpudmsqlsrvd0001"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization"
              },
              {
                "name": "TableWidgetSerialization"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "grp"
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "vDimTgkLegalEntity"
          },
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [grp].[vDimTgkLegalEntity].* FROM [grp].[vDimTgkLegalEntity] "
          }
        ]
      },
      {
        "name": "Customer Delivery Address ShalePlay",
        "columns": [
          {
            "name": "DIM_ShalePlay_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_ShalePlay_SKEY"
          },
          {
            "name": "DIM_ShalePlay_BKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_ShalePlay_BKEY"
          },
          {
            "name": "ShalePlay Id",
            "dataType": "string",
            "sourceColumn": "ShalePlayId"
          },
          {
            "name": "County",
            "dataType": "string",
            "sourceColumn": "County"
          },
          {
            "name": "State Code",
            "dataType": "string",
            "sourceColumn": "StateCode"
          },
          {
            "name": "Sales Region Type",
            "dataType": "string",
            "sourceColumn": "SalesRegionType"
          },
          {
            "name": "Shaleplay Level 1",
            "dataType": "string",
            "sourceColumn": "ShaleplayLevel1"
          },
          {
            "name": "Shaleplay Level 2",
            "dataType": "string",
            "sourceColumn": "ShaleplayLevel2"
          },
          {
            "name": "Shaleplay Level 3",
            "dataType": "string",
            "sourceColumn": "ShaleplayLevel3"
          },
          {
            "name": "Last Updated",
            "dataType": "dateTime",
            "sourceColumn": "LastUpdated",
            "formatString": "General Date"
          },
          {
            "name": "CertificateId",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CertificateId"
          },
          {
            "name": "ADFSlice",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "ADFSlice"
          },
          {
            "name": "DataSystemId",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "DataSystemId"
          },
          {
            "name": "CreatedDate",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "CreatedDate",
            "formatString": "General Date"
          },
          {
            "name": "UpdateDate",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "UpdateDate",
            "formatString": "General Date"
          },
          {
            "name": "EffectiveDate",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "EffectiveDate",
            "formatString": "General Date"
          },
          {
            "name": "EndDate",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "EndDate",
            "formatString": "General Date"
          },
          {
            "name": "CurrentIndicator",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CurrentIndicator"
          },
          {
            "name": "ExecutionId",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ExecutionId"
          },
          {
            "name": "DIM_DataForest_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_DataForest_SKEY"
          }
        ],
        "partitions": [
          {
            "name": "Customer ShalePlay",
            "source": {
              "query": "SELECT [dbo].[vDimShalePlay].* FROM [dbo].[vDimShalePlay] where DIM_DataForest_SKEY like '20%'",
              "dataSource": "sibgrpudmsqlsrvd0001"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT [dbo].[vDimShalePlay].* FROM [dbo].[vDimShalePlay] where DIM_DataForest_SKEY like '20%'</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
              }
            ]
          }
        ],
        "hierarchies": [
          {
            "name": "By Customer ShalePlay Hierarchy",
            "levels": [
              {
                "name": "Shaleplay Level 1",
                "ordinal": 0,
                "column": "Shaleplay Level 1"
              },
              {
                "name": "Shaleplay Level 2",
                "ordinal": 1,
                "column": "Shaleplay Level 2"
              },
              {
                "name": "Shaleplay Level 3",
                "ordinal": 2,
                "column": "Shaleplay Level 3"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "vDimShalePlay"
          },
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": "SELECT [dbo].[vDimShalePlay].* FROM [dbo].[vDimShalePlay] where DIM_DataForest_SKEY like '20%'"
          },
          {
            "name": "QueryEditorSerialization",
            "value": "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT [dbo].[vDimShalePlay].* FROM [dbo].[vDimShalePlay] where DIM_DataForest_SKEY like '20%'</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
          }
        ]
      },
      {
        "name": "RMA",
        "columns": [
          {
            "name": "RecId",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "RecId",
            "sourceProviderType": "WChar"
          },
          {
            "name": "DIM_DataForest_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_DataForest_SKEY",
            "sourceProviderType": "WChar"
          },
          {
            "name": "CertificateId",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CertificateId",
            "sourceProviderType": "WChar"
          },
          {
            "name": "DIM_Plant_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_Plant_SKEY",
            "sourceProviderType": "WChar"
          },
          {
            "name": "DIM_SalesOrderLine_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_SalesOrderLine_SKEY",
            "sourceProviderType": "WChar"
          },
          {
            "name": "DIM_DateCompleted_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_DateCompleted_SKEY",
            "sourceProviderType": "WChar"
          },
          {
            "name": "RMA Number",
            "dataType": "string",
            "sourceColumn": "RMANumber",
            "sourceProviderType": "WChar",
            "displayFolder": "RMA Meta"
          },
          {
            "name": "RMA Line Number",
            "dataType": "string",
            "sourceColumn": "RMALineNumber",
            "sourceProviderType": "WChar",
            "displayFolder": "RMA Meta"
          },
          {
            "name": "Return Reason Code",
            "dataType": "string",
            "sourceColumn": "ReturnReasonCode",
            "sourceProviderType": "WChar",
            "displayFolder": "RMA Meta"
          },
          {
            "name": "Return Reason Description",
            "dataType": "string",
            "sourceColumn": "ReturnReasonDescription",
            "sourceProviderType": "WChar",
            "displayFolder": "RMA Meta"
          },
          {
            "name": "Returned Unit Of Measurement",
            "dataType": "string",
            "sourceColumn": "ReturnedUnitOfMeasurement",
            "sourceProviderType": "WChar",
            "displayFolder": "RMA Meta"
          },
          {
            "name": "RMA Corr Invoice Number",
            "dataType": "string",
            "sourceColumn": "RMACorrInvoiceNumber",
            "sourceProviderType": "WChar",
            "displayFolder": "RMA Meta"
          },
          {
            "name": "Sales Order Line Id",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "SalesOrderLineId",
            "sourceProviderType": "WChar",
            "displayFolder": "RMA Meta"
          },
          {
            "name": "RMA Inspection Info",
            "dataType": "string",
            "sourceColumn": "RMAInspectionInfo",
            "displayFolder": "RMA Meta"
          },
          {
            "name": "RMA Status",
            "dataType": "string",
            "sourceColumn": "RMAStatus",
            "displayFolder": "RMA Meta"
          },
          {
            "name": "DIM_LegalEntity_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_LegalEntity_SKEY"
          },
          {
            "name": "DIM_Product_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_Product_SKEY"
          },
          {
            "name": "DIM_Customerdeliveryaddress_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_Customerdeliveryaddress_SKEY"
          },
          {
            "name": "DIM_Customer_Invoice_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_Customer_Invoice_SKEY"
          },
          {
            "name": "DIM_TgkLegalEntity_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_TgkLegalEntity_SKEY"
          },
          {
            "name": "CURR_DIM_GroupSIC_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CURR_DIM_GroupSIC_SKEY"
          },
          {
            "name": "CURR_DIM_GroupSPC_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CURR_DIM_GroupSPC_SKEY"
          },
          {
            "name": "DIM_Currency_Transaction_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_Currency_Transaction_SKEY"
          },
          {
            "name": "DIM_Currency_Accounting_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_Currency_Accounting_SKEY"
          },
          {
            "name": "DIM_Currency_Regional_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_Currency_Regional_SKEY"
          },
          {
            "name": "ReturnedQtyOrderedSalesUnit",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "ReturnedQtyOrderedSalesUnit"
          }
        ],
        "partitions": [
          {
            "name": "RMA",
            "dataView": "full",
            "source": {
              "query": "SELECT [dbo].[vFactRMA].* FROM [dbo].[vFactRMA] where DIM_DataForest_SKEY like '20%'",
              "dataSource": "sibgrpudmsqlsrvd0001"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT [dbo].[vFactRMA].* FROM [dbo].[vFactRMA] where DIM_DataForest_SKEY like '20%'</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
              }
            ]
          }
        ],
        "measures": [
          {
            "name": "RMA Returned Qty Ordered Sales Unit",
            "expression": "SUM([ReturnedQtyOrderedSalesUnit])",
            "formatString": "#,0.00",
            "displayFolder": "RMA Qty"
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": "SELECT [dbo].[vFactRMA].* FROM [dbo].[vFactRMA] where DIM_DataForest_SKEY like '20%'"
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "vFactRMA"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "QueryEditorSerialization",
            "value": "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT [dbo].[vFactRMA].* FROM [dbo].[vFactRMA] where DIM_DataForest_SKEY like '20%'</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
          }
        ]
      },
      {
        "name": "Sales Invoice Bridge",
        "columns": [
          {
            "name": "Invoice Number",
            "dataType": "string",
            "sourceColumn": "InvoiceNumber",
            "sourceProviderType": "WChar"
          },
          {
            "name": "Invoice Line Id",
            "dataType": "string",
            "sourceColumn": "InvoiceLineId",
            "sourceProviderType": "WChar"
          },
          {
            "name": "DIM_DataForest_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_DataForest_SKEY",
            "sourceProviderType": "WChar"
          },
          {
            "name": "DIM_SalesInvoiceLine_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_SalesInvoiceLine_SKEY"
          },
          {
            "name": "DIM_SalesOrderLine_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_SalesOrderLine_SKEY"
          }
        ],
        "partitions": [
          {
            "name": "Sales Invoice Line",
            "dataView": "full",
            "source": {
              "query": "SELECT [dbo].[vDimInvoiceLine].* FROM [dbo].[vDimInvoiceLine] where DIM_DataForest_SKEY like '20%'",
              "dataSource": "sibgrpudmsqlsrvd0001"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT [dbo].[vDimInvoiceLine].* FROM [dbo].[vDimInvoiceLine] where DIM_DataForest_SKEY like '20%'</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": "SELECT [dbo].[vDimInvoiceLine].* FROM [dbo].[vDimInvoiceLine] where DIM_DataForest_SKEY like '20%'"
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "vDimInvoiceLine"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "QueryEditorSerialization",
            "value": "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT [dbo].[vDimInvoiceLine].* FROM [dbo].[vDimInvoiceLine] where DIM_DataForest_SKEY like '20%'</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
          }
        ]
      },
      {
        "name": "Sales Order Bridge",
        "columns": [
          {
            "name": "Sales Order Number",
            "dataType": "string",
            "sourceColumn": "SalesOrderNumber",
            "sourceProviderType": "WChar"
          },
          {
            "name": "Sales Order Line Id",
            "dataType": "string",
            "sourceColumn": "SalesOrderLineId",
            "sourceProviderType": "WChar"
          },
          {
            "name": "DIM_DataForest_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_DataForest_SKEY",
            "sourceProviderType": "WChar"
          },
          {
            "name": "DIM_SalesOrderLine_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_SalesOrderLine_SKEY"
          }
        ],
        "partitions": [
          {
            "name": "Sales Order Line",
            "dataView": "full",
            "source": {
              "query": "SELECT [dbo].[vDimOrderLine].* FROM [dbo].[vDimOrderLine] where DIM_DataForest_SKEY like '20%'",
              "dataSource": "sibgrpudmsqlsrvd0001"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT [dbo].[vDimOrderLine].* FROM [dbo].[vDimOrderLine] where DIM_DataForest_SKEY like '20%'</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": "SELECT [dbo].[vDimOrderLine].* FROM [dbo].[vDimOrderLine] where DIM_DataForest_SKEY like '20%'"
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "vDimOrderLine"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "QueryEditorSerialization",
            "value": "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT [dbo].[vDimOrderLine].* FROM [dbo].[vDimOrderLine] where DIM_DataForest_SKEY like '20%'</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
          }
        ]
      },
      {
        "name": "Customer Hierarchy",
        "columns": [
          {
            "name": "CustomerHierarchyHashKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CustomerHierarchyHashKey",
            "sourceProviderType": "WChar"
          },
          {
            "name": "CustomerHierarchyID",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CustomerHierarchyID",
            "sourceProviderType": "WChar"
          },
          {
            "name": "CustomerNumber",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CustomerNumber",
            "sourceProviderType": "WChar"
          },
          {
            "name": "CustomerHierarchyDescription",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CustomerHierarchyDescription",
            "sourceProviderType": "WChar"
          },
          {
            "name": "ParentDescription",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "ParentDescription",
            "sourceProviderType": "WChar"
          },
          {
            "name": "ParentCode",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "ParentCode",
            "sourceProviderType": "WChar"
          },
          {
            "name": "LevelCode",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "LevelCode",
            "sourceProviderType": "Integer"
          },
          {
            "name": "DIM_DataForest_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_DataForest_SKEY",
            "sourceProviderType": "WChar"
          },
          {
            "type": "calculated",
            "name": "Path",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "PATH('Customer Hierarchy'[CustomerNumber],'Customer Hierarchy'[ParentCode])"
          },
          {
            "type": "calculated",
            "name": "Level 0",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "LOOKUPVALUE('Customer Hierarchy'[Parent],'Customer Hierarchy'[CustomerNumber],PATHITEM([PATH],1,0))"
          },
          {
            "type": "calculated",
            "name": "Level 1",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "IF( ISBLANK(LOOKUPVALUE('Customer Hierarchy'[Parent],'Customer Hierarchy'[CustomerNumber],PATHITEM([PATH],2,0)))=TRUE,LOOKUPVALUE('Customer Hierarchy'[Parent],'Customer Hierarchy'[CustomerNumber],PATHITEM([PATH],1,0)),LOOKUPVALUE('Customer Hierarchy'[Parent],'Customer Hierarchy'[CustomerNumber],PATHITEM([PATH],2,0)) & \" (\" & IF( ISBLANK('Customer Hierarchy'[Level 2 Count])=TRUE,0,'Customer Hierarchy'[Level 2 Count]) & \")\")"
          },
          {
            "type": "calculated",
            "name": "Level 2",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "IF(PATHITEM([PATH],3,0)=\"\",\"\",LOOKUPVALUE('Customer Hierarchy'[Parent],'Customer Hierarchy'[CustomerNumber],PATHITEM([PATH],3,0)) & \" (\" & IF( ISBLANK('Customer Hierarchy'[Level 3 Count])=TRUE,'Customer Hierarchy'[Customer Count],'Customer Hierarchy'[Level 3 Count]) & \")\")"
          },
          {
            "type": "calculated",
            "name": "Level 3",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "IF(PATHITEM([PATH],4,0)=\"\",\"\",LOOKUPVALUE('Customer Hierarchy'[Parent],'Customer Hierarchy'[CustomerNumber],PATHITEM([PATH],4,0)) & \" (\" & IF( ISBLANK('Customer Hierarchy'[Level 4 Count])=TRUE,'Customer Hierarchy'[Customer Count],'Customer Hierarchy'[Level 4 Count]) & \")\")"
          },
          {
            "name": "Parent",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Parent"
          },
          {
            "type": "calculated",
            "name": "Level 2 Count",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "CALCULATE(DISTINCTCOUNT('Customer Hierarchy'[Level2Bis]),FILTER('Customer Hierarchy','Customer Hierarchy'[Level2Bis]<>\"\"),FILTER('Customer Hierarchy','Customer Hierarchy'[Level1Bis]=EARLIER('Customer Hierarchy'[Level1Bis])))"
          },
          {
            "type": "calculated",
            "name": "Level 3 Count",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "CALCULATE(DISTINCTCOUNT('Customer Hierarchy'[Level3Bis]),FILTER('Customer Hierarchy','Customer Hierarchy'[Level3Bis]<>\"\"),FILTER('Customer Hierarchy','Customer Hierarchy'[Level2Bis]=EARLIER('Customer Hierarchy'[Level2Bis])),FILTER('Customer Hierarchy','Customer Hierarchy'[DIM_DataForest_SKEY]=EARLIER('Customer Hierarchy'[DIM_DataForest_SKEY])))"
          },
          {
            "type": "calculated",
            "name": "Level2Bis",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "LOOKUPVALUE('Customer Hierarchy'[Parent],'Customer Hierarchy'[CustomerNumber],PATHITEM([PATH],3,0))"
          },
          {
            "type": "calculated",
            "name": "Level1Bis",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "IF( ISBLANK(LOOKUPVALUE('Customer Hierarchy'[Parent],'Customer Hierarchy'[CustomerNumber],PATHITEM([PATH],2,0)))=TRUE,LOOKUPVALUE('Customer Hierarchy'[Parent],'Customer Hierarchy'[CustomerNumber],PATHITEM([PATH],1,0)),LOOKUPVALUE('Customer Hierarchy'[Parent],'Customer Hierarchy'[CustomerNumber],PATHITEM([PATH],2,0)))"
          },
          {
            "type": "calculated",
            "name": "Level3Bis",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "LOOKUPVALUE('Customer Hierarchy'[Parent],'Customer Hierarchy'[CustomerNumber],PATHITEM([PATH],4,0))"
          },
          {
            "type": "calculated",
            "name": "Customer Count",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "CALCULATE(DISTINCTCOUNT('Customer Hierarchy'[CustomerNumber]),FILTER('Customer Hierarchy','Customer Hierarchy'[Level2Bis]=EARLIER('Customer Hierarchy'[Level2Bis])),FILTER('Customer Hierarchy','Customer Hierarchy'[Level3Bis]=EARLIER('Customer Hierarchy'[Level3Bis])),FILTER('Customer Hierarchy','Customer Hierarchy'[DIM_DataForest_SKEY]=EARLIER('Customer Hierarchy'[DIM_DataForest_SKEY])))"
          },
          {
            "type": "calculated",
            "name": "Level4Bis",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "LOOKUPVALUE('Customer Hierarchy'[Parent],'Customer Hierarchy'[CustomerNumber],PATHITEM([PATH],5,0))"
          },
          {
            "type": "calculated",
            "name": "Level 4 Count",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "CALCULATE(DISTINCTCOUNT('Customer Hierarchy'[Level4Bis]),FILTER('Customer Hierarchy','Customer Hierarchy'[Level4Bis]<>\"\"),FILTER('Customer Hierarchy','Customer Hierarchy'[Level3Bis]=EARLIER('Customer Hierarchy'[Level3Bis])),FILTER('Customer Hierarchy','Customer Hierarchy'[DIM_DataForest_SKEY]=EARLIER('Customer Hierarchy'[DIM_DataForest_SKEY])))"
          },
          {
            "type": "calculated",
            "name": "Level 4",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "IF(PATHITEM([PATH],5,0)=\"\",\"\",LOOKUPVALUE('Customer Hierarchy'[Parent],'Customer Hierarchy'[CustomerNumber],PATHITEM([PATH],5,0))& \" (\" & 'Customer Hierarchy'[Customer Count]  & \")\")"
          }
        ],
        "partitions": [
          {
            "name": "Customer Hierarchy",
            "dataView": "full",
            "source": {
              "query": "SELECT [dbo].[vDimCustomerHierarchy].* FROM [dbo].[vDimCustomerHierarchy] where DIM_DataForest_SKEY like '20%' or  DIM_DataForest_SKEY ='*'",
              "dataSource": "sibgrpudmsqlsrvd0001"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT [dbo].[vDimCustomerHierarchy].* FROM [dbo].[vDimCustomerHierarchy] where DIM_DataForest_SKEY like '20%' or  DIM_DataForest_SKEY ='*'</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
              }
            ]
          }
        ],
        "hierarchies": [
          {
            "name": "Customer Hierarchy",
            "levels": [
              {
                "name": "Level 0",
                "ordinal": 0,
                "column": "Level 0"
              },
              {
                "name": "Level 1",
                "ordinal": 1,
                "column": "Level 1"
              },
              {
                "name": "Level 2",
                "ordinal": 2,
                "column": "Level 2"
              },
              {
                "name": "Level 3",
                "ordinal": 3,
                "column": "Level 3"
              },
              {
                "name": "Level 4",
                "ordinal": 4,
                "column": "Level 4"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": "SELECT [dbo].[vDimCustomerHierarchy].* FROM [dbo].[vDimCustomerHierarchy] where DIM_DataForest_SKEY like '20%' or  DIM_DataForest_SKEY ='*'"
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "vDimCustomerHierarchy"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "QueryEditorSerialization",
            "value": "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT [dbo].[vDimCustomerHierarchy].* FROM [dbo].[vDimCustomerHierarchy] where DIM_DataForest_SKEY like '20%' or  DIM_DataForest_SKEY ='*'</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
          }
        ]
      },
      {
        "name": "Sales Costs",
        "columns": [
          {
            "name": "RecId",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "RecId",
            "sourceProviderType": "WChar"
          },
          {
            "name": "DIM_DataForest_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_DataForest_SKEY",
            "sourceProviderType": "WChar"
          },
          {
            "name": "DIM_SalesInvoiceLine_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_SalesInvoiceLine_SKEY",
            "sourceProviderType": "WChar"
          },
          {
            "name": "DIM_LegalEntity_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_LegalEntity_SKEY",
            "sourceProviderType": "WChar"
          },
          {
            "name": "DIM_TgkLegalEntity_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_TgkLegalEntity_SKEY",
            "sourceProviderType": "Char"
          },
          {
            "name": "DIM_Plant_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_Plant_SKEY",
            "sourceProviderType": "WChar"
          },
          {
            "name": "DIM_Date_Invoice_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_Date_Invoice_SKEY",
            "sourceProviderType": "WChar"
          },
          {
            "name": "DIM_Currency_Accounting_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_Currency_Accounting_SKEY",
            "sourceProviderType": "WChar"
          },
          {
            "name": "DIM_Customer_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_Customer_SKEY",
            "sourceProviderType": "WChar"
          },
          {
            "name": "Bill To Customer Number",
            "dataType": "string",
            "sourceColumn": "BillToCustomerNumber",
            "sourceProviderType": "WChar",
            "displayFolder": "Sales Cost Meta"
          },
          {
            "name": "Bill To Sales Man",
            "dataType": "string",
            "sourceColumn": "BillToSalesMan",
            "sourceProviderType": "WChar",
            "displayFolder": "Sales Cost Meta"
          },
          {
            "name": "FreightCostCurrAcc",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "FreightCostCurrAcc",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "FreightRevenueCurrAcc",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "FreightRevenueCurrAcc",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "GrossRevenueCurrAcc",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "GrossRevenueCurrAcc",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "InternalFreightCostCurrAcc",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "InternalFreightCostCurrAcc",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "MiscChargeCostCurrAcc",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "MiscChargeCostCurrAcc",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "MiscChargeRevenueCurrAcc",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "MiscChargeRevenueCurrAcc",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "NetSalesCurrAcc",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "NetSalesCurrAcc",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "ProductCostCurrAcc",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "ProductCostCurrAcc",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "TaxCurrAcc",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "TaxCurrAcc",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "TerminalCostCurrAcc",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "TerminalCostCurrAcc",
            "sourceProviderType": "Numeric"
          },
          {
            "name": "Last Updated",
            "dataType": "string",
            "sourceColumn": "LastUpdated",
            "sourceProviderType": "WChar",
            "displayFolder": "Sales Cost Meta"
          },
          {
            "name": "DIM_Product_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_Product_SKEY"
          },
          {
            "name": "DIM_Currency_Transaction_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_Currency_Transaction_SKEY"
          },
          {
            "name": "DIM_Currency_Regional_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_Currency_Regional_SKEY"
          },
          {
            "name": "DIM_Customerdeliveryaddress_SKEY",
            "dataType": "string",
            "sourceColumn": "DIM_Customerdeliveryaddress_SKEY"
          },
          {
            "name": "CURR_DIM_GroupSIC_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CURR_DIM_GroupSIC_SKEY"
          },
          {
            "name": "CURR_DIM_GroupSPC_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CURR_DIM_GroupSPC_SKEY"
          },
          {
            "name": "AllocationVarianceCurrAcc",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "AllocationVarianceCurrAcc"
          },
          {
            "name": "DepreciationCurrAcc",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "DepreciationCurrAcc"
          },
          {
            "name": "GrossMarginCurrAcc",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "GrossMarginCurrAcc"
          },
          {
            "name": "LeaseCostCurrAcc",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "LeaseCostCurrAcc"
          },
          {
            "name": "ProductRevenueCurrAcc",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "ProductRevenueCurrAcc"
          },
          {
            "name": "RebateAmtCurrAcc",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "RebateAmtCurrAcc"
          },
          {
            "name": "TotalCostCurrAcc",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "TotalCostCurrAcc"
          },
          {
            "name": "TotalRevenueCurrAcc",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "TotalRevenueCurrAcc"
          },
          {
            "name": "FreightCostCurrReg",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "FreightCostCurrReg"
          },
          {
            "name": "FreightRevenueCurrReg",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "FreightRevenueCurrReg"
          },
          {
            "name": "GrossRevenueCurrReg",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "GrossRevenueCurrReg"
          },
          {
            "name": "InternalFreightCostCurrReg",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "InternalFreightCostCurrReg"
          },
          {
            "name": "MiscChargeCostCurrReg",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "MiscChargeCostCurrReg"
          },
          {
            "name": "MiscChargeRevenueCurrReg",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "MiscChargeRevenueCurrReg"
          },
          {
            "name": "NetSalesCurrReg",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "NetSalesCurrReg"
          },
          {
            "name": "ProductCostCurrReg",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "ProductCostCurrReg"
          },
          {
            "name": "TaxCurrReg",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "TaxCurrReg"
          },
          {
            "name": "TerminalCostCurrReg",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "TerminalCostCurrReg"
          },
          {
            "name": "AllocationVarianceCurrReg",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "AllocationVarianceCurrReg"
          },
          {
            "name": "DepreciationCurrReg",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "DepreciationCurrReg"
          },
          {
            "name": "GrossMarginCurrReg",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "GrossMarginCurrReg"
          },
          {
            "name": "LeaseCostCurrReg",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "LeaseCostCurrReg"
          },
          {
            "name": "ProductRevenueCurrReg",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "ProductRevenueCurrReg"
          },
          {
            "name": "RebateAmtCurrReg",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "RebateAmtCurrReg"
          },
          {
            "name": "TotalCostCurrReg",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "TotalCostCurrReg"
          },
          {
            "name": "TotalRevenueCurrReg",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "TotalRevenueCurrReg"
          },
          {
            "name": "ShortTons",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "ShortTons"
          },
          {
            "name": "ChargeFlag",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "ChargeFlag"
          },
          {
            "name": "ChargeGroup",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "ChargeGroup"
          },
          {
            "name": "Product Id",
            "dataType": "string",
            "sourceColumn": "ProductId"
          },
          {
            "name": "Plant Code",
            "dataType": "string",
            "sourceColumn": "PlantCode"
          },
          {
            "name": "ExchangeRate",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "ExchangeRate"
          },
          {
            "name": "Customer Number",
            "dataType": "string",
            "sourceColumn": "CustomerNumber"
          },
          {
            "name": "Legal Entity Code",
            "dataType": "string",
            "sourceColumn": "LegalEntityCode"
          }
        ],
        "partitions": [
          {
            "name": "Sales Costs",
            "dataView": "full",
            "source": {
              "query": "SELECT [dbo].[vFactSalesCost].* FROM [dbo].[vFactSalesCost] where DIM_DataForest_SKEY like '20%'",
              "dataSource": "sibgrpudmsqlsrvd0001"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT [dbo].[vFactSalesCost].* FROM [dbo].[vFactSalesCost] where DIM_DataForest_SKEY like '20%'</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
              }
            ]
          }
        ],
        "measures": [
          {
            "name": "Freight Cost Curr Acc",
            "expression": "SUM([FreightCostCurrAcc])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Cost Accounting Currency"
          },
          {
            "name": "Freight Revenue Curr Acc",
            "expression": "SUM([FreightRevenueCurrAcc])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Cost Accounting Currency"
          },
          {
            "name": "Gross Revenue Curr Acc",
            "expression": "SUM([GrossRevenueCurrAcc])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Cost Accounting Currency"
          },
          {
            "name": "Internal Freight Cost Curr Acc",
            "expression": "SUM([InternalFreightCostCurrAcc])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Cost Accounting Currency"
          },
          {
            "name": "Misc Charge Cost Curr Acc",
            "expression": "SUM([MiscChargeCostCurrAcc])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Cost Accounting Currency"
          },
          {
            "name": "Misc Charge Revenue Curr Acc",
            "expression": "SUM([MiscChargeRevenueCurrAcc])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Cost Accounting Currency"
          },
          {
            "name": "Net Sales Curr Acc",
            "expression": "SUM([NetSalesCurrAcc])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Cost Accounting Currency"
          },
          {
            "name": "Product Cost Curr Acc",
            "expression": "SUM([ProductCostCurrAcc])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Cost Accounting Currency"
          },
          {
            "name": "Tax Curr Acc",
            "expression": "SUM([TaxCurrAcc])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Cost Accounting Currency"
          },
          {
            "name": "Terminal Cost Curr Acc",
            "expression": "SUM([TerminalCostCurrAcc])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Cost Accounting Currency"
          },
          {
            "name": "Allocation Variance Curr Acc",
            "expression": "SUM([AllocationVarianceCurrAcc])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Cost Accounting Currency"
          },
          {
            "name": "Depreciation Curr Acc",
            "expression": "SUM([DepreciationCurrAcc])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Cost Accounting Currency"
          },
          {
            "name": "Reg Gross Margin Curr Acc",
            "expression": "SUM([GrossMarginCurrAcc])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Cost Accounting Currency"
          },
          {
            "name": "Lease Cost Curr Acc",
            "expression": "SUM([LeaseCostCurrAcc])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Cost Accounting Currency"
          },
          {
            "name": "Product Revenue Curr Acc",
            "expression": "SUM([ProductRevenueCurrAcc])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Cost Accounting Currency"
          },
          {
            "name": "Rebate Amt Curr Acc",
            "expression": "SUM([RebateAmtCurrAcc])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Cost Accounting Currency"
          },
          {
            "name": "Total Cost Curr Acc",
            "expression": "SUM([TotalCostCurrAcc])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Cost Accounting Currency"
          },
          {
            "name": "Total Revenue Curr Acc",
            "expression": "SUM([TotalRevenueCurrAcc])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Cost Accounting Currency"
          },
          {
            "name": "Freight Cost Curr Reg",
            "expression": "SUM([FreightCostCurrReg])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Cost Regional Currency"
          },
          {
            "name": "Freight Revenue Curr Reg",
            "expression": "SUM([FreightRevenueCurrReg])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Cost Regional Currency"
          },
          {
            "name": "Gross Revenue Curr Reg",
            "expression": "SUM([GrossRevenueCurrReg])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Cost Regional Currency"
          },
          {
            "name": "Internal Freight Cost Curr Reg",
            "expression": "SUM([InternalFreightCostCurrReg])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Cost Regional Currency"
          },
          {
            "name": "Misc Charge Cost Curr Reg",
            "expression": "SUM([MiscChargeCostCurrReg])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Cost Regional Currency"
          },
          {
            "name": "Misc Charge Revenue Curr Reg",
            "expression": "SUM([MiscChargeRevenueCurrReg])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Cost Regional Currency"
          },
          {
            "name": "Net Sales Curr Reg",
            "expression": "SUM([NetSalesCurrReg])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Cost Regional Currency"
          },
          {
            "name": "Product Cost Curr Reg",
            "expression": "SUM([ProductCostCurrReg])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Cost Regional Currency"
          },
          {
            "name": "Tax Curr Reg",
            "expression": "SUM([TaxCurrReg])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Cost Regional Currency"
          },
          {
            "name": "Terminal Cost Curr Reg",
            "expression": "SUM([TerminalCostCurrReg])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Cost Regional Currency"
          },
          {
            "name": "Allocation Variance Curr Reg",
            "expression": "SUM([AllocationVarianceCurrReg])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Cost Regional Currency"
          },
          {
            "name": "Depreciation Curr Reg",
            "expression": "SUM([DepreciationCurrReg])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Cost Regional Currency"
          },
          {
            "name": "Reg Gross Margin Curr Reg",
            "expression": "SUM([GrossMarginCurrReg])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Cost Regional Currency"
          },
          {
            "name": "Lease Cost Curr Reg",
            "expression": "SUM([LeaseCostCurrReg])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Cost Regional Currency"
          },
          {
            "name": "Product Revenue Curr Reg",
            "expression": "SUM([ProductRevenueCurrReg])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Cost Regional Currency"
          },
          {
            "name": "Rebate Amt Curr Reg",
            "expression": "SUM([RebateAmtCurrReg])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Cost Regional Currency"
          },
          {
            "name": "Total Cost Curr Reg",
            "expression": "SUM([TotalCostCurrReg])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Cost Regional Currency"
          },
          {
            "name": "Total Revenue Curr Reg",
            "expression": "SUM([TotalRevenueCurrReg])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Cost Regional Currency"
          },
          {
            "name": "Previous Month - Freight Cost Curr Acc",
            "expression": "CALCULATE([Freight Cost Curr Acc],PREVIOUSMONTH('Date'[Date]))",
            "isHidden": true
          },
          {
            "name": "Previous Month - Freight Revenue Curr Acc",
            "expression": "CALCULATE([Freight Revenue Curr Acc],PREVIOUSMONTH('Date'[Date]))",
            "isHidden": true
          },
          {
            "name": "Previous Month - Gross Revenue Curr Acc",
            "expression": "CALCULATE([Gross Revenue Curr Acc],PREVIOUSMONTH('Date'[Date]))",
            "isHidden": true
          },
          {
            "name": "Previous Month - Internal Freight Cost Curr Acc",
            "expression": "CALCULATE([Internal Freight Cost Curr Acc],PREVIOUSMONTH('Date'[Date]))",
            "isHidden": true
          },
          {
            "name": "Previous Month - Misc Charge Cost Curr Acc",
            "expression": "CALCULATE([Misc Charge Cost Curr Acc],PREVIOUSMONTH('Date'[Date]))",
            "isHidden": true
          },
          {
            "name": "Previous Month - Misc Charge Revenue Curr Acc",
            "expression": "CALCULATE([Misc Charge Revenue Curr Acc],PREVIOUSMONTH('Date'[Date]))",
            "isHidden": true
          },
          {
            "name": "Previous Month - Net Sales Curr Acc",
            "expression": "CALCULATE([Net Sales Curr Acc],PREVIOUSMONTH('Date'[Date]))",
            "isHidden": true
          },
          {
            "name": "Previous Month - Product Cost Curr Acc",
            "expression": "CALCULATE([Product Cost Curr Acc],PREVIOUSMONTH('Date'[Date]))",
            "isHidden": true
          },
          {
            "name": "Previous Month - Tax Curr Acc",
            "expression": "CALCULATE([Tax Curr Acc],PREVIOUSMONTH('Date'[Date]))",
            "isHidden": true
          },
          {
            "name": "Previous Month - Terminal Cost Curr Acc",
            "expression": "CALCULATE([Terminal Cost Curr Acc],PREVIOUSMONTH('Date'[Date]))",
            "isHidden": true
          },
          {
            "name": "Previous Month - Allocation Variance Curr Acc",
            "expression": "CALCULATE([Allocation Variance Curr Acc],PREVIOUSMONTH('Date'[Date]))",
            "isHidden": true
          },
          {
            "name": "Previous Month - Depreciation Curr Acc",
            "expression": "CALCULATE([Depreciation Curr Acc],PREVIOUSMONTH('Date'[Date]))",
            "isHidden": true
          },
          {
            "name": "Previous Month - Reg Gross Margin Curr Acc",
            "expression": "CALCULATE([Reg Gross Margin Curr Acc],PREVIOUSMONTH('Date'[Date]))",
            "isHidden": true
          },
          {
            "name": "Previous Month - Lease Cost Curr Acc",
            "expression": "CALCULATE([Lease Cost Curr Acc],PREVIOUSMONTH('Date'[Date]))",
            "isHidden": true
          },
          {
            "name": "Previous Month - Product Revenue Curr Acc",
            "expression": "CALCULATE([Product Revenue Curr Acc],PREVIOUSMONTH('Date'[Date]))",
            "isHidden": true
          },
          {
            "name": "Previous Month - Rebate Amt Curr Acc",
            "expression": "CALCULATE([Rebate Amt Curr Acc],PREVIOUSMONTH('Date'[Date]))",
            "isHidden": true
          },
          {
            "name": "Previous Month - Total Cost Curr Acc",
            "expression": "CALCULATE([Total Cost Curr Acc],PREVIOUSMONTH('Date'[Date]))",
            "isHidden": true
          },
          {
            "name": "Previous Month - Total Revenue Curr Acc",
            "expression": "CALCULATE([Total Revenue Curr Acc],PREVIOUSMONTH('Date'[Date]))",
            "isHidden": true
          },
          {
            "name": "Previous Month - Freight Cost Curr Reg",
            "expression": "CALCULATE([Freight Cost Curr Reg],PREVIOUSMONTH('Date'[Date]))",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Previous Month"
          },
          {
            "name": "Previous Month - Freight Revenue Curr Reg",
            "expression": "CALCULATE([Freight Revenue Curr Reg],PREVIOUSMONTH('Date'[Date]))",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Previous Month"
          },
          {
            "name": "Previous Month - Gross Revenue Curr Reg",
            "expression": "CALCULATE([Gross Revenue Curr Reg],PREVIOUSMONTH('Date'[Date]))",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Previous Month"
          },
          {
            "name": "Previous Month - Internal Freight Cost Curr Reg",
            "expression": "CALCULATE([Internal Freight Cost Curr Reg],PREVIOUSMONTH('Date'[Date]))",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Previous Month"
          },
          {
            "name": "Previous Month - Misc Charge Cost Curr Reg",
            "expression": "CALCULATE([Misc Charge Cost Curr Reg],PREVIOUSMONTH('Date'[Date]))",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Previous Month"
          },
          {
            "name": "Previous Month - Misc Charge Revenue Curr Reg",
            "expression": "CALCULATE([Misc Charge Revenue Curr Reg],PREVIOUSMONTH('Date'[Date]))",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Previous Month"
          },
          {
            "name": "Previous Month - Net Sales Curr Reg",
            "expression": "CALCULATE([Net Sales Curr Reg],PREVIOUSMONTH('Date'[Date]))",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Previous Month"
          },
          {
            "name": "Previous Month - Product Cost Curr Reg",
            "expression": "CALCULATE([Product Cost Curr Reg],PREVIOUSMONTH('Date'[Date]))",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Previous Month"
          },
          {
            "name": "Previous Month - Tax Curr Reg",
            "expression": "CALCULATE([Tax Curr Reg],PREVIOUSMONTH('Date'[Date]))",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Previous Month"
          },
          {
            "name": "Previous Month - Terminal Cost Curr Reg",
            "expression": "CALCULATE([Terminal Cost Curr Reg],PREVIOUSMONTH('Date'[Date]))",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Previous Month"
          },
          {
            "name": "Previous Month - Allocation Variance Curr Reg",
            "expression": "CALCULATE([Allocation Variance Curr Reg],PREVIOUSMONTH('Date'[Date]))",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Previous Month"
          },
          {
            "name": "Previous Month - Depreciation Curr Reg",
            "expression": "CALCULATE([Depreciation Curr Reg],PREVIOUSMONTH('Date'[Date]))",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Previous Month"
          },
          {
            "name": "Previous Month - Reg Gross Margin Curr Reg",
            "expression": "CALCULATE([Reg Gross Margin Curr Reg],PREVIOUSMONTH('Date'[Date]))",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Previous Month"
          },
          {
            "name": "Previous Month - Lease Cost Curr Reg",
            "expression": "CALCULATE([Lease Cost Curr Reg],PREVIOUSMONTH('Date'[Date]))",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Previous Month"
          },
          {
            "name": "Previous Month - Product Revenue Curr Reg",
            "expression": "CALCULATE([Product Revenue Curr Reg],PREVIOUSMONTH('Date'[Date]))",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Previous Month"
          },
          {
            "name": "Previous Month - Rebate Amt Curr Reg",
            "expression": "CALCULATE([Rebate Amt Curr Reg],PREVIOUSMONTH('Date'[Date]))",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Previous Month"
          },
          {
            "name": "Previous Month - Total Cost Curr Reg",
            "expression": "CALCULATE([Total Cost Curr Reg],PREVIOUSMONTH('Date'[Date]))",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Previous Month"
          },
          {
            "name": "Previous Month - Total Revenue Curr Reg",
            "expression": "CALCULATE([Total Revenue Curr Reg],PREVIOUSMONTH('Date'[Date]))",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Previous Month"
          },
          {
            "name": "RS Tons",
            "expression": "SUM([ShortTons])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Cost Tonnage"
          },
          {
            "name": "Previous Month - RS Tons",
            "expression": "CALCULATE([RS Tons],PREVIOUSMONTH('Date'[Date]))",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Previous Month"
          },
          {
            "name": "Freight Cost Curr Acc - Growth Month",
            "expression": "[Freight Cost Curr Acc]-[Previous Month - Freight Cost Curr Acc]",
            "isHidden": true
          },
          {
            "name": "Freight Revenue Curr Acc - Growth Month",
            "expression": "[Freight Revenue Curr Acc]-[Previous Month - Freight Revenue Curr Acc]",
            "isHidden": true
          },
          {
            "name": "Gross Revenue Curr Acc - Growth Month",
            "expression": "[Gross Revenue Curr Acc]-[Previous Month - Gross Revenue Curr Acc]",
            "isHidden": true
          },
          {
            "name": "Internal Freight Cost Curr Acc - Growth Month",
            "expression": "[Internal Freight Cost Curr Acc]-[Previous Month - Internal Freight Cost Curr Acc]",
            "isHidden": true
          },
          {
            "name": "Misc Charge Cost Curr Acc - Growth Month",
            "expression": "[Misc Charge Cost Curr Acc]-[Previous Month - Misc Charge Cost Curr Acc]",
            "isHidden": true
          },
          {
            "name": "Misc Charge Revenue Curr Acc - Growth Month",
            "expression": "[Misc Charge Revenue Curr Acc]-[Previous Month - Misc Charge Revenue Curr Acc]",
            "isHidden": true
          },
          {
            "name": "Net Sales Curr Acc - Growth Month",
            "expression": "[Net Sales Curr Acc]-[Previous Month - Net Sales Curr Acc]",
            "isHidden": true
          },
          {
            "name": "Product Cost Curr Acc - Growth Month",
            "expression": "[Product Cost Curr Acc]-[Previous Month - Product Cost Curr Acc]",
            "isHidden": true
          },
          {
            "name": "Tax Curr Acc - Growth Month",
            "expression": "[Tax Curr Acc]-[Previous Month - Tax Curr Acc]",
            "isHidden": true
          },
          {
            "name": "Terminal Cost Curr Acc - Growth Month",
            "expression": "[Terminal Cost Curr Acc]-[Previous Month - Terminal Cost Curr Acc]",
            "isHidden": true
          },
          {
            "name": "RS Tons - Growth Month",
            "expression": "[RS Tons]-[Previous Month - RS Tons]",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Previous Month"
          },
          {
            "name": "RS Tons - Growth Month %",
            "expression": "IF(ISBLANK([Previous Month - RS Tons])=TRUE,BLANK(),DIVIDE([RS Tons],[Previous Month - RS Tons])-1)",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Time Intelligence - Previous Month"
          },
          {
            "name": "Year To Date - RS Tons",
            "expression": "TOTALYTD([RS Tons],'Date'[Date])  ",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Year To Date Last Year - RS Tons",
            "expression": "CALCULATE([Year To Date - RS Tons],SAMEPERIODLASTYEAR('Date'[Date]))",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "RS Tons - Growth YTD",
            "expression": "[Year To Date - RS Tons]-[Year To Date Last Year - RS Tons]",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "RS Tons - Growth YTD %",
            "expression": "IF(ISBLANK([Year To Date Last Year - RS Tons])=TRUE,BLANK(),DIVIDE([Year To Date - RS Tons],[Year To Date Last Year - RS Tons])-1)",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Product Revenue Curr Reg - Growth Month",
            "expression": "[Product Revenue Curr Reg]-[Previous Month - Product Revenue Curr Reg]",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Previous Month"
          },
          {
            "name": "Product Revenue Curr Reg - Growth Month %",
            "expression": "IF(ISBLANK([Previous Month - Product Revenue Curr Reg])=TRUE,BLANK(),DIVIDE([Product Revenue Curr Reg],[Previous Month - Product Revenue Curr Reg])-1)",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Time Intelligence - Previous Month"
          },
          {
            "name": "Year To Date - Product Revenue Curr Reg",
            "expression": "TOTALYTD([Product Revenue Curr Reg],'Date'[Date])  ",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Year To Date Last Year - Product Revenue Curr Reg",
            "expression": "CALCULATE([Year To Date - Product Revenue Curr Reg],SAMEPERIODLASTYEAR('Date'[Date]))",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Product Revenue Curr Reg - Growth YTD",
            "expression": "[Year To Date - Product Revenue Curr Reg]-[Year To Date Last Year - Product Revenue Curr Reg]",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Product Revenue Curr Reg - Growth YTD %",
            "expression": "IF(ISBLANK([Year To Date Last Year - Product Revenue Curr Reg])=TRUE,BLANK(),DIVIDE([Year To Date - Product Revenue Curr Reg],[Year To Date Last Year - Product Revenue Curr Reg])-1)",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Total Revenue Per Ton Curr Reg",
            "expression": "DIVIDE(SUM('Sales Costs'[TotalRevenueCurrAcc]),[RS Tons])",
            "formatString": "#,0.00"
          },
          {
            "name": "Previous Month - Total Revenue Per Ton Curr Reg",
            "expression": "CALCULATE([Total Revenue Per Ton Curr Reg],PREVIOUSMONTH('Date'[Date]))",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Previous Month"
          },
          {
            "name": "Total Revenue Per Ton Curr Reg - Growth Month",
            "expression": "[Total Revenue Per Ton Curr Reg]-[Previous Month - Total Revenue Per Ton Curr Reg]",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Previous Month"
          },
          {
            "name": "Total Revenue Per Ton Curr Reg - Growth Month %",
            "expression": "IF(ISBLANK([Previous Month - Total Revenue Per Ton Curr Reg])=TRUE,BLANK(),DIVIDE([Total Revenue Per Ton Curr Reg],[Previous Month - Total Revenue Per Ton Curr Reg])-1)",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Time Intelligence - Previous Month"
          },
          {
            "name": "Year To Date - Total Revenue Per Ton Curr Reg",
            "expression": "TOTALYTD([Total Revenue Per Ton Curr Reg],'Date'[Date])  ",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Year To Date Last Year - Total Revenue Per Ton Curr Reg",
            "expression": "CALCULATE([Year To Date - Total Revenue Per Ton Curr Reg],SAMEPERIODLASTYEAR('Date'[Date]))",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Total Revenue Per Ton Curr Reg - Growth YTD",
            "expression": "[Year To Date - Total Revenue Per Ton Curr Reg]-[Year To Date Last Year - Total Revenue Per Ton Curr Reg]",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Total Revenue Per Ton Curr Reg - Growth YTD %",
            "expression": "IF(ISBLANK([Year To Date Last Year - Total Revenue Per Ton Curr Reg])=TRUE,BLANK(),DIVIDE([Year To Date - Total Revenue Per Ton Curr Reg],[Year To Date Last Year - Total Revenue Per Ton Curr Reg])-1)",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Total Revenue Curr Reg - Growth Month",
            "expression": "[Total Revenue Curr Reg]-[Previous Month - Total Revenue Curr Reg]",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Previous Month"
          },
          {
            "name": "Total Revenue Curr Reg - Growth Month %",
            "expression": "IF(ISBLANK([Previous Month - Total Revenue Curr Reg])=TRUE,BLANK(),DIVIDE([Total Revenue Curr Reg],[Previous Month - Total Revenue Curr Reg])-1)",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Time Intelligence - Previous Month"
          },
          {
            "name": "Year To Date - Total Revenue Curr Reg",
            "expression": "TOTALYTD([Total Revenue Curr Reg],'Date'[Date])  ",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Year To Date Last Year - Total Revenue Curr Reg",
            "expression": "CALCULATE([Year To Date - Total Revenue Curr Reg],SAMEPERIODLASTYEAR('Date'[Date]))",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Total Revenue Curr Reg - Growth YTD",
            "expression": "[Year To Date - Total Revenue Curr Reg]-[Year To Date Last Year - Total Revenue Curr Reg]",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Total Revenue Curr Reg - Growth YTD %",
            "expression": "IF(ISBLANK([Year To Date Last Year - Total Revenue Curr Reg])=TRUE,BLANK(),DIVIDE([Year To Date - Total Revenue Curr Reg],[Year To Date Last Year - Total Revenue Curr Reg])-1)",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Total Cost Curr Reg - Growth Month",
            "expression": "[Total Cost Curr Reg]-[Previous Month - Total Cost Curr Reg]",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Previous Month"
          },
          {
            "name": "Total Cost Curr Reg - Growth Month %",
            "expression": "IF(ISBLANK([Previous Month - Total Cost Curr Reg])=TRUE,BLANK(),DIVIDE([Total Cost Curr Reg],[Previous Month - Total Cost Curr Reg])-1)",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Time Intelligence - Previous Month"
          },
          {
            "name": "Year To Date - Total Cost Curr Reg",
            "expression": "TOTALYTD([Total Cost Curr Reg],'Date'[Date])  ",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Year To Date Last Year - Total Cost Curr Reg",
            "expression": "CALCULATE([Year To Date - Total Cost Curr Reg],SAMEPERIODLASTYEAR('Date'[Date]))",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Total Cost Curr Reg - Growth YTD",
            "expression": "[Year To Date - Total Cost Curr Reg]-[Year To Date Last Year - Total Cost Curr Reg]",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Total Cost Curr Reg - Growth YTD %",
            "expression": "IF(ISBLANK([Year To Date Last Year - Total Cost Curr Reg])=TRUE,BLANK(),DIVIDE([Year To Date - Total Cost Curr Reg],[Year To Date Last Year - Total Cost Curr Reg])-1)",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Rebate Amt Curr Reg - Growth Month",
            "expression": "[Rebate Amt Curr Reg]-[Previous Month - Rebate Amt Curr Reg]",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Previous Month"
          },
          {
            "name": "Rebate Amt Curr Reg - Growth Month %",
            "expression": "IF(ISBLANK([Previous Month - Rebate Amt Curr Reg])=TRUE,BLANK(),DIVIDE([Rebate Amt Curr Reg],[Previous Month - Rebate Amt Curr Reg])-1)",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Time Intelligence - Previous Month"
          },
          {
            "name": "Year To Date - Rebate Amt Curr Reg",
            "expression": "TOTALYTD([Rebate Amt Curr Reg],'Date'[Date])  ",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Year To Date Last Year - Rebate Amt Curr Reg",
            "expression": "CALCULATE([Year To Date - Rebate Amt Curr Reg],SAMEPERIODLASTYEAR('Date'[Date]))",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Rebate Amt Curr Reg - Growth YTD",
            "expression": "[Year To Date - Rebate Amt Curr Reg]-[Year To Date Last Year - Rebate Amt Curr Reg]",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Rebate Amt Curr Reg - Growth YTD %",
            "expression": "IF(ISBLANK([Year To Date Last Year - Rebate Amt Curr Reg])=TRUE,BLANK(),DIVIDE([Year To Date - Rebate Amt Curr Reg],[Year To Date Last Year - Rebate Amt Curr Reg])-1)",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Lease Cost Curr Reg - Growth Month",
            "expression": "[Lease Cost Curr Reg]-[Previous Month - Lease Cost Curr Reg]",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Previous Month"
          },
          {
            "name": "Lease Cost Curr Reg - Growth Month %",
            "expression": "IF(ISBLANK([Previous Month - Lease Cost Curr Reg])=TRUE,BLANK(),DIVIDE([Lease Cost Curr Reg],[Previous Month - Lease Cost Curr Reg])-1)",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Time Intelligence - Previous Month"
          },
          {
            "name": "Year To Date - Lease Cost Curr Reg",
            "expression": "TOTALYTD([Lease Cost Curr Reg],'Date'[Date])  ",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Year To Date Last Year - Lease Cost Curr Reg",
            "expression": "CALCULATE([Year To Date - Lease Cost Curr Reg],SAMEPERIODLASTYEAR('Date'[Date]))",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Lease Cost Curr Reg - Growth YTD",
            "expression": "[Year To Date - Lease Cost Curr Reg]-[Year To Date Last Year - Lease Cost Curr Reg]",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Lease Cost Curr Reg - Growth YTD %",
            "expression": "IF(ISBLANK([Year To Date Last Year - Lease Cost Curr Reg])=TRUE,BLANK(),DIVIDE([Year To Date - Lease Cost Curr Reg],[Year To Date Last Year - Lease Cost Curr Reg])-1)",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Reg Gross Margin Curr Reg - Growth Month",
            "expression": "[Reg Gross Margin Curr Reg]-[Previous Month - Reg Gross Margin Curr Reg]",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Previous Month"
          },
          {
            "name": "Reg Gross Margin Curr Reg - Growth Month %",
            "expression": "IF(ISBLANK([Previous Month - Reg Gross Margin Curr Reg])=TRUE,BLANK(),DIVIDE([Reg Gross Margin Curr Reg],[Previous Month - Reg Gross Margin Curr Reg])-1)",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Time Intelligence - Previous Month"
          },
          {
            "name": "Year To Date - Reg Gross Margin Curr Reg",
            "expression": "TOTALYTD([Reg Gross Margin Curr Reg],'Date'[Date])  ",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Year To Date Last Year - Reg Gross Margin Curr Reg",
            "expression": "CALCULATE([Year To Date - Reg Gross Margin Curr Reg],SAMEPERIODLASTYEAR('Date'[Date]))",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Reg Gross Margin Curr Reg - Growth YTD",
            "expression": "[Year To Date - Reg Gross Margin Curr Reg]-[Year To Date Last Year - Reg Gross Margin Curr Reg]",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Reg Gross Margin Curr Reg - Growth YTD %",
            "expression": "IF(ISBLANK([Year To Date Last Year - Reg Gross Margin Curr Reg])=TRUE,BLANK(),DIVIDE([Year To Date - Reg Gross Margin Curr Reg],[Year To Date Last Year - Reg Gross Margin Curr Reg])-1)",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Depreciation Curr Reg - Growth Month",
            "expression": "[Depreciation Curr Reg]-[Previous Month - Depreciation Curr Reg]",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Previous Month"
          },
          {
            "name": "Depreciation Curr Reg - Growth Month %",
            "expression": "IF(ISBLANK([Previous Month - Depreciation Curr Reg])=TRUE,BLANK(),DIVIDE([Depreciation Curr Reg],[Previous Month - Depreciation Curr Reg])-1)",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Time Intelligence - Previous Month"
          },
          {
            "name": "Year To Date - Depreciation Curr Reg",
            "expression": "TOTALYTD([Depreciation Curr Reg],'Date'[Date])  ",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Year To Date Last Year - Depreciation Curr Reg",
            "expression": "CALCULATE([Year To Date - Depreciation Curr Reg],SAMEPERIODLASTYEAR('Date'[Date]))",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Depreciation Curr Reg - Growth YTD",
            "expression": "[Year To Date - Depreciation Curr Reg]-[Year To Date Last Year - Depreciation Curr Reg]",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Depreciation Curr Reg - Growth YTD %",
            "expression": "IF(ISBLANK([Year To Date Last Year - Depreciation Curr Reg])=TRUE,BLANK(),DIVIDE([Year To Date - Depreciation Curr Reg],[Year To Date Last Year - Depreciation Curr Reg])-1)",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Allocation Variance Curr Reg - Growth Month",
            "expression": "[Allocation Variance Curr Reg]-[Previous Month - Allocation Variance Curr Reg]",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Previous Month"
          },
          {
            "name": "Allocation Variance Curr Reg - Growth Month %",
            "expression": "IF(ISBLANK([Previous Month - Allocation Variance Curr Reg])=TRUE,BLANK(),DIVIDE([Allocation Variance Curr Reg],[Previous Month - Allocation Variance Curr Reg])-1)",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Time Intelligence - Previous Month"
          },
          {
            "name": "Year To Date - Allocation Variance Curr Reg",
            "expression": "TOTALYTD([Allocation Variance Curr Reg],'Date'[Date])  ",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Year To Date Last Year - Allocation Variance Curr Reg",
            "expression": "CALCULATE([Year To Date - Allocation Variance Curr Reg],SAMEPERIODLASTYEAR('Date'[Date]))",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Allocation Variance Curr Reg - Growth YTD",
            "expression": "[Year To Date - Allocation Variance Curr Reg]-[Year To Date Last Year - Allocation Variance Curr Reg]",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Allocation Variance Curr Reg - Growth YTD %",
            "expression": "IF(ISBLANK([Year To Date Last Year - Allocation Variance Curr Reg])=TRUE,BLANK(),DIVIDE([Year To Date - Allocation Variance Curr Reg],[Year To Date Last Year - Allocation Variance Curr Reg])-1)",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Terminal Cost Curr Reg - Growth Month",
            "expression": "[Terminal Cost Curr Reg]-[Previous Month - Terminal Cost Curr Reg]",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Previous Month"
          },
          {
            "name": "Terminal Cost Curr Reg - Growth Month %",
            "expression": "IF(ISBLANK([Previous Month - Terminal Cost Curr Reg])=TRUE,BLANK(),DIVIDE([Terminal Cost Curr Reg],[Previous Month - Terminal Cost Curr Reg])-1)",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Time Intelligence - Previous Month"
          },
          {
            "name": "Year To Date - Terminal Cost Curr Reg",
            "expression": "TOTALYTD([Terminal Cost Curr Reg],'Date'[Date])  ",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Year To Date Last Year - Terminal Cost Curr Reg",
            "expression": "CALCULATE([Year To Date - Terminal Cost Curr Reg],SAMEPERIODLASTYEAR('Date'[Date]))",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Terminal Cost Curr Reg - Growth YTD",
            "expression": "[Year To Date - Terminal Cost Curr Reg]-[Year To Date Last Year - Terminal Cost Curr Reg]",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Terminal Cost Curr Reg - Growth YTD %",
            "expression": "IF(ISBLANK([Year To Date Last Year - Terminal Cost Curr Reg])=TRUE,BLANK(),DIVIDE([Year To Date - Terminal Cost Curr Reg],[Year To Date Last Year - Terminal Cost Curr Reg])-1)",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Tax Curr Reg - Growth Month",
            "expression": "[Tax Curr Reg]-[Previous Month - Tax Curr Reg]",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Previous Month"
          },
          {
            "name": "Tax Curr Reg - Growth Month %",
            "expression": "IF(ISBLANK([Previous Month - Tax Curr Reg])=TRUE,BLANK(),DIVIDE([Tax Curr Reg],[Previous Month - Tax Curr Reg])-1)",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Time Intelligence - Previous Month"
          },
          {
            "name": "Year To Date - Tax Curr Reg",
            "expression": "TOTALYTD([Tax Curr Reg],'Date'[Date])  ",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Year To Date Last Year - Tax Curr Reg",
            "expression": "CALCULATE([Year To Date - Tax Curr Reg],SAMEPERIODLASTYEAR('Date'[Date]))",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Tax Curr Reg - Growth YTD",
            "expression": "[Year To Date - Tax Curr Reg]-[Year To Date Last Year - Tax Curr Reg]",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Tax Curr Reg - Growth YTD %",
            "expression": "IF(ISBLANK([Year To Date Last Year - Tax Curr Reg])=TRUE,BLANK(),DIVIDE([Year To Date - Tax Curr Reg],[Year To Date Last Year - Tax Curr Reg])-1)",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Product Cost Curr Reg - Growth Month",
            "expression": "[Product Cost Curr Reg]-[Previous Month - Product Cost Curr Reg]",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Previous Month"
          },
          {
            "name": "Product Cost Curr Reg - Growth Month %",
            "expression": "IF(ISBLANK([Previous Month - Product Cost Curr Reg])=TRUE,BLANK(),DIVIDE([Product Cost Curr Reg],[Previous Month - Product Cost Curr Reg])-1)",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Time Intelligence - Previous Month"
          },
          {
            "name": "Year To Date - Product Cost Curr Reg",
            "expression": "TOTALYTD([Product Cost Curr Reg],'Date'[Date])  ",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Year To Date Last Year - Product Cost Curr Reg",
            "expression": "CALCULATE([Year To Date - Product Cost Curr Reg],SAMEPERIODLASTYEAR('Date'[Date]))",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Product Cost Curr Reg - Growth YTD",
            "expression": "[Year To Date - Product Cost Curr Reg]-[Year To Date Last Year - Product Cost Curr Reg]",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Product Cost Curr Reg - Growth YTD %",
            "expression": "IF(ISBLANK([Year To Date Last Year - Product Cost Curr Reg])=TRUE,BLANK(),DIVIDE([Year To Date - Product Cost Curr Reg],[Year To Date Last Year - Product Cost Curr Reg])-1)",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Net Sales Curr Reg - Growth Month",
            "expression": "[Net Sales Curr Reg]-[Previous Month - Net Sales Curr Reg]",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Previous Month"
          },
          {
            "name": "Net Sales Curr Reg - Growth Month %",
            "expression": "IF(ISBLANK([Previous Month - Net Sales Curr Reg])=TRUE,BLANK(),DIVIDE([Net Sales Curr Reg],[Previous Month - Net Sales Curr Reg])-1)",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Time Intelligence - Previous Month"
          },
          {
            "name": "Year To Date - Net Sales Curr Reg",
            "expression": "TOTALYTD([Net Sales Curr Reg],'Date'[Date])  ",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Year To Date Last Year - Net Sales Curr Reg",
            "expression": "CALCULATE([Year To Date - Net Sales Curr Reg],SAMEPERIODLASTYEAR('Date'[Date]))",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Net Sales Curr Reg - Growth YTD",
            "expression": "[Year To Date - Net Sales Curr Reg]-[Year To Date Last Year - Net Sales Curr Reg]",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Net Sales Curr Reg - Growth YTD %",
            "expression": "IF(ISBLANK([Year To Date Last Year - Net Sales Curr Reg])=TRUE,BLANK(),DIVIDE([Year To Date - Net Sales Curr Reg],[Year To Date Last Year - Net Sales Curr Reg])-1)",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Misc Charge Revenue Curr Reg - Growth Month",
            "expression": "[Misc Charge Revenue Curr Reg]-[Previous Month - Misc Charge Revenue Curr Reg]",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Previous Month"
          },
          {
            "name": "Misc Charge Revenue Curr Reg - Growth Month %",
            "expression": "IF(ISBLANK([Previous Month - Misc Charge Revenue Curr Reg])=TRUE,BLANK(),DIVIDE([Misc Charge Revenue Curr Reg],[Previous Month - Misc Charge Revenue Curr Reg])-1)",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Time Intelligence - Previous Month"
          },
          {
            "name": "Year To Date - Misc Charge Revenue Curr Reg",
            "expression": "TOTALYTD([Misc Charge Revenue Curr Reg],'Date'[Date])  ",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Year To Date Last Year - Misc Charge Revenue Curr Reg",
            "expression": "CALCULATE([Year To Date - Misc Charge Revenue Curr Reg],SAMEPERIODLASTYEAR('Date'[Date]))",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Misc Charge Revenue Curr Reg - Growth YTD",
            "expression": "[Year To Date - Misc Charge Revenue Curr Reg]-[Year To Date Last Year - Misc Charge Revenue Curr Reg]",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Misc Charge Revenue Curr Reg - Growth YTD %",
            "expression": "IF(ISBLANK([Year To Date Last Year - Misc Charge Revenue Curr Reg])=TRUE,BLANK(),DIVIDE([Year To Date - Misc Charge Revenue Curr Reg],[Year To Date Last Year - Misc Charge Revenue Curr Reg])-1)",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Misc Charge Cost Curr Reg - Growth Month",
            "expression": "[Misc Charge Cost Curr Reg]-[Previous Month - Misc Charge Cost Curr Reg]",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Previous Month"
          },
          {
            "name": "Misc Charge Cost Curr Reg - Growth Month %",
            "expression": "IF(ISBLANK([Previous Month - Misc Charge Cost Curr Reg])=TRUE,BLANK(),DIVIDE([Misc Charge Cost Curr Reg],[Previous Month - Misc Charge Cost Curr Reg])-1)",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Time Intelligence - Previous Month"
          },
          {
            "name": "Year To Date - Misc Charge Cost Curr Reg",
            "expression": "TOTALYTD([Misc Charge Cost Curr Reg],'Date'[Date])  ",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Year To Date Last Year - Misc Charge Cost Curr Reg",
            "expression": "CALCULATE([Year To Date - Misc Charge Cost Curr Reg],SAMEPERIODLASTYEAR('Date'[Date]))",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Misc Charge Cost Curr Reg - Growth YTD",
            "expression": "[Year To Date - Misc Charge Cost Curr Reg]-[Year To Date Last Year - Misc Charge Cost Curr Reg]",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Misc Charge Cost Curr Reg - Growth YTD %",
            "expression": "IF(ISBLANK([Year To Date Last Year - Misc Charge Cost Curr Reg])=TRUE,BLANK(),DIVIDE([Year To Date - Misc Charge Cost Curr Reg],[Year To Date Last Year - Misc Charge Cost Curr Reg])-1)",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Internal Freight Cost Curr Reg - Growth Month",
            "expression": "[Internal Freight Cost Curr Reg]-[Previous Month - Internal Freight Cost Curr Reg]",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Previous Month"
          },
          {
            "name": "Internal Freight Cost Curr Reg - Growth Month %",
            "expression": "IF(ISBLANK([Previous Month - Internal Freight Cost Curr Reg])=TRUE,BLANK(),DIVIDE([Internal Freight Cost Curr Reg],[Previous Month - Internal Freight Cost Curr Reg])-1)",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Time Intelligence - Previous Month"
          },
          {
            "name": "Year To Date - Internal Freight Cost Curr Reg",
            "expression": "TOTALYTD([Internal Freight Cost Curr Reg],'Date'[Date])  ",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Year To Date Last Year - Internal Freight Cost Curr Reg",
            "expression": "CALCULATE([Year To Date - Internal Freight Cost Curr Reg],SAMEPERIODLASTYEAR('Date'[Date]))",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Internal Freight Cost Curr Reg - Growth YTD",
            "expression": "[Year To Date - Internal Freight Cost Curr Reg]-[Year To Date Last Year - Internal Freight Cost Curr Reg]",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Internal Freight Cost Curr Reg - Growth YTD %",
            "expression": "IF(ISBLANK([Year To Date Last Year - Internal Freight Cost Curr Reg])=TRUE,BLANK(),DIVIDE([Year To Date - Internal Freight Cost Curr Reg],[Year To Date Last Year - Internal Freight Cost Curr Reg])-1)",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Gross Revenue Curr Reg - Growth Month",
            "expression": "[Gross Revenue Curr Reg]-[Previous Month - Gross Revenue Curr Reg]",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Previous Month"
          },
          {
            "name": "Gross Revenue Curr Reg - Growth Month %",
            "expression": "IF(ISBLANK([Previous Month - Gross Revenue Curr Reg])=TRUE,BLANK(),DIVIDE([Gross Revenue Curr Reg],[Previous Month - Gross Revenue Curr Reg])-1)",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Time Intelligence - Previous Month"
          },
          {
            "name": "Year To Date - Gross Revenue Curr Reg",
            "expression": "TOTALYTD([Gross Revenue Curr Reg],'Date'[Date])  ",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Year To Date Last Year - Gross Revenue Curr Reg",
            "expression": "CALCULATE([Year To Date - Gross Revenue Curr Reg],SAMEPERIODLASTYEAR('Date'[Date]))",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Gross Revenue Curr Reg - Growth YTD",
            "expression": "[Year To Date - Gross Revenue Curr Reg]-[Year To Date Last Year - Gross Revenue Curr Reg]",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Gross Revenue Curr Reg - Growth YTD %",
            "expression": "IF(ISBLANK([Year To Date Last Year - Gross Revenue Curr Reg])=TRUE,BLANK(),DIVIDE([Year To Date - Gross Revenue Curr Reg],[Year To Date Last Year - Gross Revenue Curr Reg])-1)",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Freight Revenue Curr Reg - Growth Month",
            "expression": "[Freight Revenue Curr Reg]-[Previous Month - Freight Revenue Curr Reg]",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Previous Month"
          },
          {
            "name": "Freight Revenue Curr Reg - Growth Month %",
            "expression": "IF(ISBLANK([Previous Month - Freight Revenue Curr Reg])=TRUE,BLANK(),DIVIDE([Freight Revenue Curr Reg],[Previous Month - Freight Revenue Curr Reg])-1)",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Time Intelligence - Previous Month"
          },
          {
            "name": "Year To Date - Freight Revenue Curr Reg",
            "expression": "TOTALYTD([Freight Revenue Curr Reg],'Date'[Date])  ",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Year To Date Last Year - Freight Revenue Curr Reg",
            "expression": "CALCULATE([Year To Date - Freight Revenue Curr Reg],SAMEPERIODLASTYEAR('Date'[Date]))",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Freight Revenue Curr Reg - Growth YTD",
            "expression": "[Year To Date - Freight Revenue Curr Reg]-[Year To Date Last Year - Freight Revenue Curr Reg]",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Freight Revenue Curr Reg - Growth YTD %",
            "expression": "IF(ISBLANK([Year To Date Last Year - Freight Revenue Curr Reg])=TRUE,BLANK(),DIVIDE([Year To Date - Freight Revenue Curr Reg],[Year To Date Last Year - Freight Revenue Curr Reg])-1)",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Freight Cost Curr Reg - Growth Month",
            "expression": "[Freight Cost Curr Reg]-[Previous Month - Freight Cost Curr Reg]",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Previous Month"
          },
          {
            "name": "Freight Cost Curr Reg - Growth Month %",
            "expression": "IF(ISBLANK([Previous Month - Freight Cost Curr Reg])=TRUE,BLANK(),DIVIDE([Freight Cost Curr Reg],[Previous Month - Freight Cost Curr Reg])-1)",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Time Intelligence - Previous Month"
          },
          {
            "name": "Year To Date - Freight Cost Curr Reg",
            "expression": "TOTALYTD([Freight Cost Curr Reg],'Date'[Date])  ",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Year To Date Last Year - Freight Cost Curr Reg",
            "expression": "CALCULATE([Year To Date - Freight Cost Curr Reg],SAMEPERIODLASTYEAR('Date'[Date]))",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Freight Cost Curr Reg - Growth YTD",
            "expression": "[Year To Date - Freight Cost Curr Reg]-[Year To Date Last Year - Freight Cost Curr Reg]",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence - Year To Date"
          },
          {
            "name": "Freight Cost Curr Reg - Growth YTD %",
            "expression": "IF(ISBLANK([Year To Date Last Year - Freight Cost Curr Reg])=TRUE,BLANK(),DIVIDE([Year To Date - Freight Cost Curr Reg],[Year To Date Last Year - Freight Cost Curr Reg])-1)",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Time Intelligence - Year To Date"
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": "SELECT [dbo].[vFactSalesCost].* FROM [dbo].[vFactSalesCost] where DIM_DataForest_SKEY like '20%'"
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "vFactSalesCost"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "QueryEditorSerialization",
            "value": "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT [dbo].[vFactSalesCost].* FROM [dbo].[vFactSalesCost] where DIM_DataForest_SKEY like '20%'</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
          }
        ]
      },
      {
        "name": "Sales Forecasts",
        "columns": [
          {
            "name": "DIM_Currency_Accounting_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_Currency_Accounting_SKEY",
            "sourceProviderType": "Char"
          },
          {
            "name": "DIM_Currency_Transaction_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_Currency_Transaction_SKEY",
            "sourceProviderType": "Char"
          },
          {
            "name": "DIM_Currency_Regional_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_Currency_Regional_SKEY",
            "sourceProviderType": "Char"
          },
          {
            "name": "DIM_Date_Period_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_Date_Period_SKEY",
            "sourceProviderType": "Char"
          },
          {
            "name": "DIM_LegalEntity_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_LegalEntity_SKEY",
            "sourceProviderType": "Char"
          },
          {
            "name": "DIM_TgkLegalEntity_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_TgkLegalEntity_SKEY",
            "sourceProviderType": "Char"
          },
          {
            "name": "DIM_Plant_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_Plant_SKEY",
            "sourceProviderType": "Char"
          },
          {
            "name": "DIM_Customer_Invoice_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_Customer_Invoice_SKEY",
            "sourceProviderType": "Char"
          },
          {
            "name": "DIM_Product_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_Product_SKEY",
            "sourceProviderType": "Char"
          },
          {
            "name": "CURR_DIM_GroupSIC_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CURR_DIM_GroupSIC_SKEY",
            "sourceProviderType": "Char"
          },
          {
            "name": "CURR_DIM_GroupSPC_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CURR_DIM_GroupSPC_SKEY",
            "sourceProviderType": "Char"
          },
          {
            "name": "DIM_Customerdeliveryaddress_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_Customerdeliveryaddress_SKEY",
            "sourceProviderType": "Char"
          },
          {
            "name": "RevenueCurrReg",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "RevenueCurrReg",
            "sourceProviderType": "Double"
          },
          {
            "name": "MetricTons",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "MetricTons"
          },
          {
            "name": "ShortTons",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "ShortTons"
          }
        ],
        "partitions": [
          {
            "name": "Sales Forecasts",
            "dataView": "full",
            "source": {
              "query": " SELECT [dbo].[vFactSalesForecasts].* FROM [dbo].[vFactSalesForecasts] ",
              "dataSource": "sibgrpudmsqlsrvd0001"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
                  "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
                  "  <ColumnSuggestedType />",
                  "  <ColumnFormat />",
                  "  <ColumnAccuracy />",
                  "  <ColumnCurrencySymbol />",
                  "  <ColumnPositivePattern />",
                  "  <ColumnNegativePattern />",
                  "  <ColumnWidths>",
                  "    <item>",
                  "      <key>",
                  "        <string>DIM_Currency_Accounting_SKEY</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>241</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DIM_Currency_Transaction_SKEY</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>243</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DIM_Currency_Regional_SKEY</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>223</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DIM_Date_Period_SKEY</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>182</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DIM_LegalEntity_SKEY</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>174</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DIM_TgkLegalEntity_SKEY</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>197</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DIM_Plant_SKEY</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>137</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DIM_Customer_Invoice_SKEY</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>219</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DIM_Product_SKEY</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>156</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>CURR_DIM_GroupSIC_SKEY</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>210</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>CURR_DIM_GroupSPC_SKEY</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>214</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DIM_Customerdeliveryaddress_SKEY</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>261</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>RevenueCurrReg</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>140</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>MetricTons</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>101</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>ShortTons</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>99</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnWidths>",
                  "  <ColumnDisplayIndex>",
                  "    <item>",
                  "      <key>",
                  "        <string>DIM_Currency_Accounting_SKEY</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>0</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DIM_Currency_Transaction_SKEY</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>1</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DIM_Currency_Regional_SKEY</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>2</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DIM_Date_Period_SKEY</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>3</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DIM_LegalEntity_SKEY</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>4</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DIM_TgkLegalEntity_SKEY</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>5</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DIM_Plant_SKEY</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>6</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DIM_Customer_Invoice_SKEY</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>7</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DIM_Product_SKEY</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>8</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>CURR_DIM_GroupSIC_SKEY</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>9</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>CURR_DIM_GroupSPC_SKEY</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>10</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DIM_Customerdeliveryaddress_SKEY</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>11</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>RevenueCurrReg</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>12</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>MetricTons</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>13</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>ShortTons</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>14</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnDisplayIndex>",
                  "  <ColumnFrozen />",
                  "  <ColumnChecked>",
                  "    <item>",
                  "      <key>",
                  "        <string>MetricTons</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>ShortTons</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnChecked>",
                  "  <ColumnFilter />",
                  "  <SelectionFilter />",
                  "  <FilterParameters />",
                  "  <IsSortDescending>false</IsSortDescending>",
                  "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "measures": [
          {
            "name": "Forecast Revenue Amount Curr Reg",
            "expression": "SUM([RevenueCurrReg])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Forecast Amount Regional Currency"
          },
          {
            "name": "Forecast Metric Tons",
            "expression": "SUM([MetricTons])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Forecast Tonnage"
          },
          {
            "name": "Forecast Short Tons",
            "expression": "SUM([ShortTons])",
            "formatString": "#,0.00",
            "displayFolder": "Sales Forecast Tonnage"
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[vFactSalesForecasts].* FROM [dbo].[vFactSalesForecasts] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "vFactSalesForecasts"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "TableWidgetSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
              "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
              "  <ColumnSuggestedType />",
              "  <ColumnFormat />",
              "  <ColumnAccuracy />",
              "  <ColumnCurrencySymbol />",
              "  <ColumnPositivePattern />",
              "  <ColumnNegativePattern />",
              "  <ColumnWidths>",
              "    <item>",
              "      <key>",
              "        <string>DIM_Currency_Accounting_SKEY</string>",
              "      </key>",
              "      <value>",
              "        <int>241</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DIM_Currency_Transaction_SKEY</string>",
              "      </key>",
              "      <value>",
              "        <int>243</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DIM_Currency_Regional_SKEY</string>",
              "      </key>",
              "      <value>",
              "        <int>223</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DIM_Date_Period_SKEY</string>",
              "      </key>",
              "      <value>",
              "        <int>182</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DIM_LegalEntity_SKEY</string>",
              "      </key>",
              "      <value>",
              "        <int>174</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DIM_TgkLegalEntity_SKEY</string>",
              "      </key>",
              "      <value>",
              "        <int>197</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DIM_Plant_SKEY</string>",
              "      </key>",
              "      <value>",
              "        <int>137</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DIM_Customer_Invoice_SKEY</string>",
              "      </key>",
              "      <value>",
              "        <int>219</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DIM_Product_SKEY</string>",
              "      </key>",
              "      <value>",
              "        <int>156</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>CURR_DIM_GroupSIC_SKEY</string>",
              "      </key>",
              "      <value>",
              "        <int>210</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>CURR_DIM_GroupSPC_SKEY</string>",
              "      </key>",
              "      <value>",
              "        <int>214</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DIM_Customerdeliveryaddress_SKEY</string>",
              "      </key>",
              "      <value>",
              "        <int>261</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>RevenueCurrReg</string>",
              "      </key>",
              "      <value>",
              "        <int>140</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>MetricTons</string>",
              "      </key>",
              "      <value>",
              "        <int>101</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>ShortTons</string>",
              "      </key>",
              "      <value>",
              "        <int>99</int>",
              "      </value>",
              "    </item>",
              "  </ColumnWidths>",
              "  <ColumnDisplayIndex>",
              "    <item>",
              "      <key>",
              "        <string>DIM_Currency_Accounting_SKEY</string>",
              "      </key>",
              "      <value>",
              "        <int>0</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DIM_Currency_Transaction_SKEY</string>",
              "      </key>",
              "      <value>",
              "        <int>1</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DIM_Currency_Regional_SKEY</string>",
              "      </key>",
              "      <value>",
              "        <int>2</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DIM_Date_Period_SKEY</string>",
              "      </key>",
              "      <value>",
              "        <int>3</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DIM_LegalEntity_SKEY</string>",
              "      </key>",
              "      <value>",
              "        <int>4</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DIM_TgkLegalEntity_SKEY</string>",
              "      </key>",
              "      <value>",
              "        <int>5</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DIM_Plant_SKEY</string>",
              "      </key>",
              "      <value>",
              "        <int>6</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DIM_Customer_Invoice_SKEY</string>",
              "      </key>",
              "      <value>",
              "        <int>7</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DIM_Product_SKEY</string>",
              "      </key>",
              "      <value>",
              "        <int>8</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>CURR_DIM_GroupSIC_SKEY</string>",
              "      </key>",
              "      <value>",
              "        <int>9</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>CURR_DIM_GroupSPC_SKEY</string>",
              "      </key>",
              "      <value>",
              "        <int>10</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DIM_Customerdeliveryaddress_SKEY</string>",
              "      </key>",
              "      <value>",
              "        <int>11</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>RevenueCurrReg</string>",
              "      </key>",
              "      <value>",
              "        <int>12</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>MetricTons</string>",
              "      </key>",
              "      <value>",
              "        <int>13</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>ShortTons</string>",
              "      </key>",
              "      <value>",
              "        <int>14</int>",
              "      </value>",
              "    </item>",
              "  </ColumnDisplayIndex>",
              "  <ColumnFrozen />",
              "  <ColumnChecked>",
              "    <item>",
              "      <key>",
              "        <string>MetricTons</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>ShortTons</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "  </ColumnChecked>",
              "  <ColumnFilter />",
              "  <SelectionFilter />",
              "  <FilterParameters />",
              "  <IsSortDescending>false</IsSortDescending>",
              "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "Benchmark",
        "columns": [
          {
            "name": "Benchmark",
            "dataType": "string",
            "sourceColumn": "Benchmark",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Benchmark",
            "dataView": "full",
            "source": {
              "query": " SELECT [dbo].[vDimBenchmark].* FROM [dbo].[vDimBenchmark] ",
              "dataSource": "sibgrpudmsqlsrvd0001"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[vDimBenchmark].* FROM [dbo].[vDimBenchmark] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "vDimBenchmark"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "Date Range",
        "isHidden": true,
        "columns": [
          {
            "name": "DIM_Date_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_Date_SKEY",
            "sourceProviderType": "WChar"
          },
          {
            "name": "Date Range",
            "dataType": "string",
            "sourceColumn": "DateRange",
            "sourceProviderType": "Char"
          },
          {
            "name": "Date",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "Date",
            "formatString": "General Date",
            "sourceProviderType": "DBTimeStamp"
          },
          {
            "name": "DateRangeLY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DateRangeLY",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Date Range",
            "dataView": "full",
            "source": {
              "query": " SELECT [dbo].[vDimDateRange].* FROM [dbo].[vDimDateRange] ",
              "dataSource": "sibgrpudmsqlsrvd0001"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[vDimDateRange].* FROM [dbo].[vDimDateRange] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "vDimDateRange"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "Date Range Bis",
        "columns": [
          {
            "name": "DateRange",
            "dataType": "string",
            "sourceColumn": "DateRange",
            "sourceProviderType": "Char"
          },
          {
            "name": "AxisValue",
            "dataType": "string",
            "sourceColumn": "AxisValue",
            "sortByColumn": "SortColumn",
            "sourceProviderType": "WChar"
          },
          {
            "name": "SortColumn",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "SortColumn",
            "sourceProviderType": "WChar"
          },
          {
            "name": "DIM_Date_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_Date_SKEY",
            "sourceProviderType": "WChar"
          }
        ],
        "partitions": [
          {
            "name": "Date Range Bis",
            "dataView": "full",
            "source": {
              "query": " SELECT [dbo].[vDimDateRangeBis].* FROM [dbo].[vDimDateRangeBis] ",
              "dataSource": "sibgrpudmsqlsrvd0001"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[vDimDateRangeBis].* FROM [dbo].[vDimDateRangeBis] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "vDimDateRangeBis"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "34e4ea7c-5613-4369-b370-53685c4c325e",
        "fromTable": "Sales Invoices",
        "fromColumn": "DIM_LegalEntity_SKEY",
        "toTable": "Legal Entity",
        "toColumn": "DIM_LegalEntity_SKEY"
      },
      {
        "name": "a7355b20-a23c-4202-ac34-74a2a0ad73ce",
        "fromTable": "Sales Invoices",
        "fromColumn": "DIM_Plant_SKEY",
        "toTable": "Plant",
        "toColumn": "DIM_Plant_SKEY"
      },
      {
        "name": "e5043e8f-c4b7-487b-aa92-9ba8906f5f04",
        "fromTable": "Sales Invoices",
        "fromColumn": "DIM_Date_Invoice_SKEY",
        "toTable": "Date",
        "toColumn": "DIM_Date_SKEY"
      },
      {
        "name": "be760ef0-f8a1-4f95-b83a-4a8baf661ad9",
        "fromTable": "Sales Invoices",
        "fromColumn": "DIM_Currency_Accounting_SKEY",
        "toTable": "Accounting Currency",
        "toColumn": "DIM_Currency_SKEY"
      },
      {
        "name": "6bdd77cf-e48a-4d42-af05-d3fd69130d29",
        "fromTable": "Sales Invoices",
        "fromColumn": "DIM_Currency_Regional_SKEY",
        "toTable": "Regional Currency",
        "toColumn": "DIM_Currency_SKEY"
      },
      {
        "name": "0176cc20-65a1-4488-9fe9-31a2152bf7ad",
        "fromTable": "Sales Invoices",
        "fromColumn": "DIM_Customer_Invoice_SKEY",
        "toTable": "Customer",
        "toColumn": "DIM_Customer_SKEY"
      },
      {
        "name": "868463b4-d1d3-4392-9331-8b6885a2f25e",
        "fromTable": "Sales Invoices",
        "fromColumn": "DIM_Product_SKEY",
        "toTable": "Product",
        "toColumn": "DIM_Product_SKEY"
      },
      {
        "name": "7daed5a3-247b-47fb-aae8-26b3b025362c",
        "fromTable": "Sales Invoices",
        "fromColumn": "DIM_Currency_Transaction_SKEY",
        "toTable": "Transaction Currency",
        "toColumn": "DIM_Currency_SKEY"
      },
      {
        "name": "2a890c47-fbf4-44e3-8172-28d21e2a3657",
        "fromTable": "Sales Invoices",
        "fromColumn": "CURR_DIM_GroupSIC_SKEY",
        "toTable": "SIC",
        "toColumn": "DIM_GroupSIC_SKEY"
      },
      {
        "name": "bc3a2e3c-8a21-4584-8f34-dcbded3e7c84",
        "fromTable": "Sales Invoices",
        "fromColumn": "CURR_DIM_GroupSPC_SKEY",
        "toTable": "SPC",
        "toColumn": "DIM_GroupSPC_SKEY"
      },
      {
        "name": "7de17f83-57aa-4d3c-8fc4-2b57368f02ac",
        "fromTable": "Sales Invoices",
        "fromColumn": "DIM_DataForest_SKEY",
        "toTable": "Data Forest",
        "toColumn": "DIM_DataForest_SKEY"
      },
      {
        "name": "7f719858-f645-47ca-9ee0-c548255adbb0",
        "fromTable": "Sales Invoices",
        "fromColumn": "DIM_TgkLegalEntity_SKEY",
        "toTable": "Tagetik Legal Entity",
        "toColumn": "DIM_TgkLegalEntity_SKEY"
      },
      {
        "name": "e21d40a3-2808-4577-a8ee-c19bc507310e",
        "fromTable": "Sales Budgets",
        "fromColumn": "DIM_LegalEntity_SKEY",
        "toTable": "Legal Entity",
        "toColumn": "DIM_LegalEntity_SKEY"
      },
      {
        "name": "27872d43-e3ab-4729-a60f-aaf2ce3fc3bb",
        "fromTable": "Sales Budgets",
        "fromColumn": "DIM_Plant_SKEY",
        "toTable": "Plant",
        "toColumn": "DIM_Plant_SKEY"
      },
      {
        "name": "ba9982bf-c54a-4a16-93e9-dda0e1e5a5ce",
        "fromTable": "Sales Budgets",
        "fromColumn": "DIM_Date_Period_SKEY",
        "toTable": "Date",
        "toColumn": "DIM_Date_SKEY"
      },
      {
        "name": "e2832985-2483-4584-bef0-6d689589fcdd",
        "fromTable": "Sales Budgets",
        "fromColumn": "DIM_Currency_Accounting_SKEY",
        "toTable": "Accounting Currency",
        "toColumn": "DIM_Currency_SKEY"
      },
      {
        "name": "50b46502-d654-4f4f-bde0-9d18618fb064",
        "fromTable": "Sales Budgets",
        "fromColumn": "DIM_Currency_Regional_SKEY",
        "toTable": "Regional Currency",
        "toColumn": "DIM_Currency_SKEY"
      },
      {
        "name": "8cbac191-e257-4f59-a132-919f584d8321",
        "fromTable": "Sales Budgets",
        "fromColumn": "DIM_Customer_SKEY",
        "toTable": "Customer",
        "toColumn": "DIM_Customer_SKEY"
      },
      {
        "name": "0a864cb1-e9f8-4c84-9d65-8cf25d7fb2e5",
        "fromTable": "Sales Budgets",
        "fromColumn": "DIM_Product_SKEY",
        "toTable": "Product",
        "toColumn": "DIM_Product_SKEY"
      },
      {
        "name": "074b12ca-41cd-4e91-8bb8-abb5216abae7",
        "fromTable": "Sales Budgets",
        "fromColumn": "CURR_DIM_GroupSIC_SKEY",
        "toTable": "SIC",
        "toColumn": "DIM_GroupSIC_SKEY"
      },
      {
        "name": "2c02c44c-48ba-4055-805b-de21258050aa",
        "fromTable": "Sales Budgets",
        "fromColumn": "CURR_DIM_GroupSPC_SKEY",
        "toTable": "SPC",
        "toColumn": "DIM_GroupSPC_SKEY"
      },
      {
        "name": "f64f47c9-d3cd-4493-b948-1f174d8ddd35",
        "fromTable": "Sales Budgets",
        "fromColumn": "DIM_DataForest_SKEY",
        "toTable": "Data Forest",
        "toColumn": "DIM_DataForest_SKEY"
      },
      {
        "name": "65fa11c8-60be-4a51-8a50-60e89238aa81",
        "fromTable": "Sales Budgets",
        "fromColumn": "DIM_TgkLegalEntity_SKEY",
        "toTable": "Tagetik Legal Entity",
        "toColumn": "DIM_TgkLegalEntity_SKEY"
      },
      {
        "name": "c34d2cfd-c12a-4ef1-8137-0528640393d6",
        "fromTable": "Sales Orders",
        "fromColumn": "DIM_LegalEntity_SKEY",
        "toTable": "Legal Entity",
        "toColumn": "DIM_LegalEntity_SKEY"
      },
      {
        "name": "d76e4434-589a-4d5d-aee4-c2a9debd018d",
        "fromTable": "Sales Orders",
        "fromColumn": "DIM_Plant_SKEY",
        "toTable": "Plant",
        "toColumn": "DIM_Plant_SKEY"
      },
      {
        "name": "35de5a8f-22a5-4798-8655-38e39d2ac8d9",
        "fromTable": "Sales Orders",
        "fromColumn": "DIM_Currency_Transaction_SKEY",
        "toTable": "Transaction Currency",
        "toColumn": "DIM_Currency_SKEY"
      },
      {
        "name": "2f255716-b6ed-4c1d-989f-1ae382a7847c",
        "fromTable": "Sales Orders",
        "fromColumn": "DIM_Currency_Accounting_SKEY",
        "toTable": "Accounting Currency",
        "toColumn": "DIM_Currency_SKEY"
      },
      {
        "name": "86bcb634-a276-4606-9f5b-9230ce53d6c6",
        "fromTable": "Sales Orders",
        "fromColumn": "DIM_Currency_Regional_SKEY",
        "toTable": "Regional Currency",
        "toColumn": "DIM_Currency_SKEY"
      },
      {
        "name": "5488e995-36e2-49f3-9693-e213097f388a",
        "fromTable": "Sales Orders",
        "fromColumn": "DIM_Customer_Invoice_SKEY",
        "toTable": "Customer",
        "toColumn": "DIM_Customer_SKEY"
      },
      {
        "name": "34810958-4983-40f1-90a3-9f94b0990c2e",
        "fromTable": "Sales Orders",
        "fromColumn": "DIM_Product_SKEY",
        "toTable": "Product",
        "toColumn": "DIM_Product_SKEY"
      },
      {
        "name": "230cf236-0373-4bea-ad5e-aa78bdff143b",
        "fromTable": "Sales Orders",
        "fromColumn": "CURR_DIM_GroupSIC_SKEY",
        "toTable": "SIC",
        "toColumn": "DIM_GroupSIC_SKEY"
      },
      {
        "name": "4fe0fadd-6cd0-4273-ab1e-1facef8848d8",
        "fromTable": "Sales Orders",
        "fromColumn": "CURR_DIM_GroupSPC_SKEY",
        "toTable": "SPC",
        "toColumn": "DIM_GroupSPC_SKEY"
      },
      {
        "name": "c83258dd-319e-407f-a438-4a8f2c914f80",
        "fromTable": "Sales Orders",
        "fromColumn": "DIM_DataForest_SKEY",
        "toTable": "Data Forest",
        "toColumn": "DIM_DataForest_SKEY"
      },
      {
        "name": "1babb87c-13fb-45fe-863c-5650cf4808f7",
        "fromTable": "Sales Orders",
        "fromColumn": "DIM_Date_Invoice_SKEY",
        "toTable": "Date",
        "toColumn": "DIM_Date_SKEY"
      },
      {
        "name": "8d7a00e0-33c7-4994-8a5d-d756d4ae31b7",
        "fromTable": "Sales Orders",
        "fromColumn": "DIM_Customerdeliveryaddress_SKEY",
        "toTable": "Customer Delivery Address",
        "toColumn": "DIM_Customerdeliveryaddress_SKEY"
      },
      {
        "name": "cccb6033-3cd8-4e04-8a53-b51b32fba9db",
        "fromTable": "Sales Orders",
        "fromColumn": "DIM_TgkLegalEntity_SKEY",
        "toTable": "Tagetik Legal Entity",
        "toColumn": "DIM_TgkLegalEntity_SKEY"
      },
      {
        "name": "9ed7624f-b695-4ae6-9b17-153d733f1464",
        "fromTable": "Customer Delivery Address",
        "fromColumn": "DIM_ShalePlay_SKEY",
        "toTable": "Customer Delivery Address ShalePlay",
        "toColumn": "DIM_ShalePlay_SKEY"
      },
      {
        "name": "8224558c-f710-4bd1-a09d-0c791e94b82e",
        "fromTable": "RMA",
        "fromColumn": "DIM_DataForest_SKEY",
        "toTable": "Data Forest",
        "toColumn": "DIM_DataForest_SKEY"
      },
      {
        "name": "188233aa-2053-480d-b48c-48ef3001bf63",
        "fromTable": "RMA",
        "fromColumn": "DIM_Plant_SKEY",
        "toTable": "Plant",
        "toColumn": "DIM_Plant_SKEY"
      },
      {
        "name": "c11781fb-d482-41f2-a71f-3cbf78f236b8",
        "fromTable": "RMA",
        "fromColumn": "DIM_DateCompleted_SKEY",
        "toTable": "Date",
        "toColumn": "DIM_Date_SKEY"
      },
      {
        "name": "d3bfa0c4-46d0-4719-b08b-146800adf4c9",
        "fromTable": "RMA",
        "fromColumn": "CURR_DIM_GroupSPC_SKEY",
        "toTable": "SPC",
        "toColumn": "DIM_GroupSPC_SKEY"
      },
      {
        "name": "9ebd95fa-e906-44dc-b826-80e15be0b10d",
        "fromTable": "RMA",
        "fromColumn": "CURR_DIM_GroupSIC_SKEY",
        "toTable": "SIC",
        "toColumn": "DIM_GroupSIC_SKEY"
      },
      {
        "name": "576460f2-5fb0-423e-b2a4-5063d8c3613b",
        "fromTable": "RMA",
        "fromColumn": "DIM_TgkLegalEntity_SKEY",
        "toTable": "Tagetik Legal Entity",
        "toColumn": "DIM_TgkLegalEntity_SKEY"
      },
      {
        "name": "b78f4c04-77a4-4e06-8b26-d33f7901fa54",
        "fromTable": "RMA",
        "fromColumn": "DIM_Customer_Invoice_SKEY",
        "toTable": "Customer",
        "toColumn": "DIM_Customer_SKEY"
      },
      {
        "name": "eacd5247-a693-4dd8-b696-eed2bae4f249",
        "fromTable": "RMA",
        "fromColumn": "DIM_Customerdeliveryaddress_SKEY",
        "toTable": "Customer Delivery Address",
        "toColumn": "DIM_Customerdeliveryaddress_SKEY"
      },
      {
        "name": "d9d8f42d-6429-4078-a55c-ceba8b654a85",
        "fromTable": "RMA",
        "fromColumn": "DIM_Product_SKEY",
        "toTable": "Product",
        "toColumn": "DIM_Product_SKEY"
      },
      {
        "name": "632edaf8-6243-441d-9508-855f2a7f8471",
        "fromTable": "RMA",
        "fromColumn": "DIM_LegalEntity_SKEY",
        "toTable": "Legal Entity",
        "toColumn": "DIM_LegalEntity_SKEY"
      },
      {
        "name": "439631af-e081-443b-a02e-d64d0723352a",
        "fromTable": "RMA",
        "fromColumn": "DIM_Currency_Transaction_SKEY",
        "toTable": "Transaction Currency",
        "toColumn": "DIM_Currency_SKEY"
      },
      {
        "name": "20f3633f-db8c-4471-ba35-8b4c0a41d8f8",
        "fromTable": "RMA",
        "fromColumn": "DIM_Currency_Accounting_SKEY",
        "toTable": "Accounting Currency",
        "toColumn": "DIM_Currency_SKEY"
      },
      {
        "name": "92a84184-f23d-4782-b9ad-20db2dd69461",
        "fromTable": "RMA",
        "fromColumn": "DIM_Currency_Regional_SKEY",
        "toTable": "Regional Currency",
        "toColumn": "DIM_Currency_SKEY"
      },
      {
        "name": "8b3bcbf0-c356-4872-a80c-46e2dfe27d7c",
        "fromTable": "Sales Invoices",
        "fromColumn": "DIM_Customerdeliveryaddress_SKEY",
        "toTable": "Customer Delivery Address",
        "toColumn": "DIM_Customerdeliveryaddress_SKEY"
      },
      {
        "name": "a4d9df3d-5d0b-42e1-afd0-cf0430dab8e8",
        "fromTable": "Sales Orders",
        "fromColumn": "DIM_SalesOrderLine_SKEY",
        "toTable": "Sales Order Bridge",
        "toColumn": "DIM_SalesOrderLine_SKEY"
      },
      {
        "name": "354fb328-ac8b-4161-aeae-10e6e1e18b76",
        "fromTable": "Sales Invoices",
        "fromColumn": "DIM_SalesInvoiceLine_SKEY",
        "toTable": "Sales Invoice Bridge",
        "toColumn": "DIM_SalesInvoiceLine_SKEY"
      },
      {
        "name": "1e64f56a-a1fa-43d0-8841-11b041c2df75",
        "fromTable": "Sales Invoice Bridge",
        "fromColumn": "DIM_SalesOrderLine_SKEY",
        "toTable": "Sales Order Bridge",
        "toColumn": "DIM_SalesOrderLine_SKEY",
        "crossFilteringBehavior": "bothDirections"
      },
      {
        "name": "55c2809e-ca2f-4e24-9fe0-95a23316da5b",
        "fromTable": "RMA",
        "fromColumn": "DIM_SalesOrderLine_SKEY",
        "toTable": "Sales Order Bridge",
        "toColumn": "DIM_SalesOrderLine_SKEY"
      },
      {
        "name": "5250508f-107c-41f9-8ce5-7938f64c5cc1",
        "fromTable": "Customer",
        "fromColumn": "DIM_CustomerHierarchy_SKEY",
        "toTable": "Customer Hierarchy",
        "toColumn": "CustomerHierarchyHashKey"
      },
      {
        "name": "5984172e-0d37-44ea-ba69-d595d3bba33c",
        "fromTable": "Sales Costs",
        "fromColumn": "DIM_DataForest_SKEY",
        "toTable": "Data Forest",
        "toColumn": "DIM_DataForest_SKEY"
      },
      {
        "name": "24a10e83-e55d-45cb-aa75-4c8a9ca88268",
        "fromTable": "Sales Costs",
        "fromColumn": "DIM_SalesInvoiceLine_SKEY",
        "toTable": "Sales Invoice Bridge",
        "toColumn": "DIM_SalesInvoiceLine_SKEY"
      },
      {
        "name": "f627dd19-bc59-4181-a2f7-47ed85a51f28",
        "fromTable": "Sales Costs",
        "fromColumn": "DIM_LegalEntity_SKEY",
        "toTable": "Legal Entity",
        "toColumn": "DIM_LegalEntity_SKEY"
      },
      {
        "name": "2940f496-7f16-44c4-8252-8cc9f46138f1",
        "fromTable": "Sales Costs",
        "fromColumn": "DIM_TgkLegalEntity_SKEY",
        "toTable": "Tagetik Legal Entity",
        "toColumn": "DIM_TgkLegalEntity_SKEY"
      },
      {
        "name": "da578e58-7768-42ea-892e-ef1b04c9ea35",
        "fromTable": "Sales Costs",
        "fromColumn": "DIM_Plant_SKEY",
        "toTable": "Plant",
        "toColumn": "DIM_Plant_SKEY"
      },
      {
        "name": "acbf8d18-a0e9-498c-b33a-fe36e1517a4c",
        "fromTable": "Sales Costs",
        "fromColumn": "DIM_Date_Invoice_SKEY",
        "toTable": "Date",
        "toColumn": "DIM_Date_SKEY"
      },
      {
        "name": "9695264e-3f33-4881-9b44-47a564426db1",
        "fromTable": "Sales Costs",
        "fromColumn": "DIM_Currency_Accounting_SKEY",
        "toTable": "Accounting Currency",
        "toColumn": "DIM_Currency_SKEY"
      },
      {
        "name": "adb11868-2fec-4038-b5f6-157debe93715",
        "fromTable": "Sales Costs",
        "fromColumn": "DIM_Customer_SKEY",
        "toTable": "Customer",
        "toColumn": "DIM_Customer_SKEY"
      },
      {
        "name": "d9fb37cc-c7c4-4a8a-98af-0122bea688f0",
        "fromTable": "Sales Costs",
        "fromColumn": "DIM_Customerdeliveryaddress_SKEY",
        "toTable": "Customer Delivery Address",
        "toColumn": "DIM_Customerdeliveryaddress_SKEY"
      },
      {
        "name": "62a15ff7-a778-4e04-b294-b9fc3a4f2d93",
        "fromTable": "Sales Costs",
        "fromColumn": "DIM_Currency_Regional_SKEY",
        "toTable": "Regional Currency",
        "toColumn": "DIM_Currency_SKEY"
      },
      {
        "name": "c5f4d9ff-7f54-4859-bfa8-3d27ec4167e5",
        "fromTable": "Sales Costs",
        "fromColumn": "DIM_Currency_Transaction_SKEY",
        "toTable": "Transaction Currency",
        "toColumn": "DIM_Currency_SKEY"
      },
      {
        "name": "e4671910-97c0-4e7a-8fb8-9d8ba329c0e2",
        "fromTable": "Sales Costs",
        "fromColumn": "DIM_Product_SKEY",
        "toTable": "Product",
        "toColumn": "DIM_Product_SKEY"
      },
      {
        "name": "51b22ca6-38f0-4902-8985-0b9b7a35a7b8",
        "fromTable": "Sales Costs",
        "fromColumn": "CURR_DIM_GroupSIC_SKEY",
        "toTable": "SIC",
        "toColumn": "DIM_GroupSIC_SKEY"
      },
      {
        "name": "248036f1-f0ba-42c2-8d68-3945a14d1a6e",
        "fromTable": "Sales Costs",
        "fromColumn": "CURR_DIM_GroupSPC_SKEY",
        "toTable": "SPC",
        "toColumn": "DIM_GroupSPC_SKEY"
      },
      {
        "name": "ae9e5094-2948-4bbe-96a1-d405e1b663d0",
        "fromTable": "Sales Budgets",
        "fromColumn": "DIM_Currency_Transaction_SKEY",
        "toTable": "Transaction Currency",
        "toColumn": "DIM_Currency_SKEY"
      },
      {
        "name": "a69c411b-10d4-4c43-8b65-1bc29fe07b55",
        "fromTable": "Sales Budgets",
        "fromColumn": "DIM_Customerdeliveryaddress_SKEY",
        "toTable": "Customer Delivery Address",
        "toColumn": "DIM_Customerdeliveryaddress_SKEY"
      },
      {
        "name": "c1f8c959-1ea2-42b5-8820-0eaa02431bc8",
        "fromTable": "Sales Forecasts",
        "fromColumn": "DIM_Currency_Accounting_SKEY",
        "toTable": "Accounting Currency",
        "toColumn": "DIM_Currency_SKEY"
      },
      {
        "name": "ae801a2a-ab0a-475f-8026-904f54c3bb37",
        "fromTable": "Sales Forecasts",
        "fromColumn": "DIM_Currency_Transaction_SKEY",
        "toTable": "Transaction Currency",
        "toColumn": "DIM_Currency_SKEY"
      },
      {
        "name": "4f282aeb-07fe-45eb-82a6-57c0a1e32e37",
        "fromTable": "Sales Forecasts",
        "fromColumn": "DIM_Currency_Regional_SKEY",
        "toTable": "Regional Currency",
        "toColumn": "DIM_Currency_SKEY"
      },
      {
        "name": "158536c4-8fdf-4970-b2c3-9fe4ab835cf5",
        "fromTable": "Sales Forecasts",
        "fromColumn": "DIM_Date_Period_SKEY",
        "toTable": "Date",
        "toColumn": "DIM_Date_SKEY"
      },
      {
        "name": "64d9f044-47e2-459d-9bb8-c74dde14913c",
        "fromTable": "Sales Forecasts",
        "fromColumn": "DIM_LegalEntity_SKEY",
        "toTable": "Legal Entity",
        "toColumn": "DIM_LegalEntity_SKEY"
      },
      {
        "name": "57ceba97-3a39-4091-a20b-4f6f4270ef89",
        "fromTable": "Sales Forecasts",
        "fromColumn": "DIM_TgkLegalEntity_SKEY",
        "toTable": "Tagetik Legal Entity",
        "toColumn": "DIM_TgkLegalEntity_SKEY"
      },
      {
        "name": "c38cfc82-10e2-4531-898c-3ba2cfcb2e91",
        "fromTable": "Sales Forecasts",
        "fromColumn": "DIM_Plant_SKEY",
        "toTable": "Plant",
        "toColumn": "DIM_Plant_SKEY"
      },
      {
        "name": "5d365670-88fc-4b71-bab7-8f615f6d0dfb",
        "fromTable": "Sales Forecasts",
        "fromColumn": "DIM_Customer_Invoice_SKEY",
        "toTable": "Customer",
        "toColumn": "DIM_Customer_SKEY"
      },
      {
        "name": "f331dc27-3cc0-438d-91bf-414c265f7a69",
        "fromTable": "Sales Forecasts",
        "fromColumn": "DIM_Product_SKEY",
        "toTable": "Product",
        "toColumn": "DIM_Product_SKEY"
      },
      {
        "name": "69363b71-1f09-42f6-900d-52f6ab09dc1e",
        "fromTable": "Sales Forecasts",
        "fromColumn": "CURR_DIM_GroupSIC_SKEY",
        "toTable": "SIC",
        "toColumn": "DIM_GroupSIC_SKEY"
      },
      {
        "name": "4a8ce1ab-9f60-4a07-a1a9-90222306aedf",
        "fromTable": "Sales Forecasts",
        "fromColumn": "CURR_DIM_GroupSPC_SKEY",
        "toTable": "SPC",
        "toColumn": "DIM_GroupSPC_SKEY"
      },
      {
        "name": "3f445eeb-b69c-4842-97c2-25dc2416d048",
        "fromTable": "Sales Forecasts",
        "fromColumn": "DIM_Customerdeliveryaddress_SKEY",
        "toTable": "Customer Delivery Address",
        "toColumn": "DIM_Customerdeliveryaddress_SKEY"
      },
      {
        "name": "a77b4866-fe61-4aec-b9b7-520bc00b5476",
        "fromTable": "Date Range",
        "fromColumn": "DIM_Date_SKEY",
        "toTable": "Date",
        "toColumn": "DIM_Date_SKEY",
        "crossFilteringBehavior": "bothDirections"
      },
      {
        "name": "5bd1254d-7404-42b5-a675-b7babaab342a",
        "fromTable": "Date Range Bis",
        "fromColumn": "DIM_Date_SKEY",
        "toTable": "Date",
        "toColumn": "DIM_Date_SKEY",
        "crossFilteringBehavior": "bothDirections"
      }
    ],
    "roles": [
      {
        "name": "NAMBI",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "BAllyn@unimin.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "GHard@unimin.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "jquinn@unimin.com",
            "identityProvider": "AzureAD"
          }
        ],
        "tablePermissions": [
          {
            "name": "Customer",
            "filterExpression": "[DIM_DataForest_SKEY]=\"20_104\"  || [DIM_DataForest_SKEY]=BLANK()"
          },
          {
            "name": "Legal Entity",
            "filterExpression": "[DIM_DataForest_SKEY]=\"20_104\"  || [DIM_DataForest_SKEY]=BLANK()"
          },
          {
            "name": "Plant",
            "filterExpression": "[DIM_DataForest_SKEY]=\"20_104\"  || [DIM_DataForest_SKEY]=BLANK()"
          },
          {
            "name": "Product",
            "filterExpression": "[DIM_DataForest_SKEY]=\"20_104\"  || [DIM_DataForest_SKEY]=BLANK()"
          },
          {
            "name": "Sales Invoices",
            "filterExpression": "[DIM_DataForest_SKEY]=\"20_104\" || [DIM_DataForest_SKEY]=BLANK()"
          },
          {
            "name": "Sales Orders",
            "filterExpression": "[DIM_DataForest_SKEY]=\"20_104\" || [DIM_DataForest_SKEY]=BLANK()"
          },
          {
            "name": "Data Forest",
            "filterExpression": "[Data Forest Id]=\"20_104\""
          },
          {
            "name": "Accounting Currency",
            "filterExpression": "[DIM_DataForest_SKEY]=\"20_104\"  || [DIM_DataForest_SKEY]=BLANK()"
          },
          {
            "name": "Regional Currency",
            "filterExpression": "[DIM_DataForest_SKEY]=\"20_104\"  || [DIM_DataForest_SKEY]=BLANK()"
          },
          {
            "name": "Sales Budgets",
            "filterExpression": "[DIM_DataForest_SKEY]=\"20_104\" || [DIM_DataForest_SKEY]=BLANK()"
          },
          {
            "name": "Transaction Currency",
            "filterExpression": "[DIM_DataForest_SKEY]=\"20_104\"  || [DIM_DataForest_SKEY]=BLANK()"
          },
          {
            "name": "Customer Delivery Address",
            "filterExpression": "[DIM_DataForest_SKEY]=\"20_104\"  || [DIM_DataForest_SKEY]=BLANK()"
          },
          {
            "name": "Customer Delivery Address ShalePlay",
            "filterExpression": "[DIM_DataForest_SKEY]=\"20_104\"  || [DIM_DataForest_SKEY]=BLANK()"
          },
          {
            "name": "RMA",
            "filterExpression": "[DIM_DataForest_SKEY]=\"20_104\" || [DIM_DataForest_SKEY]=BLANK()"
          },
          {
            "name": "Sales Invoice Bridge",
            "filterExpression": "[DIM_DataForest_SKEY]=\"20_104\"  || [DIM_DataForest_SKEY]=BLANK()"
          },
          {
            "name": "Sales Order Bridge",
            "filterExpression": "[DIM_DataForest_SKEY]=\"20_104\"  || [DIM_DataForest_SKEY]=BLANK()"
          },
          {
            "name": "Sales Costs",
            "filterExpression": "[DIM_DataForest_SKEY]=\"20_104\" || [DIM_DataForest_SKEY]=BLANK()"
          },
          {
            "name": "Customer Hierarchy",
            "filterExpression": "[DIM_DataForest_SKEY]=\"20_104\" || [DIM_DataForest_SKEY]=BLANK()"
          }
        ]
      },
      {
        "name": "MEXBI",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "ribarra@gmp.com.mx",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "sgonzalez@gmp.com.mx",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "gvillarreal@gmp.com.mx",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "rcantu@gmp.com.mx",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "ileyva@gmp.com.mx",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "asobrevilla@gmp.com.mx",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "jduran@gmp.com.mx",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "pmartinez@gmp.com.mx",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "jcaballero@gmp.com.mx",
            "identityProvider": "AzureAD"
          }
        ],
        "tablePermissions": [
          {
            "name": "Customer",
            "filterExpression": "[DIM_DataForest_SKEY]=\"20_103\"  || [DIM_DataForest_SKEY]=BLANK()"
          },
          {
            "name": "Legal Entity",
            "filterExpression": "[DIM_DataForest_SKEY]=\"20_103\"  || [DIM_DataForest_SKEY]=BLANK()"
          },
          {
            "name": "Plant",
            "filterExpression": "[DIM_DataForest_SKEY]=\"20_103\"  || [DIM_DataForest_SKEY]=BLANK()"
          },
          {
            "name": "Product",
            "filterExpression": "[DIM_DataForest_SKEY]=\"20_103\"  || [DIM_DataForest_SKEY]=BLANK()"
          },
          {
            "name": "Sales Invoices",
            "filterExpression": "[DIM_DataForest_SKEY]=\"20_103\" || [DIM_DataForest_SKEY]=BLANK()"
          },
          {
            "name": "Sales Orders",
            "filterExpression": "[DIM_DataForest_SKEY]=\"20_103\" || [DIM_DataForest_SKEY]=BLANK()"
          },
          {
            "name": "Data Forest",
            "filterExpression": "[Data Forest Id]=\"20_103\""
          },
          {
            "name": "Accounting Currency",
            "filterExpression": "[DIM_DataForest_SKEY]=\"20_103\"  || [DIM_DataForest_SKEY]=BLANK()"
          },
          {
            "name": "Regional Currency",
            "filterExpression": "[DIM_DataForest_SKEY]=\"20_103\"  || [DIM_DataForest_SKEY]=BLANK()"
          },
          {
            "name": "Sales Budgets",
            "filterExpression": "[DIM_DataForest_SKEY]=\"20_103\" || [DIM_DataForest_SKEY]=BLANK()"
          },
          {
            "name": "Transaction Currency",
            "filterExpression": "[DIM_DataForest_SKEY]=\"20_103\"  || [DIM_DataForest_SKEY]=BLANK()"
          },
          {
            "name": "Customer Delivery Address",
            "filterExpression": "[DIM_DataForest_SKEY]=\"20_103\"  || [DIM_DataForest_SKEY]=BLANK()"
          },
          {
            "name": "Customer Delivery Address ShalePlay",
            "filterExpression": "[DIM_DataForest_SKEY]=\"20_103\"  || [DIM_DataForest_SKEY]=BLANK()"
          },
          {
            "name": "RMA",
            "filterExpression": "[DIM_DataForest_SKEY]=\"20_103\" || [DIM_DataForest_SKEY]=BLANK()"
          },
          {
            "name": "Sales Invoice Bridge",
            "filterExpression": "[DIM_DataForest_SKEY]=\"20_103\"  || [DIM_DataForest_SKEY]=BLANK()"
          },
          {
            "name": "Sales Order Bridge",
            "filterExpression": "[DIM_DataForest_SKEY]=\"20_103\"  || [DIM_DataForest_SKEY]=BLANK()"
          },
          {
            "name": "Sales Costs",
            "filterExpression": "[DIM_DataForest_SKEY]=\"20_103\" || [DIM_DataForest_SKEY]=BLANK()"
          },
          {
            "name": "Customer Hierarchy",
            "filterExpression": "[DIM_DataForest_SKEY]=\"20_103\"  || [DIM_DataForest_SKEY]=BLANK()"
          }
        ]
      },
      {
        "name": "ALLBI",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "Benny.Loix@sibelco.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "Toon.Augustyns@sibelco.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "Anne.Van.Loy@sibelco.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "Anne.Bouter@sibelco.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "Hugo.Vandormael@sibelco.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "Kurt.Decat@sibelco.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "Jan.Steukers@sibelco.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "Frank.Kellens@sibelco.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "Ralf.Loyen@sibelco.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "ddan-crisan@unimin.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "raloy@unimin.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "cjones@unimin.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "dataservice@sibelco.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "Anne-Marie.Snepvangers@sibelco.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "Saar.Gillis@sibelco.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "Dominique.Dhaenens@sibelco.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "Geert.Goijens@sibelco.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "RSomayajula@unimin.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "RStegmeier@unimin.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "CKemmerer@unimin.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "BSkelly@unimin.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "PGamma@unimin.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "MDeMasi@unimin.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "MIdrees@unimin.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "SWimalasooriya@unimin.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "JCorera@unimin.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "RSpear@unimin.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "AGopalakrishnan@unimin.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "DFagan@unimin.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "edilson.santos@sibelco.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "FHilmy@unimin.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "PRajagopal@unimin.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "ZBaloch@unimin.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "AEich@unimin.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "JHunt@unimin.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "JKilbane@unimin.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "JLorenzoni@unimin.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "SBrock@unimin.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "PPhillips@unimin.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "swestmoreland@unimin.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "mgarza@gmp.com.mx",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "Yannick.Verthongen@sibelco.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "SJha@unimin.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "miriam.vencken@sibelco.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "yvan.hoefman@sibelco.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "DPetersen@unimin.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "MSmerekanicz@unimin.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "Nele.Van.Peteghem@sibelco.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "RBlanc@unimin.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "GMullet@unimin.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "CGastony@unimin.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "Steven.Devlies@sibelco.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "Sophie.Chevallier@sibelco.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "CGoodwin@unimin.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "CBanker@unimin.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "CBerry@unimin.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "igarza@gmp.com.mx",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "Wim.Vanpeel@sibelco.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "Spreston@unimin.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "Moskam@unimin.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "Eduardo.Sainz@sibelco.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "bmosher@unimin.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "eopera@unimin.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "JStrehl@unimin.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "MBencic@unimin.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "agutierrez@gmp.com.mx",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "ajimenez@gmp.com.mx",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "adeluca@unimin.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "bkavanagh@unimin.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "bwarcup@unimin.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "cchapman@unimin.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "chernandez@gmp.com.mx",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "CLeBlanc@unimin.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "Clay.Collins@unimin.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "dklewsaat@unimin.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "DMcCaghren@unimin.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "dmjohnson@unimin.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "eparras@gmp.com.mx",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "fzatta@unimin.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "gwebb@gmp.com.mx",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "gchavez@gmp.com.mx",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "Hmontgomery@unimin.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "igonzalez@gmp.com.mx",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "jislas@gmp.com.mx",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "JMigyanko@unimin.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "kfuller@unimin.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "kbirdwell@unimin.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "LGully@unimin.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "lcantu@gmp.com.mx",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "MHolmes@unimin.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "myanez@gmp.com.mx",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "mpigage@unimin.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "Mdavis@unimin.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "pcharbonneau@unimin.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "rlight@unimin.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "RRicker@unimin.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "respinoza@gmp.com.mx",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "Rpataky@unimin.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "RWeathers@unimin.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "Sgutierrez@unimin.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "tbaranowski@unimin.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "rcotsonas@unimin.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "NHolobinka@unimin.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "Matthew.Lewtas@sibelco.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "Felice.Pollio@sibelco.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "dhingorani@unimin.com",
            "identityProvider": "AzureAD"
          }
        ]
      }
    ],
    "annotations": [
      {
        "name": "ASW-DEFAULT-DIAGRAM",
        "value": "{\"Version\":1,\"Name\":\"default\",\"Tables\":[{\"TableName\":\"Sales Invoices\",\"X\":910,\"Y\":910,\"Z\":1,\"Width\":225,\"Height\":275},{\"TableName\":\"Customer\",\"X\":1210,\"Y\":910,\"Z\":2,\"Width\":225,\"Height\":275},{\"TableName\":\"Customer Delivery Address\",\"X\":910,\"Y\":1210,\"Z\":3,\"Width\":225,\"Height\":275},{\"TableName\":\"Sales Invoice Bridge\",\"X\":910,\"Y\":610,\"Z\":4,\"Width\":225,\"Height\":275},{\"TableName\":\"Date\",\"X\":610,\"Y\":910,\"Z\":5,\"Width\":225,\"Height\":275},{\"TableName\":\"Tagetik Legal Entity\",\"X\":1210,\"Y\":1210,\"Z\":6,\"Width\":225,\"Height\":275},{\"TableName\":\"Plant\",\"X\":1210,\"Y\":610,\"Z\":7,\"Width\":225,\"Height\":275},{\"TableName\":\"SPC\",\"X\":610,\"Y\":1210,\"Z\":8,\"Width\":225,\"Height\":275},{\"TableName\":\"SIC\",\"X\":610,\"Y\":610,\"Z\":9,\"Width\":225,\"Height\":275},{\"TableName\":\"Transaction Currency\",\"X\":1510,\"Y\":910,\"Z\":10,\"Width\":225,\"Height\":275},{\"TableName\":\"Legal Entity\",\"X\":910,\"Y\":1510,\"Z\":11,\"Width\":225,\"Height\":275},{\"TableName\":\"Regional Currency\",\"X\":910,\"Y\":310,\"Z\":12,\"Width\":225,\"Height\":275},{\"TableName\":\"Accounting Currency\",\"X\":310,\"Y\":910,\"Z\":13,\"Width\":225,\"Height\":275},{\"TableName\":\"Product\",\"X\":1510,\"Y\":1210,\"Z\":14,\"Width\":225,\"Height\":275},{\"TableName\":\"Data Forest\",\"X\":1510,\"Y\":610,\"Z\":15,\"Width\":225,\"Height\":275},{\"TableName\":\"Sales Orders\",\"X\":1210,\"Y\":1510,\"Z\":16,\"Width\":225,\"Height\":275},{\"TableName\":\"RMA\",\"X\":1210,\"Y\":310,\"Z\":17,\"Width\":225,\"Height\":275},{\"TableName\":\"Sales Costs\",\"X\":610,\"Y\":1510,\"Z\":18,\"Width\":225,\"Height\":275},{\"TableName\":\"Sales Budgets\",\"X\":310,\"Y\":1210,\"Z\":19,\"Width\":225,\"Height\":275},{\"TableName\":\"Sales Forecasts\",\"X\":610,\"Y\":310,\"Z\":20,\"Width\":225,\"Height\":275},{\"TableName\":\"Date Range\",\"X\":310,\"Y\":610,\"Z\":21,\"Width\":225,\"Height\":275},{\"TableName\":\"Date Range Bis\",\"X\":310,\"Y\":1510,\"Z\":22,\"Width\":225,\"Height\":275},{\"TableName\":\"Sales Order Bridge\",\"X\":1510,\"Y\":1510,\"Z\":23,\"Width\":225,\"Height\":275},{\"TableName\":\"Customer Delivery Address ShalePlay\",\"X\":1510,\"Y\":310,\"Z\":24,\"Width\":225,\"Height\":275},{\"TableName\":\"Customer Hierarchy\",\"X\":310,\"Y\":310,\"Z\":25,\"Width\":225,\"Height\":275},{\"TableName\":\"Benchmark\",\"X\":10,\"Y\":10,\"Z\":26,\"Width\":225,\"Height\":275}]}"
      }
    ]
  }
}